import {text,facts} from './api-v1.js';
import {validateWorkspaceErvHumanReadV1,type WorkspaceErvHumanReadV1,type WorkspaceErvHumanDecisionV1} from '../../contracts/src/workspace-erv-human-v1.js';
import type {WorkspaceContextReadbackV1} from '../../contracts/src/workspace-context-selection-v1.js';
import type {createWorkspaceContextSelectionV1,WorkspaceModuleViewRequestV1} from './context-selection-v1.js';
export function createWorkspaceErvHumanV1(o:{main:HTMLElement;context:ReturnType<typeof createWorkspaceContextSelectionV1>;signal:AbortSignal;refreshNativeSources:()=>Promise<boolean>}){
 const root=document.createElement('section'),detail=document.createElement('div'),status=text('p',''),diff=text('p',''),select=document.createElement('select'),selectedAction=text('p',''),actions=['REVIEW','QUERY','APPROVE_LOCAL_EVIDENCE_ONLY'] as const,next=['REVIEWED','QUERY_PENDING','APPROVED'].map(s=>s+'_LOCAL_EVIDENCE_ONLY');root.id='shell.erv-human';root.className='module-view-editor';status.setAttribute('role','status');selectedAction.id='shell.erv-human.selected-action';selectedAction.dataset.humanSelectedAction='';selectedAction.style.overflowWrap='anywhere';select.setAttribute('aria-describedby',selectedAction.id);select.setAttribute('aria-label','Fachliche Evidenzaktion');actions.forEach((s,i)=>{const option=text('option',['Prüfen','Rückfrage','Getrennte lokale Evidenzfreigabe'][i]!) as HTMLOptionElement;option.value=s;select.append(option);});root.append(text('h2','Native Fachentscheidung — nur lokale Evidenz'),text('p','Keine Buchung, Zahlung oder produktive Ausführung. Führend: PAN472_TARGET_SQLITE.'),status,detail,select,selectedAction,diff);
 let c:WorkspaceContextReadbackV1|null=null,v:WorkspaceErvHumanReadV1|null=null,p:WorkspaceErvHumanDecisionV1|null=null,csrf:string|undefined,busy=false,attempted=false,expected='';
 const live=(t:WorkspaceContextReadbackV1)=>!o.signal.aborted&&c===t&&o.context.current()===t&&t.lease.expiresAtMs>Date.now();
 function button(label:string,fn:()=>void){const b=text('button',label) as HTMLButtonElement;b.type='button';b.addEventListener('click',fn,{signal:o.signal});root.append(b);return b;}
 const preview=button('Fachentscheidung vorschauen',()=>{if(!c||!live(c)||preview.disabled||!v)return;const i=select.selectedIndex;expected=next[i]!;p=Object.freeze({schemaVersion:'pansphaira.erv-human/decision/v1',invoiceId:v.invoiceId,effectId:'synthetic:human-'+crypto.randomUUID(),transportId:'synthetic:human-'+crypto.randomUUID(),expectedNativeRevision:v.nativeRevision,expectedProposalRevision:v.proposalRevision,proposalDigest:v.proposalDigest,action:actions[i]!});attempted=false;diff.textContent='Vorher / Nachher: '+v.state+' → '+expected+' · Humanrevision '+v.proposalRevision+' → '+(v.proposalRevision+1);state('HUMAN_PREVIEW_ONLY');}),confirm=button('Genau diese fachliche Evidenzentscheidung bestätigen',()=>{void effect(false);}),cancel=button('Fachvorschau abbrechen',()=>{if(!busy){p=null;diff.textContent='';state('CURRENT_HUMAN_READ');}}),reconcile=button('Unklaren Ausgang nativ lesen',()=>{void effect(true);}),reload=button('Humanstand neu lesen',()=>{if(c&&!busy)void load(c);});
 function state(s:string){root.dataset.state=s;status.textContent=s;selectedAction.textContent='Gewählte Fachaktion: '+select.selectedOptions[0]!.textContent;for(const [i,option]of [...select.options].entries())option.disabled=!v||(i===2?v.nativeRole!=='APPROVER'||v.state!==next[0]:v.nativeRole!=='REVIEWER'||!(i===0?['REVIEW_REQUIRED','STALE_NATIVE_BASIS_REVIEW_REQUIRED',next[1]]:['REVIEW_REQUIRED','STALE_NATIVE_BASIS_REVIEW_REQUIRED',next[0]]).includes(v.state));preview.disabled=busy||attempted||!csrf||select.selectedOptions[0]!.disabled;confirm.disabled=busy||!p||attempted||!csrf;cancel.disabled=busy;reload.disabled=busy;reconcile.hidden=!attempted||!p;reconcile.disabled=busy;}
 select.addEventListener('change',()=>state(root.dataset.state!),{signal:o.signal});
 async function request(t:WorkspaceContextReadbackV1,op:WorkspaceModuleViewRequestV1,payload?:Readonly<Record<string,unknown>>){if(!live(t))throw Error();const r=await o.context.moduleViewRequest(op,payload,op==='HUMAN_DECIDE'?csrf:undefined);if(!live(t)||r.outcome!=='CURRENT_MODULE_VIEW_RESPONSE')throw Error();const x=r.value as Record<string,unknown>;if(!x||Object.keys(x).length!==4||x.schemaVersion!=='pansphaira.workspace-erv-human/'+op.slice(6).toLowerCase()+'/v1'||x.contextHandle!==t.contextHandle)throw Error();return x;}
 function projection(t:WorkspaceContextReadbackV1,x:unknown){return validateWorkspaceErvHumanReadV1(x,t.primaryObject!.objectId,t.primaryObject!.revision);}
 async function read(t:WorkspaceContextReadbackV1){const r=await request(t,'HUMAN_READ');v=projection(t,r.value);csrf=typeof r.csrfProof==='string'&&/^[a-f0-9]{64}$/.test(r.csrfProof)?r.csrfProof:undefined;detail.replaceChildren();facts(detail,[['Rechnung / Fachrevision',v.invoiceId+' / '+v.nativeRevision],['Bestellung / Position',v.references.orderId+' / '+v.references.positionId],['Wareneingangsbezug',v.references.receiptIds.join(', ')||'UNKNOWN — keine nativen Eingangsreferenzen'],['Native Mengeneinheit / Quelle',v.references.quantityUnit+' / '+v.leadingStore],['Rechnungsquelle / SHA256',v.references.invoiceSourcePath+' / '+v.references.invoiceSourceSha256],['Native Rolle / Zustand',v.nativeRole+' / '+v.state],['Humanrevision / Proposaldigest',v.proposalRevision+' / '+v.proposalDigest]]);return v;}
 async function load(t:WorkspaceContextReadbackV1){busy=true;state('READING_HUMAN');try{await read(t);p=null;attempted=false;diff.textContent='';if(v?.nativeRole==='APPROVER')select.selectedIndex=2;state('CURRENT_HUMAN_READ');}catch{if(live(t)){v=null;csrf=undefined;detail.replaceChildren();state('HUMAN_UNAVAILABLE');}}finally{if(live(t)){busy=false;state(root.dataset.state!);}}}
 async function effect(reconciling:boolean){const t=c,command=p;if(!t||!command||busy||!live(t)||reconciling!==attempted||!reconciling&&!csrf)return;attempted=true;busy=true;state('CONFIRMING_HUMAN');try{const r=await request(t,reconciling?'HUMAN_RECONCILE':'HUMAN_DECIDE',reconciling?{effectId:command.effectId}:{command}),x=r.value as Record<string,unknown>;if(reconciling&&(x.outcome!=='RECONCILED_LOCAL_DECISION_NO_NEW_EFFECT'||x.newDecisionEffect!==false||x.executionAuthorityGranted!==false))throw Error();const receipt=projection(t,reconciling?x.readback:x),after=await read(t);if(receipt.proposalRevision!==command.expectedProposalRevision+1||receipt.state!==expected||!receipt.lastEventDigest||receipt.proposalDigest!==after.proposalDigest||receipt.lastEventDigest!==after.lastEventDigest||reconciling&&x.eventDigest!==after.lastEventDigest)throw Error();const refreshed=await o.refreshNativeSources();if(!live(t))return;p=null;diff.textContent=refreshed?'':'Native Fachentscheidung exakt zurückgelesen; persönlicher View-/Quellenstand nicht aktuell bestätigt.';state('HUMAN_DECISION_NATIVE_READBACK_CONFIRMED');}catch{if(live(t))state('HUMAN_WRITE_OUTCOME_UNKNOWN');}finally{if(live(t)){busy=false;state(root.dataset.state!);}}}
 const unsubscribe=o.context.subscribe(t=>{c=t;v=null;p=null;csrf=undefined;attempted=false;busy=false;diff.textContent='';detail.replaceChildren();root.hidden=!t||t.moduleId!=='pan.erv'||!t.primaryObject;if(!root.hidden){if(!root.isConnected)o.main.append(root);void load(t!);}});function close(){unsubscribe();c=null;v=null;p=null;csrf=undefined;root.remove();}o.signal.addEventListener('abort',close,{once:true});return Object.freeze({close});
}
