import {text} from "./api-v1.js";
import {reduceWorkspaceModuleViewV1,type WorkspaceModuleViewV1,type WorkspaceViewDeltaV1,type WorkspaceViewOperationV1} from "../../contracts/src/workspace-module-view-v1.js";
import type {WorkspaceContextReadbackV1} from "../../contracts/src/workspace-context-selection-v1.js";
import type {createWorkspaceContextSelectionV1,WorkspaceModuleViewRequestV1} from "./context-selection-v1.js";
import {nativeViewCatalogV1,nativeViewCellsV1,nativeViewReadV1,nativeViewPreviewV1,nativeViewWriteReceiptV1,type NativeViewCatalogV1,type NativeViewCellV1,type NativeViewReadV1,type NativeViewPreviewV1} from "./module-view-native-v1.js";
const labels:Readonly<Record<string,string>>={"erv.invoice.amountMinor":"Rechnungsbetrag","erv.invoice.currency":"Währung","erv.invoice.liabilityStatus":"Fachstatus","erv.invoice.expectedAmountMinor":"Erwarteter Betrag","erv.invoice.varianceMinor":"Abweichung","erv.invoice.orderedQuantity":"Bestellte Menge","erv.invoice.acceptedQuantity":"Angenommene Menge","erv.invoice.invoicedQuantity":"Berechnete Menge","erv.human.reviewState":"Nativer Prüfstand"};
const titles:Readonly<Record<string,string>>={VALUE:"Rechnungswert",TABLE:"Native Rechnungsfelder",HUMAN_REVIEW:"Nativer Prüfstand — keine Buchungsfreigabe"};
export function createWorkspaceModuleViewEditorV1(options:{readonly main:HTMLElement;readonly context:ReturnType<typeof createWorkspaceContextSelectionV1>;readonly signal:AbortSignal}){
 const root=document.createElement("section");root.id="shell.module-view";root.className="module-view-editor";root.setAttribute("aria-label","Persönliche native ERV-View");root.hidden=true;
 const heading=text("h2","Persönliche ERV-View"),boundary=text("p","Nur persönliche Anordnung und Bindung zugelassener nativer Felder. Kein Autosave; kein Buchungs-, Zahlungs- oder Ausführungsrecht."),status=text("p","Nativer Viewstand wird gelesen."),toolbar=document.createElement("div"),content=document.createElement("div"),cards=document.createElement("div"),properties=document.createElement("fieldset"),comparison=document.createElement("section"),beforeAfter=document.createElement("div");
 toolbar.className="module-view-toolbar";content.className="module-view-content";cards.className="module-view-cards";properties.className="module-view-properties";properties.hidden=true;properties.append(text("legend","Eigenschaften — ausgewähltes Viewelement"));comparison.className="module-view-comparison";comparison.hidden=true;beforeAfter.className="module-view-before-after";status.setAttribute("role","status");status.setAttribute("aria-live","polite");boundary.className="module-view-boundary";root.append(heading,boundary,status,toolbar,content,comparison);content.append(cards,properties);comparison.append(text("h3","Vorher / Nachher — noch nicht gespeichert"),beforeAfter);
 let context:WorkspaceContextReadbackV1|null=null,metadata:NativeViewCatalogV1|null=null,before:NativeViewReadV1|null=null,draft:WorkspaceModuleViewV1|null=null,pending:NativeViewPreviewV1|null=null,cells=new Map<string,NativeViewCellV1>(),operations:WorkspaceViewOperationV1[]=[],selected="invoice-value",editing=false,busy=false,serial=0,ownReadback=false,closed=false;
 const cardNodes=new Map<string,{root:HTMLElement;title:HTMLButtonElement;values:HTMLElement}>();
 // A dispatched UI candidate is never offered again, even if its reply was
 // lost or independent readback failed. Only a fresh native preview can save.
 const attemptedCandidates=new WeakSet<NativeViewPreviewV1>();
 function button(parent:HTMLElement,label:string,action:()=>void){const b=text("button",label) as HTMLButtonElement;b.type="button";b.addEventListener("click",action,{signal:options.signal});parent.append(b);return b;}
 const edit=button(toolbar,"View bearbeiten",()=>{if(!before||busy)return;editing=true;properties.hidden=false;state("DRAFT","Lokaler Entwurf — Änderungen werden erst nach Vorschau und ausdrücklicher Bestätigung gespeichert.");update();});
 const discard=button(toolbar,"Entwurf verwerfen",()=>{void cancel();});
 const preview=button(toolbar,"Vorher/Nachher prüfen",()=>{void previewDelta({schemaVersion:"pansphaira.workspace-module-view/delta/v1",operations:[...operations]},"MANUAL");});
 const undo=button(toolbar,"Letzten gespeicherten Viewstand zurückholen",()=>{void previewUndo();});
 const reload=button(toolbar,"Neu lesen — Entwurf behalten",()=>{void reloadCurrent();});
 const reconcile=button(toolbar,"Unklaren Schreibausgang unabhängig zurücklesen",()=>{void readback(pending);});reconcile.hidden=true;
 const selection=document.createElement("select");selection.id="pan546-selected-instance";const selectionLabel=text("label","Ausgewähltes Viewelement");selectionLabel.setAttribute("for",selection.id);properties.append(selectionLabel,selection);selection.addEventListener("change",()=>{void options.context.selectModuleViewInstance(selection.value);},{signal:options.signal});
 button(properties,"Element nach oben",()=>move(-1));button(properties,"Element nach unten",()=>move(1));
 const size=document.createElement("select");size.id="pan546-instance-size";for(const [value,label]of[["compact","Kompakt"],["regular","Normal"],["large","Groß"]]){const o=text("option",label!) as HTMLOptionElement;o.value=value!;size.append(o);}const sizeLabel=text("label","Elementgröße");sizeLabel.setAttribute("for",size.id);properties.append(sizeLabel,size);size.addEventListener("change",()=>apply({kind:"RESIZE",instanceId:selected,size:size.value as "compact"|"regular"|"large"}),{signal:options.signal});
 const visibility=document.createElement("input");visibility.type="checkbox";visibility.id="pan546-instance-visible";const visibilityLabel=text("label","In persönlicher View anzeigen");visibilityLabel.setAttribute("for",visibility.id);properties.append(visibility,visibilityLabel);visibility.addEventListener("change",()=>apply({kind:"SHOW",instanceId:selected,visible:visibility.checked}),{signal:options.signal});
 const binding=document.createElement("select");binding.id="pan546-field-binding";binding.multiple=true;binding.size=5;const bindingLabel=text("label","Erlaubte native Feldbindung — Mehrfachauswahl für Tabelle");bindingLabel.setAttribute("for",binding.id);properties.append(bindingLabel,binding);const bindApply=button(properties,"Ausgewählte Feldbindung anwenden",()=>apply({kind:"BIND",instanceId:selected,binding:{fieldIds:[...binding.selectedOptions].map(o=>o.value),unit:draft?.instances.find(i=>i.instanceId===selected)?.componentId==="TABLE"?"PER_FIELD":metadata?.fields.find(f=>f.fieldId===binding.value)?.unit??"COUNT"}}));
 const confirm=button(comparison,"Genau diese persönliche View bestätigen und speichern",()=>{void persist();});button(comparison,"Vorschau abbrechen — nichts speichern",()=>{void cancel();});
 function live(c:WorkspaceContextReadbackV1,n=serial){return !closed&&!options.signal.aborted&&serial===n&&context===c&&options.context.current()===c&&c.lease.expiresAtMs>Date.now();}
 function state(value:string,message:string){root.dataset.state=value;status.textContent=message;update();}
 function update(){edit.disabled=busy||!before||editing;preview.disabled=busy||!editing||operations.length===0;discard.disabled=busy||!before;undo.disabled=busy||!before||before.revision===0;reload.disabled=busy||!context;properties.disabled=busy;confirm.disabled=busy||!pending||attemptedCandidates.has(pending)||pending.expiresAtMs<=Date.now();root.dataset.revision=before?String(before.revision):"unknown";root.dataset.editing=String(editing);}
 async function request(c:WorkspaceContextReadbackV1,op:WorkspaceModuleViewRequestV1,payload?:Readonly<Record<string,unknown>>){const n=serial;if(!live(c,n))throw Error("MODULE_VIEW_CONTEXT_RETIRED");const r=await options.context.moduleViewRequest(op,payload);if(!live(c,n))throw Error("MODULE_VIEW_CONTEXT_RETIRED");if(r.outcome!=="CURRENT_MODULE_VIEW_RESPONSE")throw Error(r.outcome);return r.value;}
 function fieldValue(id:string){const v=cells.get(id);if(!v)return "UNAVAILABLE — nicht aktuell nativ gelesen";if(v.state==="UNKNOWN")return "UNKNOWN — nativer Fehlwert";const currency=cells.get("erv.invoice.currency")?.value;const value=v.unit==="CURRENCY_MINOR"&&typeof v.value==="number"&&typeof currency==="string"?new Intl.NumberFormat("de-DE",{style:"currency",currency}).format(v.value/100):String(v.value)+(v.unit==="CURRENCY_MINOR"?" minor units · Währung UNKNOWN":"");return value+" · "+v.unit+" · "+v.source+" · Stand "+v.sourceRevision;}
 function render(view:WorkspaceModuleViewV1){
  for(const i of view.instances){let node=cardNodes.get(i.instanceId);if(!node){const r=document.createElement("article"),t=button(r,titles[i.componentId]??i.instanceId,()=>{void options.context.selectModuleViewInstance(i.instanceId);}),values=document.createElement("div");r.className="module-view-card";r.dataset.instance=i.instanceId;r.append(values);node={root:r,title:t,values};cardNodes.set(i.instanceId,node);}node.root.hidden=!i.visible;node.root.dataset.size=i.size;node.root.dataset.selected=String(i.instanceId===selected);node.title.setAttribute("aria-pressed",String(i.instanceId===selected));node.values.replaceChildren(...i.binding.fieldIds.map(id=>{const row=text("p",(labels[id]??id)+": "+fieldValue(id));row.dataset.field=id;return row;}));}
  for(let p=0;p<view.instances.length;p++){const node=cardNodes.get(view.instances[p]!.instanceId)!.root;if(cards.children[p]!==node)cards.insertBefore(node,cards.children[p]??null);}
  if(!sameOptions(selection,[...view.instances].map(i=>i.instanceId))){selection.replaceChildren(...view.instances.map(i=>{const o=text("option",(titles[i.componentId]??i.instanceId)+" — "+i.instanceId+(i.visible?"":" (ausgeblendet)")) as HTMLOptionElement;o.value=i.instanceId;return o;}));}selection.value=selected;
  const i=view.instances.find(i=>i.instanceId===selected)??view.instances[0]!;size.value=i.size;visibility.checked=i.visible;visibility.disabled=["invoice-value","native-review"].includes(i.instanceId);const allowed=metadata?.fields.filter(f=>i.componentId==="TABLE"?f.source==="ERV_NATIVE":i.componentId==="HUMAN_REVIEW"?f.source==="HUMAN_NATIVE":f.source==="ERV_NATIVE"&&f.type==="NUMBER")??[];
  if(!sameOptions(binding,allowed.map(f=>f.fieldId)))binding.replaceChildren(...allowed.map(f=>{const o=text("option",(labels[f.fieldId]??f.fieldId)+" · "+f.unit) as HTMLOptionElement;o.value=f.fieldId;return o;}));for(const o of binding.options)o.selected=i.binding.fieldIds.includes(o.value);binding.disabled=["invoice-value","native-review"].includes(i.instanceId);bindApply.disabled=binding.disabled;
 }
 function sameOptions(select:HTMLSelectElement,values:readonly string[]){return JSON.stringify([...select.options].map(o=>o.value))===JSON.stringify(values);}
 function move(step:number){const p=draft?.instances.findIndex(i=>i.instanceId===selected)??-1;if(!draft||p<0||p+step<0||p+step>=draft.instances.length)return;apply({kind:"MOVE",instanceId:selected,position:p+step});}
 function apply(operation:WorkspaceViewOperationV1){if(!editing||busy||!before||!metadata||!context||!live(context))return;try{const next=[...operations,operation];draft=reduceWorkspaceModuleViewV1(before.view,{schemaVersion:"pansphaira.workspace-module-view/delta/v1",operations:next},metadata.fields);operations=next;pending=null;comparison.hidden=true;render(draft);state("DRAFT","Lokaler Entwurf geändert — keine Persistenz; aktualisierte Vorschau erforderlich.");}catch{state("DRAFT_DENIED","Änderung verweigert: Pflichtanzeige, Feld-/Einheitvertrag oder Viewgrenze. Keine Persistenz.");}}
 async function load(c:WorkspaceContextReadbackV1,keepDraft=false){
  const n=serial;busy=true;state("READING_NATIVE_VIEW","Persönlichen Viewstand und echte native Quellen unabhängig lesen.");
  try{
   const m=nativeViewCatalogV1(await request(c,"CATALOG"),c),r=await nativeViewReadV1(await request(c,"READ"),c,m);if(!live(c,n))return;
   const ids=[...new Set(["erv.invoice.currency",...r.view.instances.filter(i=>i.visible).flatMap(i=>i.binding.fieldIds)])],all=new Map<string,NativeViewCellV1>();
   for(let p=0;p<ids.length;p+=8){const batch=ids.slice(p,p+8),read=await request(c,"DATA",{schemaVersion:"pansphaira.workspace-data-read/v1",fieldIds:batch});for(const cell of nativeViewCellsV1(read,c,m,batch))all.set(cell.fieldId,cell);}if(!live(c,n))return;
   metadata=m;before=r;cells=all;delete root.dataset.error;boundary.textContent="Persönliche View, keine Fachwirkung. Nativer Katalog: zwei zulässige Rechnungen; höchstens acht Felder je Read, eine Zeile, Relationstiefe 0, keine freien Queries. Lieferant, Zuständigkeit und Belegnummer: UNAVAILABLE — keine autorisierte native Relation. Kein Autosave, Buchungs- oder Zahlungsrecht.";if(!keepDraft){operations=[];editing=false;}draft=operations.length?reduceWorkspaceModuleViewV1(r.view,{schemaVersion:"pansphaira.workspace-module-view/delta/v1",operations},m.fields):r.view;pending=ownReadback?pending:null;selected=c.selection?.elementId==="pan.erv.module-card"&&draft.instances.some(i=>i.instanceId===c.selection?.rowId)?c.selection.rowId!:selected;if(!draft.instances.some(i=>i.instanceId===selected))selected=draft.instances[0]!.instanceId;
   if(!root.isConnected)options.main.append(root);root.hidden=false;properties.hidden=!editing;comparison.hidden=!pending;render(draft);state("CURRENT_NATIVE_VIEW",operations.length?"Aktueller nativer Stand gelesen; lokaler Entwurf erhalten — neue Vorschau nötig.":"Aktueller persönlicher Viewstand unabhängig nativ gelesen. Keine Buchungs- oder Zahlungsfreigabe.");
  }catch(error){if(live(c,n)){root.dataset.error=error instanceof Error?error.message:"NATIVE_VIEW_DENIED";before=null;metadata=null;draft=null;cells.clear();cards.replaceChildren();cardNodes.clear();root.hidden=false;if(!root.isConnected)options.main.append(root);state("NATIVE_VIEW_UNAVAILABLE","Aktueller nativer View-/Quellenstand nicht bestätigt. Keine alten oder erfundenen Werte, kein Speichern.");}}
  finally{if(live(c,n)){busy=false;update();}}
 }
 async function showPreview(c:WorkspaceContextReadbackV1,value:unknown,m:NativeViewCatalogV1){if(!before||!live(c))return;const p=await nativeViewPreviewV1(value,c,m,before);if(!live(c))return;pending=p;metadata=m;beforeAfter.replaceChildren(...[["Vorher — nativ gelesen",p.beforeView],["Nachher — genau zu bestätigen",p.afterView]].map(([label,v])=>{const side=document.createElement("section");side.append(text("h4",label as string),text("p","Revision "+p.expectedRevision+" · "+((label as string).startsWith("Vorher")?p.beforeDigest:p.afterDigest)));const list=document.createElement("ol");for(const i of (v as WorkspaceModuleViewV1).instances)list.append(text("li",i.instanceId+" · "+i.size+" · "+(i.visible?"sichtbar":"ausgeblendet")+" · "+i.binding.fieldIds.join(", ")+" · "+i.binding.unit));side.append(list);return side;}));comparison.hidden=false;state("PREVIEW_ONLY","Vorher/Nachher nativ bestätigt — noch nicht gespeichert; nur persönliche View, keine Fachwirkung.");}
 async function previewDelta(delta:WorkspaceViewDeltaV1,source:"MANUAL"|"AGENT"){
  if(!context||!metadata||!before||busy)return;const c=context;busy=true;update();
  try{const expected=reduceWorkspaceModuleViewV1(before.view,delta,metadata.fields),m=nativeViewCatalogV1(await request(c,"CATALOG"),c),value=await request(c,"PREVIEW",{schemaVersion:"pansphaira.workspace-module-view/preview/v1",delta});await showPreview(c,value,m);if(!live(c))return;if(!pending||JSON.stringify(pending.afterView)!==JSON.stringify(expected))throw Error("NATIVE_SHARED_REDUCER_MISMATCH");draft=expected;operations=[...delta.operations];editing=true;properties.hidden=false;root.dataset.proposalSource=source;render(draft);}
  catch{if(live(c)){pending=null;comparison.hidden=true;state("PREVIEW_DENIED","Vorschau nicht aktuell bestätigt. Entwurf bleibt lokal; keine Persistenz und kein automatischer Retry.");}}
  finally{if(live(c)){busy=false;update();}}
 }
 async function previewUndo(){if(!context||!before||!metadata||busy||!before.revision)return;const c=context;busy=true;update();try{const m=nativeViewCatalogV1(await request(c,"CATALOG"),c),value=await request(c,"UNDO_PREVIEW",{schemaVersion:"pansphaira.workspace-module-view/undo-preview/v1",targetRevision:before.revision-1});await showPreview(c,value,m);}catch{if(live(c))state("UNDO_PREVIEW_DENIED","Gespeicherter Vorgänger nicht aktuell bestätigt. Kein blindes Zurücksetzen oder Schreiben.");}finally{if(live(c)){busy=false;update();}}}
 async function readback(candidate:NativeViewPreviewV1|null){if(!candidate||busy)return;busy=true;ownReadback=true;update();try{if(!await options.context.refreshModuleViewContext())throw Error("CURRENT_CONTEXT_REFRESH_DENIED");const c=options.context.current();if(!c||c.moduleId!==candidate.context.moduleId||c.viewId!==candidate.context.viewId||c.primaryObject?.objectId!==candidate.context.primaryObject?.objectId||c.binding.epoch!==candidate.context.binding.epoch)throw Error("SOURCE_SCOPE_CHANGED");context=c;await load(c,false);if(!before||before.revision!==candidate.expectedRevision+1||before.viewDigest!==candidate.afterDigest||before.confirmedCandidateDigest!==candidate.candidateDigest)throw Error("NATIVE_TARGET_NOT_CONFIRMED");pending=null;comparison.hidden=true;operations=[];editing=false;properties.hidden=true;reconcile.hidden=true;state("SAVED_AND_NATIVE_READBACK_CONFIRMED","Persönliche View gespeichert und durch unabhängiges natives GET exakt bestätigt. Keine Buchung, Zahlung oder Fachwirkung.");}catch{pending=candidate;reconcile.hidden=false;state("WRITE_OUTCOME_UNCONFIRMED","Schreibausgang nicht unabhängig bestätigt. Kein Erfolgsstatus, kein automatischer Save-/Undo-Retry; aktuelles Ziel erneut nur lesen.");}finally{ownReadback=false;busy=false;update();}}
 async function persist(){const p=pending,c=context;if(!p||!c||busy||p.context!==c||attemptedCandidates.has(p))return;attemptedCandidates.add(p);busy=true;state("CONFIRMING","Ausdrücklich bestätigte persönliche View einmal mit native CAS speichern; danach unabhängigen Readback prüfen.");try{const value=await request(c,"CONFIRM",{schemaVersion:"pansphaira.workspace-module-view/confirm/v1",candidateHandle:p.candidateHandle,candidateDigest:p.candidateDigest,confirmation:"CONFIRM_PERSONAL_VIEW"});nativeViewWriteReceiptV1(value,p);busy=false;state("READBACK_REQUIRED","Schreibreceipt empfangen — noch kein bestätigter Erfolg; aktuelles natives Ziel separat lesen.");await readback(p);}catch(error){if(!closed){busy=false;reconcile.hidden=false;state(error instanceof Error&&error.message==="MODULE_VIEW_WRITE_OUTCOME_UNKNOWN"?"WRITE_OUTCOME_UNCONFIRMED":"SAVE_DENIED","Speichern nicht bestätigt. Entwurf bleibt erhalten; kein blindes Überschreiben oder Retry. Nur aktuelles natives Ziel zurücklesen.");}}finally{busy=false;update();}}
 async function cancel(){if(busy)return;const p=pending,c=context,n=serial;if(p&&c&&p.context===c){try{await request(c,"CANCEL",{schemaVersion:"pansphaira.workspace-module-view/cancel/v1",candidateHandle:p.candidateHandle,candidateDigest:p.candidateDigest});}catch{/* Local discard is not a successful persistence or server-cancel claim. */}}if(!before||serial!==n||context!==c||closed)return;operations=[];pending=null;editing=false;draft=before.view;comparison.hidden=true;properties.hidden=true;reconcile.hidden=true;render(draft);state("LOCAL_DRAFT_DISCARDED","Lokaler Entwurf verworfen — kein Layoutschreibzugriff durch Vorschau/Abbruch.");}
 async function reloadCurrent(){if(busy||!context)return;const c=context;busy=true;ownReadback=true;update();try{if(!await options.context.refreshModuleViewContext())throw Error("CURRENT_CONTEXT_REFRESH_DENIED");const fresh=options.context.current();if(!fresh||fresh.binding.epoch!==c.binding.epoch||fresh.primaryObject?.objectId!==c.primaryObject?.objectId)throw Error("SOURCE_SCOPE_CHANGED");context=fresh;await load(fresh,true);}catch{if(context?.binding.epoch===c.binding.epoch)state("NATIVE_VIEW_UNAVAILABLE","Aktueller nativer Stand nicht bestätigt; Entwurf nicht gespeichert.");}finally{ownReadback=false;busy=false;update();}}
 const unsubscribe=options.context.subscribe(c=>{const previous=context,keep=Boolean(c&&previous&&c.binding.epoch===previous.binding.epoch&&c.primaryObject?.objectId===previous.primaryObject?.objectId&&c.moduleId===previous.moduleId&&c.revisions.viewRevision===previous.revisions.viewRevision);serial++;context=c;if(ownReadback)return;pending=null;comparison.hidden=true;if(!c||c.moduleId!=="pan.erv"||!c.primaryObject){root.hidden=true;before=null;metadata=null;cells.clear();operations=[];draft=null;editing=false;busy=false;cards.replaceChildren();cardNodes.clear();return;}root.hidden=false;if(!root.isConnected)options.main.append(root);void load(c,keep);});
 const api=Object.freeze({previewDelta,async refreshNativeSources(){const c=context;if(busy||!c||!live(c))return false;await load(c,true);return live(c)&&before!==null&&metadata!==null;},frame(){return before&&metadata&&context&&context.moduleId==="pan.erv"&&context.contextHandle===metadata.contextHandle&&context.primaryObject?.objectId===metadata.objectId&&live(context)?Object.freeze({context,metadata,nativeView:before,localDraft:draft}):null;},close(){if(closed)return;closed=true;serial++;unsubscribe();context=null;metadata=null;before=null;draft=null;pending=null;cells.clear();cardNodes.clear();root.remove();}});options.signal.addEventListener("abort",api.close,{once:true});return api;
}
