// Closed browser projections only. Validation/digests never mint native scope,
// read permission, consent or write authority; the trusted context adapter does
// the actual authenticated requests and source/context revalidation.
import {validateWorkspaceModuleViewV1,type WorkspaceModuleViewV1,type WorkspaceViewFieldV1} from "../../contracts/src/workspace-module-view-v1.js";
import type {WorkspaceContextReadbackV1} from "../../contracts/src/workspace-context-selection-v1.js";
type R=Record<string,unknown>;
export interface NativeViewCatalogV1 {readonly fields:readonly WorkspaceViewFieldV1[];readonly sourceDigest:string;readonly sourceRevisions:{readonly erv:number;readonly human:number};readonly contextHandle:string;readonly objectId:string}
export interface NativeViewReadV1 {readonly revision:number;readonly view:WorkspaceModuleViewV1;readonly viewDigest:string;readonly confirmedCandidateDigest:string|null}
export interface NativeViewPreviewV1 {readonly candidateHandle:string;readonly candidateDigest:string;readonly expiresAtMs:number;readonly kind:"DELTA"|"UNDO";readonly expectedRevision:number;readonly beforeView:WorkspaceModuleViewV1;readonly afterView:WorkspaceModuleViewV1;readonly beforeDigest:string;readonly afterDigest:string;readonly context:WorkspaceContextReadbackV1}
export interface NativeViewCellV1 {readonly fieldId:string;readonly unit:string;readonly state:"AVAILABLE"|"UNKNOWN";readonly value:string|number|null;readonly source:"ERV_NATIVE"|"HUMAN_NATIVE";readonly sourceRevision:number;readonly leadingStore:string}
function fail():never{throw Error("MODULE_VIEW_NATIVE_RESPONSE_DENIED");}
function record(value:unknown,keys:readonly string[]):R{if(!value||typeof value!=="object"||Object.getPrototypeOf(value)!==Object.prototype)return fail();const ds=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(ds).length!==keys.length||keys.some(k=>!Object.hasOwn(ds,k))||Object.values(ds).some(d=>!d.enumerable||!("value"in d)))return fail();return Object.fromEntries(keys.map(k=>[k,ds[k]!.value]));}
function list(value:unknown,max:number):readonly unknown[]{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length<1||value.length>max)return fail();const ds=Object.getOwnPropertyDescriptors(value),keys=[...Array(value.length).keys()].map(String);if(Reflect.ownKeys(ds).length!==keys.length+1||keys.some(k=>!Object.hasOwn(ds,k)||!ds[k]!.enumerable||!("value"in ds[k]!)))return fail();return keys.map(k=>ds[k]!.value as unknown);}
function number(v:unknown):number{if(!Number.isSafeInteger(v)||(v as number)<0)return fail();return v as number;}
function string(v:unknown,max=96):string{if(typeof v!=="string"||!v.length||v.length>max)return fail();return v;}
function digest(v:unknown):string{if(typeof v!=="string"||!/^[a-f0-9]{64}$/.test(v))return fail();return v;}
function same(a:unknown,b:unknown){return JSON.stringify(a)===JSON.stringify(b);}
export async function nativeViewDigestV1(v:unknown):Promise<string>{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(v)));return [...new Uint8Array(bytes)].map(n=>n.toString(16).padStart(2,"0")).join("");}
const catalogKeys=["schemaVersion","moduleId","viewId","contextHandle","objectId","fields","sourceRevisions","sourceDigest","budgets","components","executionAuthorityGranted","businessEffectProduced"];
function catalog(v:R,c:WorkspaceContextReadbackV1):NativeViewCatalogV1{
 if(v.moduleId!=="pan.erv"||v.viewId!=="pan.erv.view"||v.contextHandle!==c.contextHandle||v.objectId!==c.primaryObject?.objectId||v.executionAuthorityGranted!==false||v.businessEffectProduced!==false)return fail();
 const revisions=record(v.sourceRevisions,["erv","human"]),erv=number(revisions.erv),human=number(revisions.human);if(erv!==c.primaryObject?.revision)return fail();
 const budgets=record(v.budgets,["maximumNativeObjects","maximumFieldsPerRead","maximumRows","maximumRelationDepth","freeQueriesAllowed"]);if(budgets.maximumNativeObjects!==2||budgets.maximumFieldsPerRead!==8||budgets.maximumRows!==1||budgets.maximumRelationDepth!==0||budgets.freeQueriesAllowed!==false||!same(v.components,["VALUE","TABLE","HUMAN_REVIEW"]))return fail();
 const seen=new Set<string>(),fields=list(v.fields,32).map(x=>{const f=record(x,["fieldId","source","type","unit","cardinality","readOnly"]),fieldId=string(f.fieldId);if(!/^erv\.(?:invoice|human)\.[A-Za-z][A-Za-z0-9]{0,79}$/.test(fieldId)||seen.has(fieldId)||!["ERV_NATIVE","HUMAN_NATIVE"].includes(f.source as string)||!["NUMBER","STRING"].includes(f.type as string)||!["CURRENCY_MINOR","ISO4217","LIABILITY_STATE","REVIEW_STATE","COUNT","QUANTITY"].includes(f.unit as string)||f.cardinality!=="ONE"||f.readOnly!==true)return fail();seen.add(fieldId);return Object.freeze({fieldId,source:f.source as WorkspaceViewFieldV1["source"],type:f.type as WorkspaceViewFieldV1["type"],unit:f.unit as WorkspaceViewFieldV1["unit"]});});
 return Object.freeze({fields:Object.freeze(fields),sourceDigest:digest(v.sourceDigest),sourceRevisions:Object.freeze({erv,human}),contextHandle:c.contextHandle,objectId:c.primaryObject!.objectId});
}
export function nativeViewCatalogV1(value:unknown,c:WorkspaceContextReadbackV1):NativeViewCatalogV1{const v=record(value,catalogKeys);if(v.schemaVersion!=="pansphaira.workspace-data-catalog/v1")return fail();return catalog(v,c);}
export function nativeViewCellsV1(value:unknown,c:WorkspaceContextReadbackV1,metadata:NativeViewCatalogV1,requested:readonly string[]):readonly NativeViewCellV1[]{
 const v=record(value,[...catalogKeys,"cells","unavailableRelations","bookingAuthorityGranted","paymentOrderAuthorized"]);if(v.schemaVersion!=="pansphaira.workspace-data-readback/v1"||v.bookingAuthorityGranted!==false||v.paymentOrderAuthorized!==false)return fail();const m=catalog(v,c);if(!same(m,metadata))return fail();
 const unavailable=list(v.unavailableRelations,3);if(unavailable.length!==3||!same(unavailable.map(x=>{const r=record(x,["relationId","state","reason"]);if(r.state!=="UNAVAILABLE"||!string(r.reason,64).startsWith("NO_AUTHORIZED_NATIVE_"))return fail();return r.relationId;}),["supplier","assignee","document-number"]))return fail();
 const fields=new Map(m.fields.map(f=>[f.fieldId,f])),cells=list(v.cells,8).map(x=>{const r=record(x,["fieldId","unit","state","value","source","sourceRevision","leadingStore"]),fieldId=string(r.fieldId),f=fields.get(fieldId);if(!f||r.unit!==f.unit||r.source!==f.source||number(r.sourceRevision)!==(f.source==="ERV_NATIVE"?m.sourceRevisions.erv:m.sourceRevisions.human)||!["AVAILABLE","UNKNOWN"].includes(r.state as string)||r.state==="UNKNOWN"&&r.value!==null||r.state==="AVAILABLE"&&(f.type==="NUMBER"?(typeof r.value!=="number"||!Number.isFinite(r.value)):(typeof r.value!=="string"||r.value.length>128)))return fail();return Object.freeze({fieldId,unit:f.unit,state:r.state as NativeViewCellV1["state"],value:r.value as NativeViewCellV1["value"],source:f.source,sourceRevision:r.sourceRevision as number,leadingStore:string(r.leadingStore)});});if(!same(cells.map(x=>x.fieldId),requested))return fail();return Object.freeze(cells);
}
export async function nativeViewReadV1(value:unknown,c:WorkspaceContextReadbackV1,metadata:NativeViewCatalogV1):Promise<NativeViewReadV1>{
 const v=record(value,["schemaVersion","revision","view","viewDigest","confirmedCandidateDigest","persisted","businessEffectProduced","moduleId","viewId","binding","contextHandle","independentNativeRead"]),revision=number(v.revision),view=validateWorkspaceModuleViewV1(v.view,metadata.fields);
 if(v.schemaVersion!=="pansphaira.workspace-module-view/readback/v1"||v.moduleId!==c.moduleId||v.viewId!==c.viewId||!same(v.binding,c.binding)||v.contextHandle!==c.contextHandle||v.independentNativeRead!==true||v.businessEffectProduced!==false||v.persisted!==(revision>0)||await nativeViewDigestV1(view)!==digest(v.viewDigest)||revision===0&&v.confirmedCandidateDigest!==null)return fail();
 return Object.freeze({revision,view,viewDigest:v.viewDigest as string,confirmedCandidateDigest:revision===0?null:digest(v.confirmedCandidateDigest)});
}
export async function nativeViewPreviewV1(value:unknown,c:WorkspaceContextReadbackV1,metadata:NativeViewCatalogV1,before:NativeViewReadV1):Promise<NativeViewPreviewV1>{
 const v=record(value,["schemaVersion","candidateHandle","candidateDigest","expiresAtMs","kind","binding","expectedRevision","beforeView","afterView","beforeDigest","afterDigest","consequence","previewOnly","persistenceProduced","businessEffectProduced","executionAuthorityGranted"]),beforeView=validateWorkspaceModuleViewV1(v.beforeView,metadata.fields),afterView=validateWorkspaceModuleViewV1(v.afterView,metadata.fields),expectedRevision=number(v.expectedRevision),expiresAtMs=number(v.expiresAtMs);
 if(v.schemaVersion!=="pansphaira.workspace-module-view/preview-readback/v1"||!["DELTA","UNDO"].includes(v.kind as string)||!/^view-preview:[a-f0-9]{64}$/.test(string(v.candidateHandle))||!same(v.binding,c.binding)||expectedRevision!==before.revision||v.beforeDigest!==before.viewDigest||!same(beforeView,before.view)||expiresAtMs<=Date.now()||expiresAtMs>c.lease.expiresAtMs||v.consequence!=="PERSONAL_MODULE_VIEW_ONLY"||v.previewOnly!==true||v.persistenceProduced!==false||v.businessEffectProduced!==false||v.executionAuthorityGranted!==false||await nativeViewDigestV1(beforeView)!==digest(v.beforeDigest)||await nativeViewDigestV1(afterView)!==digest(v.afterDigest))return fail();
 const core={schemaVersion:"pansphaira.workspace-module-view/candidate/v1",kind:v.kind,binding:c.binding,contextHandle:c.contextHandle,sourceDigest:metadata.sourceDigest,expectedRevision,beforeDigest:v.beforeDigest,afterView,afterDigest:v.afterDigest};if(await nativeViewDigestV1(core)!==digest(v.candidateDigest))return fail();
 return Object.freeze({candidateHandle:v.candidateHandle as string,candidateDigest:v.candidateDigest as string,expiresAtMs,kind:v.kind as NativeViewPreviewV1["kind"],expectedRevision,beforeView,afterView,beforeDigest:v.beforeDigest as string,afterDigest:v.afterDigest as string,context:c});
}
export function nativeViewWriteReceiptV1(value:unknown,p:NativeViewPreviewV1):void{
 const v=record(value,["schemaVersion","outcome","kind","revision","viewDigest","confirmedCandidateDigest","binding","personalViewPersistenceProduced","businessEffectProduced","executionAuthorityGranted","independentReadbackRequired"]);
 if(v.schemaVersion!=="pansphaira.workspace-module-view/write-receipt/v1"||v.outcome!=="VIEW_PERSISTED"||v.kind!==p.kind||number(v.revision)!==p.expectedRevision+1||v.viewDigest!==p.afterDigest||v.confirmedCandidateDigest!==p.candidateDigest||!same(v.binding,p.context.binding)||v.personalViewPersistenceProduced!==true||v.businessEffectProduced!==false||v.executionAuthorityGranted!==false||v.independentReadbackRequired!==true)return fail();
}
