import {text} from './api-v1.js';
import type {createWorkspaceContextSelectionV1,WorkspaceModuleViewRequestV1} from './context-selection-v1.js';
import type {WorkspaceContextReadbackV1} from '../../contracts/src/workspace-context-selection-v1.js';
import {validateWorkspaceInvoiceQueryV1,validateWorkspaceNavigationResultV1,type WorkspaceNavigationOperationV1,type WorkspaceInvoiceSearchReadbackV1,type WorkspaceInvoiceCandidateV1,type WorkspaceNavigationRequestReadbackV1,type WorkspaceNavigationNativeReadbackV1,type WorkspaceNavigationRenderReadbackV1,type WorkspaceNavigationRenderedV1} from '../../contracts/src/workspace-invoice-navigation-v1.js';
import type {WorkspaceDirtyDraftV1,WorkspaceNavigationDriverV1} from './workspace-dirty-draft-v1.js';
import {buildBrowserDeepLinkV1} from '../../browser-shell/src/deep-link-v1.js';
import type {BrowserContextV1} from '../../browser-shell/src/context-owner-v1.js';
import type {createBrowserShellRegistryV1} from '../../browser-shell/src/registry-v1.js';
import type {createWorkspaceModuleViewEditorV1} from './module-view-editor-v1.js';
import type {createWorkspaceProfileEditorV1} from './profile-editor-v1.js';
export interface WorkspaceNativeNavigationFrameV1 {readonly context:WorkspaceContextReadbackV1|null;readonly invoice:import('../../contracts/src/browser-erv-read-v1.js').BrowserErvReadV1;readonly root:HTMLElement;readonly main:HTMLElement;isLive():boolean}
export function createWorkspaceInvoiceNavigationV1(options:{readonly container:HTMLElement;readonly context:ReturnType<typeof createWorkspaceContextSelectionV1>;readonly signal:AbortSignal;readonly drafts:ReadonlySet<WorkspaceDirtyDraftV1>;readonly editor:ReturnType<typeof createWorkspaceModuleViewEditorV1>;readonly profile:Awaited<ReturnType<typeof createWorkspaceProfileEditorV1>>|null;readonly shellContext:()=>BrowserContextV1;readonly registry:ReturnType<typeof createBrowserShellRegistryV1<HTMLElement>>;readonly activate:(read:WorkspaceNavigationNativeReadbackV1)=>Promise<WorkspaceNativeNavigationFrameV1|undefined>}):WorkspaceNavigationDriverV1{
 const root=document.createElement('section');root.id='shell.invoice-navigation';root.className='invoice-navigation';root.setAttribute('aria-label','Native Rechnungssuche und sichere Navigation');
 const form=document.createElement('form'),label=text('label','Native Vorgangs-ID suchen'),query=document.createElement('input'),search=text('button','Native Rechnungen suchen')as HTMLButtonElement,status=text('p','Kontext wird geprüft.'),candidates=document.createElement('ul');query.id='native-invoice-query';query.type='search';query.maxLength=64;query.autocomplete='off';query.spellcheck=false;label.setAttribute('for',query.id);search.type='submit';status.setAttribute('role','status');status.setAttribute('aria-live','polite');form.append(label,query,search);candidates.className='invoice-navigation-candidates';
 const guard=document.createElement('section'),guardText=text('p',''),keep=text('button','Entwurf behalten — Navigation abbrechen')as HTMLButtonElement,discard=text('button','Ungespeicherte Entwürfe verwerfen und navigieren')as HTMLButtonElement;guard.hidden=true;guard.className='invoice-navigation-dirtyguard';guard.setAttribute('aria-label','Ungespeicherte Entwürfe vor Navigation');guard.setAttribute('role','region');guardText.setAttribute('role','status');keep.type=discard.type='button';guard.append(text('h3','Ungespeicherte Änderungen erhalten'),guardText,keep,discard);
 root.append(text('h2','Native Rechnungssuche'),text('p','Nur zwei aktuell zugelassene synthetische Vorgangs-IDs aus der führenden Quelle. Kein allgemeiner Dokumentdienst, keine Lieferanten-/Zuständigkeitsmetadaten, keine freie URL und keine Fachwirkung. Erst Treffer wählen, dann nativen Read und echte View prüfen.'),form,status,candidates,guard);options.container.append(root);
 let closed=false,busy=false,inNavigation=false,serial=0,choiceLifetime=new AbortController(),guardTicket:{readonly action:()=>void}|null=null;
 const available=()=>!closed&&!options.signal.aborted&&root.isConnected;
 function state(code:string,message:string){if(!available())return;root.dataset.state=code;status.textContent=message;search.disabled=busy||!options.context.current();query.disabled=busy;}
 function clear(){choiceLifetime.abort();choiceLifetime=new AbortController();candidates.replaceChildren();}
 function dirty():readonly WorkspaceDirtyDraftV1[]{return [...options.drafts,{id:'PERSONAL_MODULE_VIEW' as const,label:'Persönlicher ERV-Viewentwurf',isDirty:()=>options.editor.isDirty(),discardForNavigation:()=>options.editor.discard()},{id:'PERSONAL_SHELL_PROFILE' as const,label:'Persönliches Darstellungsprofil',isDirty:()=>options.profile?.isDirty()??false,discardForNavigation:()=>options.profile?.discard()??Promise.resolve(false)}].filter(d=>d.isDirty());}
 function cancelGuard(){guardTicket=null;guard.hidden=true;discard.disabled=false;}
 function guarded(action:()=>void){if(!available())return;cancelGuard();const changed=dirty();if(!changed.length){action();return;}guardTicket={action};guard.hidden=false;guardText.textContent='Vor Navigation ausdrücklich behalten oder verwerfen: '+changed.map(d=>d.label).join('; ')+'. Kein Entwurf wird gespeichert. Ein unklarer oder laufender Schreibausgang muss zuerst separat zurückgelesen werden.';keep.focus();}
 keep.addEventListener('click',()=>{cancelGuard();query.focus();},{signal:options.signal});
 guard.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();cancelGuard();query.focus();}},{signal:options.signal});
 discard.addEventListener('click',()=>{void(async()=>{const ticket=guardTicket;if(!ticket||discard.disabled)return;discard.disabled=true;try{for(const d of dirty()){if(!available()||guardTicket!==ticket)return;if(!await d.discardForNavigation())throw Error('DIRTY_DRAFT_NOT_DISCARDED');}if(!available()||guardTicket!==ticket)return;if(dirty().length)throw Error('DIRTY_DRAFT_CHANGED');cancelGuard();ticket.action();}catch{if(available()&&guardTicket===ticket){discard.disabled=false;guardText.textContent='Entwurf nicht sicher verworfen. Navigation bleibt angehalten; keine Speicherung und kein Schreibretry. Laufenden oder unklaren Vorgang zuerst unabhängig lesen.';}}})();},{signal:options.signal});
 async function request(c:WorkspaceContextReadbackV1,operation:WorkspaceNavigationOperationV1,payload:Readonly<Record<string,unknown>>,n:number){if(!available()||n!==serial||options.context.current()!==c||Date.now()>=c.lease.expiresAtMs)throw Error('NAV_BROWSER_CONTEXT_RETIRED');const response=await options.context.moduleViewRequest(('NAV_'+operation)as WorkspaceModuleViewRequestV1,payload);if(!available()||n!==serial||options.context.current()!==c||response.outcome!=='CURRENT_MODULE_VIEW_RESPONSE')throw Error('NAV_BROWSER_RESPONSE_DENIED');return validateWorkspaceNavigationResultV1(operation,response.value);}
 async function find(c:WorkspaceContextReadbackV1,value:string,n:number){const result=await request(c,'SEARCH',{schemaVersion:'pansphaira.workspace-invoice-search/v1',query:value},n)as WorkspaceInvoiceSearchReadbackV1;if(result.contextHandle!==c.contextHandle||result.query!==value)throw Error('NAV_BROWSER_SEARCH_BINDING_DENIED');return result;}
 async function navigate(chosen:WorkspaceInvoiceCandidateV1,value:string){const c=options.context.current();if(!c||busy||!available())return;const n=++serial;busy=true;clear();state('SEARCHING_NATIVE','Gewählten Vorgang aus aktueller nativer Quelle erneut prüfen …');
  try{const fresh=await find(c,value,n),current=fresh.candidates.find(i=>i.objectId===chosen.objectId&&i.dataRevision===chosen.dataRevision);if(!current)throw Error('NAV_BROWSER_TARGET_STALE');
   const p=await request(c,'REQUEST',{schemaVersion:'pansphaira.workspace-navigation/request/v1',targetHandle:current.targetHandle},n)as WorkspaceNavigationRequestReadbackV1;
   if(p.target.objectId!==current.objectId||p.target.dataRevision!==current.dataRevision||p.lease.expiresAtMs!==c.lease.expiresAtMs||p.lease.issuedAtMs!==c.lease.issuedAtMs)throw Error('NAV_BROWSER_TARGET_BINDING_DENIED');
   state('NAVIGATION_REQUESTED','NAVIGATION_REQUESTED — Ziel serverseitig auf registrierte ERV-Route aufgelöst; noch kein Browserrender bestätigt.');
   const r=await request(c,'READ',{schemaVersion:'pansphaira.workspace-navigation/read/v1',requestHandle:p.requestHandle},n)as WorkspaceNavigationNativeReadbackV1;
   if(r.requestHandle!==p.requestHandle||r.invoice.tenantId!==c.binding.tenantId||r.invoice.invoiceId!==p.target.objectId||r.invoice.revision!==p.target.dataRevision)throw Error('NAV_BROWSER_READ_BINDING_DENIED');
   state('NATIVE_TARGET_READBACK_RECEIVED','Native Zielwerte und Datenrevision gelesen — noch kein Browserrenderreceipt.');
   if(n!==serial||options.context.current()!==c||dirty().length)throw Error('NAV_BROWSER_MANUAL_OR_DRAFT_PRECEDENCE');inNavigation=true;
   if(options.registry.status('pan.erv').outcome!=='REGISTERED'||!options.registry.routes().some(route=>route.routeId===p.target.routeId&&route.path===p.target.path&&route.state==='REGISTERED'))throw Error('NAV_BROWSER_PLUGIN_RETIRED');
   const shell=options.shellContext();history.replaceState(null,'',buildBrowserDeepLinkV1({path:p.target.path,tenantId:shell.tenantId,sessionId:shell.sessionId,objectId:p.target.objectId,revision:p.target.dataRevision}));
   const frame=await options.activate(r),c1=frame?.context;
   if(!available()||n!==serial||!frame||!c1||!frame.isLive()||!frame.root.isConnected||frame.main.hidden||frame.root.getBoundingClientRect().width<=0||frame.root.getBoundingClientRect().height<=0||c1.moduleId!=='pan.erv'||c1.viewId!=='pan.erv.view'||c1.primaryObject?.objectId!==r.invoice.invoiceId||c1.primaryObject.revision!==r.invoice.revision||JSON.stringify(frame.invoice)!==JSON.stringify(r.invoice)||frame.root.querySelector('h1')?.textContent!=='Eingangsrechnungsprüfung'||![...frame.root.querySelectorAll('dd')].some(node=>node.textContent===r.invoice.invoiceId))throw Error('NAV_BROWSER_RENDER_UNCONFIRMED');
   const rendered:WorkspaceNavigationRenderedV1=Object.freeze({moduleId:'pan.erv',viewId:'pan.erv.view',objectId:r.invoice.invoiceId,dataRevision:r.invoice.revision,tabId:c1.binding.tabId,epoch:c1.binding.epoch});
   const destination=options.context.current();if(!destination||destination.primaryObject?.objectId!==r.invoice.invoiceId||destination.primaryObject.revision!==r.invoice.revision||destination.binding.tabId!==c.binding.tabId||Date.now()>=c.lease.expiresAtMs)throw Error('NAV_BROWSER_RENDER_BINDING_DENIED');
   const ack=await request(destination,'ACK',{schemaVersion:'pansphaira.workspace-navigation/render-ack/v1',requestHandle:p.requestHandle,readReceiptHandle:r.readReceiptHandle,rendered},n)as WorkspaceNavigationRenderReadbackV1;
   if(ack.requestHandle!==p.requestHandle||Object.keys(rendered).some(k=>ack.rendered[k as keyof WorkspaceNavigationRenderedV1]!==rendered[k as keyof WorkspaceNavigationRenderedV1]))throw Error('NAV_BROWSER_ACK_BINDING_DENIED');
   root.dataset.object=rendered.objectId;root.dataset.dataRevision=String(rendered.dataRevision);root.dataset.tab=rendered.tabId;root.dataset.epoch=String(rendered.epoch);
   state('BROWSER_RENDERED_AND_ACK_REPORTED','Aktueller Vorgang '+rendered.objectId+' in nativer ERV-View wirklich gelesen und gerendert, Datenrevision '+rendered.dataRevision+', Tab und Epoch exakt gebunden. ACK ist nur client-reported, keine serverzertifizierte Render- oder Ausführungsfreigabe.');
  }catch{if(available()&&n===serial)state('NAVIGATION_NOT_CONFIRMED','Navigation/aktueller Browserrender nicht bestätigt: Route, Kontext, Revision, Session oder Entwurf nicht aktuell. Kein Erfolgsbeleg, keine freie URL, keine Wiederholung eines verbrauchten Targets/Receipts. Suche ausdrücklich erneut starten.');}
  finally{if(available()&&n===serial){busy=false;inNavigation=false;search.disabled=!options.context.current();query.disabled=false;}}
 }
 form.addEventListener('submit',event=>{event.preventDefault();if(busy||!available())return;cancelGuard();const c=options.context.current();if(!c)return;const n=++serial;busy=true;clear();state('SEARCHING_NATIVE','Zulässige native Vorgangs-IDs werden gelesen …');void(async()=>{try{const value=validateWorkspaceInvoiceQueryV1(query.value),result=await find(c,value,n);if(result.outcome==='NONE'){state('NO_NATIVE_MATCH','Kein erlaubter nativer Treffer. Keine Navigation und keine erfundenen Werte.');return;}state(result.outcome==='ONE'?'ONE_NATIVE_MATCH':'AMBIGUOUS_NATIVE_MATCH',result.outcome==='ONE'?'Ein aktueller erlaubter Treffer — ausdrücklich auswählen. Noch keine Navigation.':'Mehrdeutig: zwei erlaubte Vorgänge. Keinen ersten Treffer raten; genau einen ausdrücklich auswählen.');const signal=AbortSignal.any([options.signal,choiceLifetime.signal]);for(const candidate of result.candidates){const li=document.createElement('li'),button=text('button',candidate.label+' · Datenrevision '+candidate.dataRevision+' — Vorgang öffnen')as HTMLButtonElement;button.type='button';button.addEventListener('click',()=>{if(busy||options.context.current()!==c||n!==serial)return;guarded(()=>{void navigate(candidate,value);});},{signal});li.append(button);candidates.append(li);}}catch{if(available()&&n===serial)state('NATIVE_SEARCH_DENIED','Suche nicht aktuell bestätigt. Nur native Vorgangs-IDs mit A–Z, 0–9 und Bindestrich, höchstens 64 Zeichen; keine URL, SQL oder Metadatensuche. Kein fachlicher Erfolg.');}finally{if(available()&&n===serial){busy=false;search.disabled=!options.context.current();query.disabled=false;}}})();},{signal:options.signal});
 const unsubscribe=options.context.subscribe(c=>{if(closed||inNavigation)return;serial++;busy=false;clear();state(c?'SEARCH_READY':'CONTEXT_UNAVAILABLE',c?'Native Vorgangs-ID eingeben. Kein Autosave und keine Fachwirkung.':'Aktueller nativer Kontext nicht bestätigt. Fachnavigation und Abmelden bleiben unabhängig.');});
 const api=Object.freeze({guard:guarded,hashChange(acceptedHash:string,invalidate:()=>void,activate:()=>void){const next=location.hash;api.manualNavigation();invalidate();history.replaceState(null,'',acceptedHash);guarded(()=>{if(!available())return;history.replaceState(null,'',next);activate();});},manualNavigation(){if(!available())return;serial++;busy=false;inNavigation=false;clear();cancelGuard();state('MANUAL_NAVIGATION_PRECEDENCE','Manuelle Navigation hat Vorrang. Vorherige Suche/Navigation und spätere Antworten sind verworfen; kein alter Renderreceipt.');},close(){if(closed)return;closed=true;serial++;clear();cancelGuard();unsubscribe();root.remove();}});options.signal.addEventListener('abort',api.close,{once:true});return api;
}
