import {validateModelConnectionReadbackV1,MODEL_CONNECTION_PHASES_V1,type ModelConnectionReadbackV1,type ModelConnectionPhaseV1} from '../../contracts/src/workspace-model-connection-v1.js';
import {text} from './api-v1.js';
// Dedicated reference-only connection region; never a secret/password/URL input.
// This optional module does not enlarge or replace the existing shell bundle.
export async function createWorkspaceModelConnectionV1(){
 const scope=/^\/t\/([a-z0-9][a-z0-9-]{0,63})\/workspace$/.exec(location.pathname),canvas=document.getElementById('profile.canvas');if(!scope||!canvas)throw Error('MODEL_CONNECTION_BROWSER_DENIED');
 const base='/t/'+scope[1]+'/workspace',lifetime=new AbortController(),root=document.createElement('section');root.id='shell.model-connection';root.className='model-connection';root.setAttribute('aria-label','Sichere bestehende Modellverbindung');
 const open=text('button','Sichere Modellverbindung öffnen')as HTMLButtonElement,body=document.createElement('div'),status=text('p','Aktueller minimierter Backendzustand wird gelesen …');body.id='pan565-connection-body';body.hidden=true;open.type='button';open.setAttribute('aria-controls',body.id);open.setAttribute('aria-expanded','false');status.setAttribute('role','status');status.setAttribute('aria-live','polite');root.append(open,status,body);canvas.after(root);
 let alive=true,busy=false,serial=0,sessionId:string|null=null,readback:ModelConnectionReadbackV1|null=null,controls=new AbortController();
 let focusEpoch=0;document.addEventListener('focusin',()=>{focusEpoch++;},{signal:lifetime.signal});
 const live=()=>alive&&!lifetime.signal.aborted&&root.isConnected;
 const focused=()=>document.activeElement instanceof HTMLElement&&body.contains(document.activeElement)?document.activeElement.id:null;
 function restoreFocus(id:string|null,epoch:number){if(!id||!live()||body.hidden||epoch!==focusEpoch)return;let target=document.getElementById(id)as HTMLButtonElement|HTMLSelectElement|null;if(!target||target.disabled)target=body.querySelector<HTMLButtonElement>('button:not(:disabled)');target?.focus();}
 function state(code:string,message:string){if(live()){root.dataset.state=code;status.textContent=message;}}
 async function context(){const response=await fetch(base+'/context',{cache:'no-store',credentials:'same-origin',signal:lifetime.signal});if(response.status!==200)throw Error('MODEL_CONNECTION_SESSION_RETIRED');const c=await response.json()as{tenantId?:unknown;sessionId?:unknown};if(c.tenantId!==scope![1]||typeof c.sessionId!=='string'||!/^session:[a-f0-9]{64}$/.test(c.sessionId)||sessionId!==null&&c.sessionId!==sessionId)throw Error('MODEL_CONNECTION_SESSION_RETIRED');return c.sessionId;}
 async function request(operation:'read'|'select'|'probe'|'consent',payload?:unknown){if(!live()||!sessionId)throw Error('MODEL_CONNECTION_BROWSER_DENIED');await context();const r=await fetch(base+'/model-connection'+(operation==='read'?'':'/'+operation),{method:operation==='read'?'GET':'POST',credentials:'same-origin',cache:'no-store',signal:lifetime.signal,headers:{'x-pan565-session':sessionId,...(operation==='read'?{}:{'content-type':'application/json'})},...(operation==='read'?{}:{body:JSON.stringify(payload)})});if(r.status!==200)throw Error('MODEL_CONNECTION_NOT_CONFIRMED');const value=validateModelConnectionReadbackV1(await r.json());await context();if(!live()||value.binding.sessionId!==sessionId||value.binding.tenantId!==scope![1])throw Error('MODEL_CONNECTION_SESSION_RETIRED');return value;}
 const labels:Record<ModelConnectionPhaseV1,string>={REACHABILITY:'Erreichbarkeit',AUTHENTICATION:'Authentifizierung',MODEL_AVAILABILITY:'Modellverfügbarkeit',INFERENCE:'Begrenzte Inferenz'};
 function render(value:ModelConnectionReadbackV1){
  if(!live())return;readback=value;controls.abort();controls=new AbortController();const signal=AbortSignal.any([lifetime.signal,controls.signal]);body.replaceChildren(text('h2','Bestehende sichere Verbindung'),text('p','Nur serverseitig zugelassene Referenzen. Keine Geheimnisse, freien Ziele, OAuth-/Deviceannahmen oder Workerzugänge. Erreichbarkeit und Modellliste sind kein Inferenznachweis.'));
  const label=text('label','Zugelassene Verbindung'),select=document.createElement('select');select.id='pan565-connection-choice';label.setAttribute('for',select.id);const empty=document.createElement('option');empty.value='';empty.textContent='Bitte ausdrücklich auswählen';select.append(empty);
  for(const c of value.connections){const option=document.createElement('option');option.value=c.connectionId;option.textContent=c.connectionId+' · '+c.model+' · '+c.evidenceClass;option.disabled=!c.selectable;select.append(option);}select.value=value.selectedConnectionId??'';select.disabled=busy||value.connections.length===0;
  const preview=text('p',''),confirmed=text('p',''),actions=new Map<HTMLButtonElement,boolean>();preview.id='pan565-choice-preview';preview.setAttribute('aria-live','polite');confirmed.id='pan565-confirmed-reference';select.setAttribute('aria-describedby',preview.id+' '+confirmed.id);
  const coherent=()=>select.value===(value.selectedConnectionId??'');
  function syncChoice(){const c=value.connections.find(c=>c.connectionId===select.value);preview.textContent=c?(coherent()?'Browserauswahl entspricht der unabhängig bestätigten Referenz; keine neue Freigabe':'Browserauswahl — noch nicht gesetzt, keine Freigabe')+' · Referenz '+c.connectionId+' · Modell '+c.model+' · Evidenz '+c.evidenceClass:'Browserauswahl: keine Referenz gewählt, nichts gesetzt und keine Freigabe.';save.disabled=busy||!c||!c.selectable;for(const[b,denied]of actions)b.disabled=denied||!coherent();}
  const save=text('button','Genau diese Referenz setzen')as HTMLButtonElement;save.id='pan565-select';save.type='button';select.addEventListener('change',syncChoice,{signal});
  save.addEventListener('click',()=>{if(busy||!select.value||save.disabled)return;void mutate('select',{schemaVersion:'pansphaira.workspace-model-connection/select/v1',expectedRevision:value.revision,connectionId:select.value});},{signal});body.append(label,select,preview,save);
  const selected=value.connections.find(c=>c.connectionId===value.selectedConnectionId);confirmed.textContent=selected?'Unabhängig bestätigte persistierte Referenz: '+selected.connectionId+' · Modell '+selected.model+' · Evidenz '+selected.evidenceClass:'Unabhängiger Readback: keine persistierte Referenz bestätigt.';body.append(confirmed);if(selected){const dl=document.createElement('dl');for(const[k,v]of [['Referenz',selected.connectionId],['Modell',selected.model],['Evidenzklasse',selected.evidenceClass],['Secretreferenz',selected.secretReference??'Kein Secret — nur ausdrücklich lokaler Server'],['Authentisierung',selected.authMethod],['Konfigurationsrevision',String(selected.identity.configurationRevision)],['Deployment',selected.identity.deploymentId],['Prüfidentität',value.identityDigest??'nicht gebunden'],['Verfügbarkeit Runtime / Provider / Auth / Modell / Funktionen',Object.entries(selected.availability).map(([k,v])=>k+': '+(v?'SUPPORTED':'UNAVAILABLE')).join(' · ')]]as const)dl.append(text('dt',k),text('dd',v));body.append(dl);}
  const synthetic=selected?.evidenceClass==='SYNTHETIC_ONLY';
  const phases=document.createElement('ul');for(const p of MODEL_CONNECTION_PHASES_V1){const check=value.checks[p];phases.append(text('li',labels[p]+': '+check.state+' · '+check.reason+' · '+(check.checkedAtMs===null?'nicht ausgeführt':new Date(check.checkedAtMs).toISOString())));const b=text('button',labels[p]+' separat prüfen')as HTMLButtonElement;b.id='pan565-probe-'+p;b.type='button';const before=p==='AUTHENTICATION'?'REACHABILITY':p==='MODEL_AVAILABILITY'?'AUTHENTICATION':null;b.disabled=busy||!selected||!selected.selectable||before!==null&&value.checks[before].state!=='PASS'||p==='INFERENCE'&&!value.readyForInference;actions.set(b,b.disabled);b.addEventListener('click',()=>{if(busy||b.disabled||!coherent())return;void mutate('probe',{schemaVersion:'pansphaira.workspace-model-connection/probe/v1',expectedRevision:value.revision,identityDigest:value.identityDigest,phase:p});},{signal});body.append(b);}body.append(phases,text('p',(synthetic?'Synthetische Testfreigabe — keine Produktfreigabe: ':'Produkt-Kostenfreigabe: ')+value.consent+'. Reale Modell-/Toolloopabnahme: NICHT QUALIFIZIERT.'));
  const offer=value.inferenceOffer;if(offer){const limits=offer.limits,terms=document.createElement('dl');body.append(text('p',offer.pricingClass==='CODE_OWNED_SYNTHETIC_ZERO_PRICE'?'SYNTHETIC_ONLY: codeeigener Nullpreis, keine reale Währung, keine Produktfreigabe.':'OWNER_BOUND_NOT_QUALIFIED: gedeckelte Produkt-Kostenfreigabe, Preisrevision '+offer.priceRevision+'; noch keine Modellabnahme.'));for(const[k,v]of [['Max. Kosten',String(limits.maxCostMicros)+' Mikroeinheiten '+(offer.currency==='NONE'?'(synthetisches Limit; Nullpreis)':offer.currency)],['Max. Laufzeit',String(limits.maxTimeMs)+' ms'],['Max. Turns',String(limits.maxTurns)],['Max. Tools',String(limits.maxTools)],['Max. Modellrequests',String(limits.maxRequests)],['Max. Tokens',String(limits.maxTokens)],['Max. Eingabebytes',String(limits.maxInputBytes)],['Max. Ausgabebytes',String(limits.maxOutputBytes)],['Testdatendigest',offer.testDataDigest],['Owner-Angebot gültig bis',new Date(offer.expiresAtMs).toISOString()]]as const)terms.append(text('dt',k),text('dd',v));body.append(terms,text('p','Genau ein bestätigter Prüfstart; Browserfreigabe maximal 30 Sekunden. Ausschließlich fest gebundene öffentliche synthetische Testdaten, kein Toolloopnachweis.'));const grant=text('button','Genau diese gedeckelte Inferenzprobe freigeben')as HTMLButtonElement;grant.id='pan565-consent';grant.type='button';grant.disabled=busy||value.consent==='BOUNDED_ONCE'||value.checks.INFERENCE.state!=='NOT_RUN'||MODEL_CONNECTION_PHASES_V1.slice(0,3).some(p=>value.checks[p].state!=='PASS');actions.set(grant,grant.disabled);grant.addEventListener('click',()=>{if(busy||grant.disabled||!coherent())return;void mutate('consent',{schemaVersion:'pansphaira.workspace-model-connection/consent/v1',expectedRevision:value.revision,identityDigest:value.identityDigest,limits:offer.limits,testDataDigest:offer.testDataDigest,confirm:true});},{signal});body.append(grant);}else body.append(text('p',value.reason==='BUDGET_EXHAUSTED'?'Natives Budget erschöpft: keine weitere Freigabe oder Inferenz. Referenzsetzen setzt Verbrauch nicht zurück.':'Keine konkrete ausführbare gedeckelte Freigabe vorhanden. Keine Inferenzfreigabe aus Workerabo, Modellliste oder HTTP200.'));
  const refresh=text('button','Verbindungsstatus unabhängig lesen')as HTMLButtonElement;refresh.id='pan565-read';refresh.type='button';refresh.disabled=busy;refresh.addEventListener('click',()=>{if(!busy)void refreshRead();},{signal});body.append(refresh,text('p','Neue Credentials werden hier nicht erfasst oder gespeichert. Einen bestehenden geeigneten Secretpfad muss der zuständige Owner bereitstellen. Browser, Chat und Export enthalten nur Referenz und minimierten Status.'));
  syncChoice();state(value.connections.length===0?'NO_AUTHORIZED_CONNECTION':'CURRENT_CONNECTION',value.connections.length===0?'Keine autorisierte Produkt-Modellroute vorhanden. Referenz fehlt; Inferenz NOT_RUN. Interne Vertragsarbeit ist davon getrennt.':'Nativer Referenz-/Prüfstatus gelesen, Revision '+value.revision+'. Kein automatischer Test oder Inferenzstart.');
 }
 async function refreshRead(){if(busy||!live())return;const focus=focused();busy=true;const n=++serial;if(readback)render(readback);const epoch=focusEpoch;state('READING','Minimierten Status unabhängig lesen …');try{const r=await request('read');if(n===serial&&live()){busy=false;render(r);restoreFocus(focus,epoch);}}catch{if(n===serial&&live()){busy=false;deny();}}}
 function deny(){controls.abort();body.replaceChildren(text('p','Session, Tenant, Revision oder Verbindungsstatus nicht aktuell bestätigt. Kein Retry einer Mutation, kein neuer Provider und keine Inferenz. Nur unabhängigen Status lesen oder mit gültiger Session neu öffnen.'));const retry=text('button','Verbindungsstatus unabhängig lesen')as HTMLButtonElement;retry.type='button';retry.addEventListener('click',()=>{if(!busy&&live())void refreshRead();},{signal:lifetime.signal});body.append(retry);readback=null;state('READBACK_NOT_CONFIRMED','Verbindung nicht aktuell bestätigt. Keine Speicherung oder Inferenz behauptet.');}
 async function mutate(operation:'select'|'probe'|'consent',payload:unknown){if(busy||!live()||!readback)return;const focus=focused();busy=true;const n=++serial;render(readback);const epoch=focusEpoch;state('REQUESTING','Genau angeforderte Referenz-/Prüfaktion läuft …');try{const acknowledged=await request(operation,payload),independent=await request('read');if(independent.revision!==acknowledged.revision||independent.selectedConnectionId!==acknowledged.selectedConnectionId||independent.identityDigest!==acknowledged.identityDigest)throw Error('MODEL_CONNECTION_READBACK_MISMATCH');if(n===serial&&live()){busy=false;render(independent);restoreFocus(focus,epoch);}}catch{if(n===serial&&live()){busy=false;deny();}}}
 open.addEventListener('click',()=>{body.hidden=!body.hidden;open.setAttribute('aria-expanded',String(!body.hidden));open.textContent=body.hidden?'Sichere Modellverbindung öffnen':'Verbindungsdialog schließen';if(!body.hidden)body.querySelector<HTMLElement>('select,button')?.focus();},{signal:lifetime.signal});
 body.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();body.hidden=true;open.setAttribute('aria-expanded','false');open.textContent='Sichere Modellverbindung öffnen';open.focus();}},{signal:lifetime.signal});
 function close(){if(!alive)return;alive=false;serial++;controls.abort();lifetime.abort();root.remove();}
 addEventListener('pagehide',close,{once:true});try{sessionId=await context();await refreshRead();}catch{if(live())deny();}return Object.freeze({close});
}
if(typeof document!=='undefined')void createWorkspaceModelConnectionV1().catch(()=>{const root=document.getElementById('profile.canvas');root?.after(text('p','Verbindungsdialog nicht verfügbar. Keine Inferenz; Fachnavigation und Abmelden bleiben unabhängig.'));});
