import {text} from './api-v1.js';
import type {createWorkspaceContextSelectionV1,WorkspaceModuleViewRequestV1} from './context-selection-v1.js';
import type {createWorkspaceModuleViewEditorV1} from './module-view-editor-v1.js';
import {nativeViewCatalogV1} from './module-view-native-v1.js';
import {validateWorkspaceAgentPlanV1,validateWorkspaceAgentReadV1,type WorkspaceAgentPlanV1,type WorkspaceAgentReadV1} from '../../contracts/src/workspace-agent-run-v1.js';
import type {WorkspaceContextReadbackV1} from '../../contracts/src/workspace-context-selection-v1.js';
export function createWorkspaceAgentPanelV1(options:{readonly container:HTMLElement;readonly context:ReturnType<typeof createWorkspaceContextSelectionV1>;readonly editor:ReturnType<typeof createWorkspaceModuleViewEditorV1>;readonly signal:AbortSignal}){
 const root=document.createElement('section');root.id='shell.agent-panel';root.className='workspace-agent';root.setAttribute('aria-label','Gemeinsames nichtmodales Auftragspanel');
 const controls=document.createElement('div'),body=document.createElement('div'),status=text('p','Aktuellen nativen Kontext wählen.'),scope=text('p','Keine aktuelle native Auswahl.'),facts=document.createElement('dl'),explanation=text('p','Noch kein Auftrag.');controls.className='workspace-agent-controls';body.id='pan548-agent-body';body.className='workspace-agent-body';status.setAttribute('role','status');status.setAttribute('aria-live','polite');scope.dataset.agentScope='true';explanation.dataset.agentExplanation='true';
 let c:WorkspaceContextReadbackV1|null=null,plan:WorkspaceAgentPlanV1|null=null,result:WorkspaceAgentReadV1|null=null,runId:string|null=null,busy=false,serial=0,closed=false,opened=true,focusMode=false;
 const attempted=new Set<string>(),nativeConfigured=document.body.dataset.ownerModelConnections==='true';let offerTimer:ReturnType<typeof setTimeout>|null=null;
 function button(parent:HTMLElement,label:string,action:()=>void){const b=text('button',label) as HTMLButtonElement;b.type='button';b.addEventListener('click',action,{signal:options.signal});parent.append(b);return b;}
 const chip=button(controls,'Auftragspanel ausblenden',()=>{opened=!opened;body.hidden=!opened;chip.textContent=opened?'Auftragspanel ausblenden':'Auftragspanel öffnen';chip.setAttribute('aria-expanded',String(opened));if(!opened)chip.focus();});chip.setAttribute('aria-controls',body.id);chip.setAttribute('aria-expanded','true');
 button(controls,'Darstellung Dock / Fokus wechseln',()=>{focusMode=!focusMode;root.dataset.presentation=focusMode?'FOCUS':'DOCK';});
 body.append(text('h2','Auftrag, Lauf und persönliche Vorschläge'),text('p',nativeConfigured?'Native vorhandene Modellverbindung: erst den genau gebundenen Datenumfang und das Angebot prüfen, dann separat einmalig bestätigen. Ownerbindung ist keine Echtmodellabnahme; nur persönlicher Viewvorschlag, keine Fachwirkung.':'Dieser begrenzte Backendtest ist synthetisch: kein Sprachmodell und keine Fachentscheidung. Nur das ausgewählte native Viewelement größer darstellen; getrennte Vorschau und ausdrückliche Bestätigung im persönlichen Vieweditor.'),scope,status);
 const form=document.createElement('div');form.className='workspace-agent-compose';const label=text('label',nativeConfigured?'Text des gebundenen Viewauftrags':'Begründung des synthetischen Testauftrags'),input=document.createElement('textarea');input.id='pan548-agent-intent';input.maxLength=1024;input.rows=3;input.value='Ausgewähltes Viewelement größer darstellen, zunächst nur Vorschlag.';label.setAttribute('for',input.id);form.append(label,input);
 const consentLabel=text('label',''),transferConsent=document.createElement('input');transferConsent.type='checkbox';transferConsent.id='pan548-agent-inference-consent';consentLabel.setAttribute('for',transferConsent.id);consentLabel.append(transferConsent,document.createTextNode('Genau diesen Text, die persönliche Viewanordnung und die zwei Toolrückgaben einmalig an die unten gebundene Route übertragen; genau diese Kosten-/Zeit-/Turn-/Toolgrenzen bestätigen. Kein Speichern und keine Fachwirkung.'));consentLabel.hidden=true;form.append(consentLabel);transferConsent.addEventListener('change',update,{signal:options.signal});input.addEventListener('input',()=>{plan=null;transferConsent.checked=false;consentLabel.hidden=true;update();},{signal:options.signal});
 const makePlan=button(form,nativeConfigured?'Gebundenen Auftrag und Angebot planen':'Begrenzten Testauftrag planen',()=>{void prepare();}),start=button(form,'Genau diesen synthetischen Lauf starten',()=>{void dispatch();}),read=button(form,'Laufstatus unabhängig nativ lesen',()=>{void reconcile();}),review=button(form,'Diesen Vorschlag separat im Vieweditor prüfen',()=>{void preview();});
 const cancel=button(form,'Lauf abbrechen — nicht verfügbar',()=>{}),resume=button(form,'Lauf fortsetzen — nicht verfügbar',()=>{}),real=button(form,'Echten Modellvorschlag senden — nicht verfügbar',()=>{});for(const b of [cancel,resume,real])b.disabled=true;
 body.append(form,text('p',nativeConfigured?'Cancel und Resume: kein vorhandener nativer Modelltaskvertrag. Nur eine vorhandene native Route mit aktuellem Ownergrant, Secretreferenz, Identität, Preis und passendem Datenzweck kann ein Angebot liefern. Keine Workerabo-/Credential-/Providerübernahme und keine automatische Ausführung.':'Cancel und Resume: kein vorhandener nativer Modelltaskvertrag. Echtmodellroute: sichere Secretreferenz, aktuelle Verbindungs-/Modell-/Parseridentität und gedeckelte Produktinferenzfreigabe aus #565/#575 fehlen. Keine Aktivierung aus Workerabo, keine Credential- oder Providerkonfiguration in diesem Panel.'),facts,explanation);root.append(controls,body);options.container.append(root);root.dataset.presentation='DOCK';root.dataset.modelMode=nativeConfigured?'OWNER_BOUND_PROVIDER':'SYNTHETIC_PROBE_ONLY';
 function state(phase:string,message:string){root.dataset.state=phase;status.textContent=message;update();}
 function live(context:WorkspaceContextReadbackV1,n=serial){return !closed&&!options.signal.aborted&&n===serial&&c===context&&options.context.current()===context&&context.lease.expiresAtMs>Date.now();}
 function usable(){return Boolean(c&&c.moduleId==='pan.erv'&&c.primaryObject&&c.selection?.elementId==='pan.erv.module-card'&&c.lease.expiresAtMs>Date.now());}
 function freshProposal(){const frame=options.editor.frame();return Boolean(result?.phase==='RESULT_READY'&&result.proposal&&frame&&result.sourceDigest===frame.metadata.sourceDigest&&result.proposal.beforeDigest===frame.nativeView.viewDigest&&result.proposal.expectedRevision===frame.nativeView.revision&&frame.context.selection?.rowId===result.proposal.delta.operations[0]?.instanceId&&frame.context.selection?.elementId==='pan.erv.module-card');}
 function update(){const offer=plan?.inferenceConsentOffer;makePlan.disabled=busy||!usable();start.disabled=busy||!plan||attempted.has(plan.planHandle)||plan.expiresAtMs<=Date.now()||Boolean(offer&&(offer.expiresAtMs<=Date.now()||!transferConsent.checked));start.textContent=offer?'Genau diesen gebundenen Lauf einmalig starten':'Genau diesen synthetischen Lauf starten';transferConsent.disabled=busy||!offer||offer.expiresAtMs<=Date.now();consentLabel.hidden=!offer;read.disabled=busy||!runId||!c||c.moduleId!=='pan.erv'||!c.primaryObject;review.disabled=busy||!freshProposal();input.disabled=busy;root.dataset.run=runId??'none';root.dataset.dispatchAvailable=String(!start.disabled);}
 function storageKey(context:WorkspaceContextReadbackV1){const b=context.binding;return 'pansphaira.workspace-agent.last-run/v1:'+b.tenantId+':'+b.subjectId+':'+b.instanceId+':'+b.generation;}
 function remember(context:WorkspaceContextReadbackV1,id:string){try{sessionStorage.setItem(storageKey(context),id);}catch{/* Storage is optional hint, never dispatch/auth authority. */}}
 async function request(context:WorkspaceContextReadbackV1,operation:WorkspaceModuleViewRequestV1,payload?:Readonly<Record<string,unknown>>){const n=serial;if(!live(context,n))throw Error('AGENT_CONTEXT_RETIRED');const reply=await options.context.moduleViewRequest(operation,payload);if(!live(context,n)||reply.outcome!=='CURRENT_MODULE_VIEW_RESPONSE')throw Error('AGENT_RESPONSE_UNCONFIRMED');return reply.value;}
 function details(value:WorkspaceAgentPlanV1|WorkspaceAgentReadV1){root.dataset.modelMode=value.modelMode;const rows:[string,string][]=[['Nativer Lauf',value.runId],['Modellstatus',value.modelMode==='OWNER_BOUND_PROVIDER'?'Native Ownerbindung — keine Echtmodellabnahme':'Synthetischer Test — kein KI-Abnahmenachweis'],['Wirkung','Keine Viewpersistenz und keine Fachwirkung']];if('planDigest'in value){rows.push(['Planbindung',value.planDigest],['Ausgewähltes Viewelement',value.selectedInstanceId]);const o=value.inferenceConsentOffer;if(o){rows.push(['Gebundene Route',o.routeId+' · '+o.provider+' · '+o.model],['Evidenz',o.evidenceClass==='SYNTHETIC_ONLY'?'Lokaler synthetischer Protokolltest, kein Sprachmodell':'Ownergebunden, echte Modellabnahme weiterhin offen'],['Preisbasis',o.currency==='NONE'?'Codeeigener lokaler Nullpreis':o.currency+' · Revision '+o.priceRevision],['Kostenobergrenze',o.currency==='NONE'?'Keine Produktkosten':String(o.limits.maxCostMicros)+' Mikroeinheiten '+o.currency],['Zeit / Turns / Tools / Requests',o.limits.maxTimeMs+' ms / '+o.limits.maxTurns+' / '+o.limits.maxTools+' / '+o.limits.maxRequests],['Tokens / Eingabe / Ausgabe',o.limits.maxTokens+' / '+o.limits.maxInputBytes+' Bytes / '+o.limits.maxOutputBytes+' Bytes'],['Übertragungsbindung',o.payloadDigest],['Identität / Angebot',o.identityDigest+' / '+o.offerDigest]);}}else{rows.push(['Native Auftragsbindung',value.requestDigest],['Verbrauch/Reservierung','Modellunits: '+value.budget.model.consumedUnits+' verbraucht / '+value.budget.model.committedUnits+' gebunden; Runtimeunits: '+value.budget.runtime.consumedUnits+' verbraucht / '+value.budget.runtime.committedUnits+' gebunden']);}rows.push(['Native Quelle',value.sourceDigest??'UNKNOWN — keine rekonstruierbaren Kontextdetails, kein erfundener Quellenstand'],['Native Quellenrevisionen',value.sourceRevisions?'ERV '+value.sourceRevisions.erv+' · Human '+value.sourceRevisions.human:'UNKNOWN']);facts.replaceChildren(...rows.flatMap(([key,val])=>[text('dt',key),text('dd',val)]));}
 async function prepare(){if(!c||busy||!usable())return;const context=c,n=serial;busy=true;plan=null;result=null;transferConsent.checked=false;if(offerTimer)clearTimeout(offerTimer);state('PLANNING','Auftrag und aktuelle native Auswahl serverseitig prüfen; noch kein Dispatch.');try{const p=validateWorkspaceAgentPlanV1(await request(context,'AGENT_PLAN',{schemaVersion:'pansphaira.workspace-agent/plan/v1',text:input.value}),context);if(!live(context,n))return;plan=p;runId=p.runId;details(p);if(p.inferenceConsentOffer)offerTimer=setTimeout(update,Math.max(0,p.inferenceConsentOffer.expiresAtMs-Date.now()));explanation.textContent=p.inferenceConsentOffer?'Plan: nur persönlicher Viewvorschlag. Erst die ausdrückliche Daten-/Budgetbestätigung und der separate einmalige Start erlauben genau dieses gebundene Angebot; kein Speichern.':'Plan: nur persönlicher Viewvorschlag. Erst der separate Start dispatcht den synthetischen Testlauf; kein Speichern.';state('PLANNED_NOT_DISPATCHED','Genauen Auftrag und Scope prüfen. Dieser Plan hat noch keinen Backendlauf gestartet.');}catch{if(live(context,n))state('PLAN_DENIED',nativeConfigured?'Aktuelle Verbindung, Ownerzweck, Quelle oder Auswahl nicht bestätigt. Vorhandene Verbindung zuerst prüfen; kein synthetischer Fallback, keine Ausführung oder automatische Wiederholung.':'Auftrag/Quelle/Auswahl nicht aktuell bestätigt. Keine Ausführung, keine automatische Wiederholung.');}finally{if(live(context,n)){busy=false;update();}}}
 async function resultOf(context:WorkspaceContextReadbackV1,value:unknown,n:number){const catalog=nativeViewCatalogV1(await request(context,'CATALOG'),context),r=validateWorkspaceAgentReadV1(value,context,catalog.fields);if(!live(context,n)||r.runId!==runId)throw Error('AGENT_RUN_BINDING_DENIED');result=r;plan=null;details(r);explanation.textContent=r.text;state(r.phase,r.phase==='RESULT_READY'?'Native Laufprojektion gelesen. Vorschlag, nicht gespeicherte View; separate aktuelle Vorschau und Bestätigung bleiben nötig.':'Schreib-/Nutzungsausgang unbestätigt; Budget bleibt gebunden. Kein Erfolgsstatus und kein blinder Startretry.');}
 async function dispatch(){const p=plan,context=c,n=serial,o=p?.inferenceConsentOffer;if(!p||!context||busy||attempted.has(p.planHandle)||p.expiresAtMs<=Date.now()||o&&(o.expiresAtMs<=Date.now()||!transferConsent.checked))return;attempted.add(p.planHandle);remember(context,p.runId);runId=p.runId;busy=true;state('DISPATCHING','Genau einen gebundenen nativen Lauf starten; eine unklare Antwort wird nicht erneut gesendet.');try{const value=await request(context,'AGENT_START',{schemaVersion:'pansphaira.workspace-agent/start/v1',planHandle:p.planHandle,planDigest:p.planDigest,...(o?{inferenceConsent:{offerDigest:o.offerDigest,confirm:true}}:{})});await resultOf(context,value,n);}catch{if(live(context,n)){plan=null;result=null;state('OUTCOME_UNCONFIRMED','Laufausgang nicht unabhängig bestätigt. Derselbe Auftrag wird nicht erneut angeboten; nur den nativen Status lesen.');}}finally{if(live(context,n)){busy=false;update();}}}
 async function reconcile(){const context=c,id=runId,n=serial;if(!context||!id||busy||context.moduleId!=='pan.erv'||!context.primaryObject)return;busy=true;state('READING_NATIVE_RUN','Gespeicherten Laufstatus frisch unabhängig lesen — kein Dispatch/Resume.');try{await resultOf(context,await request(context,'AGENT_READ',{runId:id}),n);}catch{if(live(context,n)){result=null;state('RUN_READ_DENIED','Gespeicherter Lauf nicht aktuell nativ bestätigt. Kein alter/fremder Status und kein automatischer Dispatch.');}}finally{if(live(context,n)){busy=false;update();}}}
 async function preview(){if(busy||!result?.proposal||!freshProposal())return;await options.editor.previewDelta(result.proposal.delta,'AGENT');document.getElementById('shell.module-view')?.scrollIntoView({block:'nearest'});update();}
 const unsubscribe=options.context.subscribe(context=>{serial++;c=context;plan=null;busy=false;result=null;transferConsent.checked=false;if(offerTimer)clearTimeout(offerTimer);scope.textContent=context?'Scope: '+context.moduleId+' · '+(context.primaryObject?.objectId??'kein Fachobjekt')+' · Auswahl '+(context.selection?.rowId??'keine aktuelle native Viewauswahl')+' · Fachrevision '+(context.revisions.domainRevision??'UNKNOWN')+' · Viewrevision '+context.revisions.viewRevision:'Kontext nicht aktuell bestätigt — keine Ausgabe alter Quellen.';facts.replaceChildren();explanation.textContent='Vorschläge werden bei relevanten Kontextwechseln nicht als aktuelle Änderung angeboten.';if(context){try{const saved=sessionStorage.getItem(storageKey(context));if(saved&&/^operation:ui-[a-f0-9]{48}$/.test(saved))runId=saved;else runId=null;}catch{runId=null;}}else runId=null;state('CURRENT_SCOPE',usable()?nativeConfigured?'Native Viewauswahl aktuell. Vorhandene Verbindung und genaues Daten-/Budgetangebot separat prüfen; noch kein Modellversand.':'Native Viewauswahl aktuell. Synthetischen Auftrag separat planen; echtmodellbasierter Versand bleibt deaktiviert.':'Aktuelles natives Viewelement mit dem vorhandenen Auswahlpicker wählen. Keine Ableitung aus CSS oder DOMnamen.');if(runId&&context?.moduleId==='pan.erv'&&context.primaryObject)void reconcile();});
 const unsubscribeFrame=options.editor.subscribeFrame(update);
 const api=Object.freeze({close(){if(closed)return;closed=true;serial++;if(offerTimer)clearTimeout(offerTimer);unsubscribe();unsubscribeFrame();plan=null;result=null;c=null;root.remove();}});options.signal.addEventListener('abort',api.close,{once:true});return api;
}
