import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import https from 'node:https';
import {nativeViewFixture546} from '../pan546/native-fixture.mjs';
import {createNativeWorkspaceAgentRunV1,syntheticWorkspaceViewModelV1} from '../../src/pan548/native-agent-run.mjs';
import {mountProtectedWorkspaceAgentRunV1} from '../../src/pan527/origin-session-adapter.mjs';
import {validateWorkspaceAgentPlanV1,validateWorkspaceAgentReadV1} from '../../dist/packages/contracts/src/workspace-agent-run-v1.js';
import {nativeWorkspaceViewFieldsV1} from '../../src/pan546/native-data-catalog.mjs';
async function fixture(){const f=await nativeViewFixture546(),model=syntheticWorkspaceViewModelV1('tenant-a'),original=model.providerCall;let calls=0;model.providerCall=async(...args)=>{calls++;return original(...args);};const create=()=>createNativeWorkspaceAgentRunV1({sessions:f.sessions,contextSelection:f.context,dataCatalog:f.data,viewOwner:f.view,root:join(f.root,'owned-ui-run-ledger'),model});let owner=create(),attachment;const mount=()=>{attachment=mountProtectedWorkspaceAgentRunV1(f.tls.gateway,{optIn:true,tenantId:'tenant-a',origin:f.tls.origin,identityDigest:f.sessions.binding.identityDigest,adapterVersion:'pan548-native-agent-run/v1',owner,script:readFileSync('dist/browser-workspace/workspace-agent-panel.js','utf8')});};mount();const t=f.tab(),c=t.context;t.context=f.context.claim(t.headers,{schemaVersion:'pansphaira.workspace-context/claim/v1',tabId:c.binding.tabId,moduleId:c.moduleId,viewId:c.viewId,primaryObjectId:c.primaryObject.objectId,selection:{elementId:'pan.erv.module-card',rowId:'invoice-value'},expected:{...c.revisions,epoch:c.binding.epoch}}).context;
const context=()=>f.verification(t);function wire(suffix,body,extra={},headers=t.headers){return new Promise((resolve,reject)=>{const req=https.request(f.tls.origin+'/t/tenant-a/workspace/agent-run/'+suffix,{method:body===undefined?'GET':'POST',ca:readFileSync(f.tls.options.tls.certPath),rejectUnauthorized:true,headers:{...headers,...(body===undefined?{'x-pan546-context':t.context.contextHandle}:{'content-type':'application/json'}),...extra}},res=>{const chunks=[];res.on('data',x=>chunks.push(x));res.on('end',()=>{const raw=Buffer.concat(chunks).toString();resolve({status:res.statusCode,value:res.headers['content-type']?.includes('application/json')?JSON.parse(raw):raw});});});req.on('error',reject);if(body!==undefined)req.write(typeof body==='string'?body:JSON.stringify(body));req.end();});}
return {f,t,model,create,context,wire,calls:()=>calls,get owner(){return owner;},reopen(){attachment.close();owner=create();mount();},async close(){attachment?.close();await f.close();}};}

test('PUI07 actual authenticated HTTPS plan/start and independent GET/reopened native owner ledger, closed DTO validation; no UI authority or view persistence',async()=>{const x=await fixture();try{const p=await x.wire('plan',{schemaVersion:'pansphaira.workspace-agent/plan/v1',context:x.context(),text:'Nur native persönliche View größer.'});assert.equal(p.status,200);const plan=validateWorkspaceAgentPlanV1(p.value,x.t.context);assert.equal(x.calls(),0);const command={schemaVersion:'pansphaira.workspace-agent/start/v1',context:x.context(),planHandle:plan.planHandle,planDigest:plan.planDigest};const result=await x.wire('start',command);assert.equal(result.status,200);assert.equal(result.value.phase,'RESULT_READY');validateWorkspaceAgentReadV1(result.value,x.t.context,nativeWorkspaceViewFieldsV1);assert.equal(x.calls(),2);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);const duplicate=await x.wire('start',command);assert.deepEqual(duplicate.value,result.value);assert.equal(x.calls(),2);x.reopen();const read=await x.wire('read',undefined,{'x-pan548-run':plan.runId});assert.equal(read.status,200);assert.deepEqual(read.value,result.value);assert.equal(x.calls(),2);assert.throws(()=>validateWorkspaceAgentPlanV1({...p.value,role:'admin'},x.t.context),/DTO_DENIED/);assert.throws(()=>validateWorkspaceAgentReadV1({...read.value,modelMode:'OWNER_BOUND_PROVIDER',realModelAcceptance:true},x.t.context,nativeWorkspaceViewFieldsV1),/DTO_DENIED/);assert.throws(()=>validateWorkspaceAgentReadV1({...read.value,executionAuthorityGranted:true},x.t.context,nativeWorkspaceViewFieldsV1),/DTO_DENIED/);assert.throws(()=>validateWorkspaceAgentReadV1({...read.value,binding:{...read.value.binding,tenantId:'tenant-b'}},x.t.context,nativeWorkspaceViewFieldsV1),/DTO_DENIED/);assert.throws(()=>validateWorkspaceAgentReadV1({...read.value,operations:{...read.value.operations,cancel:{available:true,reason:'FAKE_CANCEL_SUCCESS'}}},x.t.context,nativeWorkspaceViewFieldsV1),/DTO_DENIED/);let getters=0;const accessor={...p.value};Object.defineProperty(accessor,'planDigest',{enumerable:true,get(){getters++;return p.value.planDigest;}});assert.throws(()=>validateWorkspaceAgentPlanV1(accessor,x.t.context),/DTO_DENIED/);assert.equal(getters,0);}finally{await x.close();}});

test('PUI07 HTTPS native route denies schema/role/free model/foreign session-tab-origin/body/method and absent cancel-resume before synthetic dispatch; real provider descriptor never inference authority',async()=>{const x=await fixture();try{const body={schemaVersion:'pansphaira.workspace-agent/plan/v1',context:x.context(),text:'Nur persönliche View.'};for(const bad of [{...body,schemaVersion:'pansphaira.workspace-agent/plan/v0'},{...body,role:'admin'},{...body,provider:'fake-provider'},{...body,model:'gpt-6.1-sol'},{...body,text:'api_key=synthetic-do-not-dispatch'},{...body,context:{...body.context,tabId:'tab:'+'0'.repeat(32)}}])assert.notEqual((await x.wire('plan',bad)).status,200);assert.equal((await x.wire('plan',body,{origin:'https://foreign.invalid'})).status,403);assert.equal((await x.wire('plan',body,{'content-type':'text/plain'})).status,400);assert.equal((await x.wire('plan','x'.repeat(4097))).status,413);assert.notEqual((await x.wire('plan',body,{},{})).status,200);assert.equal((await x.wire('plan',undefined)).status,404);assert.equal((await x.wire('cancel',body)).status,404);assert.equal((await x.wire('resume',body)).status,404);assert.equal((await x.wire('read',undefined,{'x-pan548-run':'operation:caller-chosen'})).status,400);const foreign=x.f.tab(x.f.issue('synthetic:erv-reader','reader'));const plan=x.owner.plan(x.t.headers,body);await assert.rejects(x.owner.start(foreign.headers,{schemaVersion:'pansphaira.workspace-agent/start/v1',context:x.f.verification(foreign),planHandle:plan.planHandle,planDigest:plan.planDigest}),/AGENT_PLAN_STALE_DENIED/);assert.throws(()=>createNativeWorkspaceAgentRunV1({sessions:x.f.sessions,contextSelection:x.f.context,dataCatalog:x.f.data,viewOwner:x.f.view,root:join(x.f.root,'unpermitted-real-route'),model:{...x.model,mode:'OWNER_BOUND_PROVIDER'}}),/AGENT_REAL_ROUTE_NOT_BOUND_DENIED/);assert.equal(x.calls(),0);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);}finally{await x.close();}});
