import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {nativeViewFixture546} from '../pan546/native-fixture.mjs';
import {syntheticModelAccessPolicyV1} from '../../dist/packages/contracts/src/model-access-broker.js';
async function fixture(change=()=>{}){
 const {createNativeWorkspaceAgentRunV1}=await import('../../src/pan548/native-agent-run.mjs');
 const f=await nativeViewFixture546(),root=mkdtempSync(join(tmpdir(),'pan548-owned-native-run-'));
 const policy=syntheticModelAccessPolicyV1('OPENAI_RESPONSES');policy.routes[0].allowedTenants=['tenant:tenant-a'];policy.routes[0].allowedPurposes=['purpose:ui-view-proposal'];policy.routes[0].optionalFields=['reasoning','store'];policy.routes[0].attachmentMediaTypes=[];policy.workloadIdentities=['workload:ui-view-assistant'];policy.userIdentities=['user:workspace-personal-view'];policy.maxBudget.maxRequests=2;
 let calls=0;const model={mode:'SYNTHETIC_PROBE_ONLY',policy,providerCall:async(request,signal)=>{calls++;assert.equal(request.request.reasoning.effort,'max');assert.equal(request.request.store,false);assert.equal(signal.aborted,false);return {contentType:'text/plain',text:calls%2===1?'Nur Vorschlag, keine Speicherung.':'Native Vorschau geprüft; getrennte Bestätigung bleibt erforderlich.',toolCalls:calls%2===1?[{id:'tool:resize-001',name:'ui.view.propose',arguments:{schemaVersion:'pansphaira.workspace-module-view/delta/v1',operations:[{kind:'RESIZE',instanceId:'invoice-value',size:'large'}]}}]:[],usage:{inputTokens:2,outputTokens:2,costMicros:0}};}};
 change(model);const create=()=>createNativeWorkspaceAgentRunV1({sessions:f.sessions,contextSelection:f.context,dataCatalog:f.data,viewOwner:f.view,root,model});let owner=create();
 function tab(){const t=f.tab();const c=t.context;t.context=f.context.claim(t.headers,{schemaVersion:'pansphaira.workspace-context/claim/v1',tabId:c.binding.tabId,moduleId:c.moduleId,viewId:c.viewId,primaryObjectId:c.primaryObject.objectId,selection:{elementId:'pan.erv.module-card',rowId:'invoice-value'},expected:{...c.revisions,epoch:c.binding.epoch}}).context;return t;}
 const t=tab(),ctx=()=>f.verification(t),plan=text=>owner.plan(t.headers,{schemaVersion:'pansphaira.workspace-agent/plan/v1',context:ctx(),text}),start=p=>owner.start(t.headers,{schemaVersion:'pansphaira.workspace-agent/start/v1',context:ctx(),planHandle:p.planHandle,planDigest:p.planDigest}),read=p=>owner.read(t.headers,{schemaVersion:'pansphaira.workspace-agent/read/v1',context:ctx(),runId:p.runId});
 return {f,t,root,model,ctx,plan,start,read,get owner(){return owner;},calls:()=>calls,reopen(){owner.close();owner=create();},async close(){owner.close();await f.close();rmSync(root,{recursive:true,force:true});}};
}
test('PAN548_NATIVE_UI_RUN_ONE_REAL_SOURCE_BOUND_TOOL_PROPOSAL_TWO_BROKER_PHASES_NO_VIEW_WRITE',async()=>{const x=await fixture();try{const before=x.f.view.read(x.t.headers,x.ctx()),p=x.plan('Rechnungswert größer darstellen, nur Vorschlag.');assert.equal(p.phase,'PLANNED_NOT_DISPATCHED');assert.equal(x.calls(),0);const result=await x.start(p);assert.equal(result.phase,'RESULT_READY');assert.equal(result.modelMode,'SYNTHETIC_PROBE_ONLY');assert.equal(result.realModelAcceptance,false);assert.equal(x.calls(),2);assert.equal(result.binding.subjectId,x.t.context.binding.subjectId);assert.equal(result.sourceDigest,x.f.data.metadata(x.t.headers,x.ctx()).sourceDigest);assert.equal(result.proposal.beforeDigest,before.viewDigest);assert.equal(result.proposal.afterView.instances.find(i=>i.instanceId==='invoice-value').size,'large');assert.equal(result.personalViewPersistenceProduced,false);assert.equal(result.businessEffectProduced,false);assert.deepEqual(x.f.view.read(x.t.headers,x.ctx()),before);assert.deepEqual(x.read(p),result);assert.equal(result.operations.cancel.available,false);assert.equal(result.operations.resume.available,false);assert.equal(result.budget.runtime.consumedUnits,2);}finally{await x.close();}});
test('PAN548_NATIVE_EXACT_SAME_KEY_DUPLICATE_AND_FRESH_NATIVE_PROCESS_CONNECTION_READBACK_NEVER_NEW_DISPATCH',async()=>{const x=await fixture();try{const p=x.plan('Nur Rechnungswert größer.');const [a,b]=await Promise.all([x.start(p),x.start(p)]);assert.deepEqual(a,b);assert.equal(x.calls(),2);x.reopen();assert.deepEqual(x.read(p),a);assert.equal(x.calls(),2);}finally{await x.close();}});
test('PAN548_NATIVE_UNKNOWN_AFTER_PROVIDER_ATTEMPT_REOPEN_HELD_NO_BLIND_REPLAY_OR_FAKE_RESUME',async()=>{const x=await fixture(m=>{m.providerCall=async()=>{throw Error('genuine owner callback failed after dispatch fence');};});try{const p=x.plan('Nur Rechnungswert größer.');const r=await x.start(p);assert.equal(r.phase,'OUTCOME_UNCONFIRMED');assert.equal(r.proposal,null);assert.ok(r.budget.model.committedUnits>0);x.reopen();const after=x.read(p);assert.equal(after.phase,'OUTCOME_UNCONFIRMED');assert.equal(after.budget.model.committedUnits,r.budget.model.committedUnits);assert.equal(after.operations.resume.available,false);}finally{await x.close();}});
test('PAN548_NATIVE_STALE_CONTEXT_BEFORE_DISPATCH_AND_REVOKE_DURING_PROVIDER_NO_LATE_APPLY',async()=>{let entered,release;const gate=new Promise(r=>{release=r;}),started=new Promise(r=>{entered=r;});const x=await fixture(m=>{const original=m.providerCall;m.providerCall=async(...args)=>{entered();await gate;return original(...args);};});try{const p=x.plan('Nur Rechnungswert größer.');const running=x.start(p);await started;x.f.context.retire(x.t.headers,x.ctx());release();const r=await running;assert.equal(r.phase,'OUTCOME_UNCONFIRMED');assert.equal(r.proposal,null);assert.equal(x.calls(),1);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);assert.ok(r.budget.model.committedUnits>0);}finally{release();await x.close();}});
test('PAN548_NATIVE_MODEL_FREE_HANDLE_ROLE_CROSS_TENANT_SCHEMA_AND_OWNER_CAPABILITY_DENIED',async()=>{const x=await fixture();try{const p=x.plan('Nur Rechnungswert größer.');await assert.rejects(x.owner.start(x.t.headers,{schemaVersion:'pansphaira.workspace-agent/start/v1',context:x.ctx(),planHandle:p.planHandle,planDigest:p.planDigest,role:'admin'}),/AGENT_.*DENIED/);await assert.rejects(x.owner.start(x.t.headers,{schemaVersion:'pansphaira.workspace-agent/start/v0',context:x.ctx(),planHandle:p.planHandle,planDigest:p.planDigest}),/AGENT_.*DENIED/);await assert.rejects(x.owner.start({...x.t.headers,'x-pan548-tab':'0'.repeat(64)},{schemaVersion:'pansphaira.workspace-agent/start/v1',context:x.ctx(),planHandle:p.planHandle,planDigest:p.planDigest}),/CONTEXT_TAB_DENIED/);assert.throws(()=>x.owner.plan(x.t.headers,{schemaVersion:'pansphaira.workspace-agent/plan/v1',context:x.ctx(),text:'Only view',model:'caller-model'}),/AGENT_.*DENIED/);assert.equal(x.calls(),0);assert.equal(typeof x.owner.settle,'undefined');assert.equal(typeof x.owner.activate,'undefined');}finally{await x.close();}});
test('PAN548_NATIVE_MODEL_FOREIGN_TOOL_AND_AUTHORITY_ARGUMENTS_NEVER_VIEW_OR_FACH_EFFECT',async()=>{const x=await fixture(m=>{m.providerCall=async()=>({contentType:'text/plain',text:'untrusted proposal',toolCalls:[{id:'tool:unsafe-001',name:'ui.view.propose',arguments:{schemaVersion:'pansphaira.workspace-module-view/delta/v1',operations:[{kind:'SHOW',instanceId:'invoice-value',visible:false}],authority:'admin'}}],usage:{inputTokens:2,outputTokens:2,costMicros:0}});});try{const p=x.plan('Nur Rechnungswert größer.');const r=await x.start(p);assert.equal(r.phase,'OUTCOME_UNCONFIRMED');assert.equal(r.proposal,null);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);}finally{await x.close();}});
test('PAN548_NATIVE_NONMODAL_SELECTION_NULL_CLARIFY_AND_CREDENTIAL_OR_ACCESSOR_INPUT_NO_DISPATCH',async()=>{const x=await fixture();try{const t=x.f.tab();assert.throws(()=>x.owner.plan(t.headers,{schemaVersion:'pansphaira.workspace-agent/plan/v1',context:x.f.verification(t),text:'Mach größer.'}),/AGENT_SELECTION_CLARIFY_REQUIRED/);let reads=0;const value={schemaVersion:'pansphaira.workspace-agent/plan/v1',context:x.ctx()};Object.defineProperty(value,'text',{enumerable:true,get(){reads++;return 'unsafe';}});assert.throws(()=>x.owner.plan(x.t.headers,value),/AGENT_.*DENIED/);assert.equal(reads,0);assert.throws(()=>x.plan('api_key='+'sk'+'-aaaaaaaaaaaaaaaaaaaaaaaaaaaa'),/AGENT_.*DENIED/);assert.equal(x.calls(),0);}finally{await x.close();}});
test('PAN548_NATIVE_REAL_SETTLEMENT_SQLITE_WAIT_PAST_ACTUAL_LEASE_RETAINS_FULL_UNKNOWN_USAGE_NO_LATE_RESULT', {timeout:90000}, async()=>{
 const {Worker}=await import('node:worker_threads'),{DatabaseSync}=await import('node:sqlite'),{readdirSync}=await import('node:fs');let x,p,worker,lockedAt;
 x=await fixture(m=>{const original=m.providerCall;m.providerCall=async(...args)=>{const result=await original(...args);if(result.toolCalls.length===0){const directory=readdirSync(x.root).find(n=>n.startsWith('ui-view-run-'));assert.ok(directory);const database=join(x.root,directory,'resource-budget.sqlite');worker=new Worker(`const {parentPort,workerData}=require('node:worker_threads');const {DatabaseSync}=require('node:sqlite');const db=new DatabaseSync(workerData.database);db.exec('PRAGMA busy_timeout=15000; BEGIN IMMEDIATE');parentPort.postMessage({kind:'LOCKED',at:Date.now()});setTimeout(()=>{db.exec('ROLLBACK');db.close();parentPort.postMessage({kind:'RELEASED',at:Date.now()});parentPort.close();},Math.max(0,workerData.releaseAt-Date.now()));`,{eval:true,workerData:{database,releaseAt:p.expiresAtMs+200}});const message=await new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);});assert.equal(message.kind,'LOCKED');lockedAt=message.at;assert.ok(lockedAt<p.expiresAtMs,'Genuine SQLite write lock must begin before actual native lease expiry, not fake clock or expired start');}return result;};});
 try{p=x.plan('Nur native persönliche View größer; Abschluss während echter Lease-Verwerfung prüfen.');await new Promise(resolve=>setTimeout(resolve,Math.max(0,p.expiresAtMs-Date.now()-1800)));const result=await x.start(p);assert.ok(Date.now()>p.expiresAtMs,'Actual unchanged native 60000ms lease expires during real SQLite writer wait');assert.equal(result.phase,'OUTCOME_UNCONFIRMED','NATIVE_SETTLEMENT_MUST_REVERIFY_AFTER_SQLITE_WAIT_BEFORE_RELEASE_OR_RESULT_READY');assert.equal(result.proposal,null);assert.equal(x.calls(),2);assert.equal(result.budget.model.committedUnits,x.model.policy.maxBudget.maxTokens*4);assert.equal(result.budget.model.consumedUnits,0);assert.equal(result.budget.runtime.committedUnits,2);const directory=readdirSync(x.root).find(n=>n.startsWith('ui-view-run-')),db=new DatabaseSync(join(x.root,directory,'resource-budget.sqlite'),{readOnly:true});try{const row=db.prepare('SELECT state,result_json,completion FROM reservations WHERE operation_id=?').get(p.runId);assert.equal(row.state,'UNKNOWN_USAGE');assert.equal(row.result_json,null);assert.equal(row.completion,null);}finally{db.close();}x.f.fresh(x.t);x.reopen();const read=x.read(p);assert.equal(read.phase,'OUTCOME_UNCONFIRMED');assert.equal(read.budget.model.committedUnits,result.budget.model.committedUnits);assert.equal(x.calls(),2);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);console.log(JSON.stringify({actualSettlementLockBeforeLeaseExpiry:lockedAt,actualLeaseExpiresAt:p.expiresAtMs,actualReadAfterWait:Date.now(),unknownNativeUsageHeld:true,realModelAcceptance:false}));}finally{await worker?.terminate();await x.close();}
});
test('PAN548_NATIVE_VIEW_COMMIT_IS_ONLY_EXISTING546_CONFIRM_CAS_READBACK_UNDO_NOT_MODEL_TASK_SETTLEMENT',async()=>{const x=await fixture();try{const p=x.plan('Nur Rechnungswert größer.');const result=await x.start(p);assert.equal(x.f.store.read(x.f.sessions.authenticate(x.t.headers)).revision,0);const preview=x.f.view.preview(x.t.headers,{schemaVersion:'pansphaira.workspace-module-view/preview/v1',context:x.ctx(),delta:result.proposal.delta});const receipt=x.f.view.confirm(x.t.headers,x.f.confirmation(x.t,preview));assert.equal(receipt.outcome,'VIEW_PERSISTED');x.f.fresh(x.t);const read=x.f.view.read(x.t.headers,x.ctx());assert.equal(read.viewDigest,preview.afterDigest);assert.equal(read.revision,1);const undo=x.f.view.previewUndo(x.t.headers,{schemaVersion:'pansphaira.workspace-module-view/undo-preview/v1',context:x.ctx(),targetRevision:0});assert.equal(x.f.view.confirm(x.t.headers,x.f.confirmation(x.t,undo)).revision,2);assert.equal(x.calls(),2);}finally{await x.close();}});
