import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {nativeViewBrowserFixture546} from './browser-fixture.mjs';
import {ervPluginV1} from '../../dist/packages/browser-workspace/src/plugin-erv-v1.js';
const id='AP-PAN516-PARTIAL-01',region='[id="shell.invoice-navigation"]',guard='.invoice-navigation-dirtyguard',view='[id="shell.module-view"]';
const ready=p=>p.locator(region+'[data-state="SEARCH_READY"]').waitFor();
const current=p=>p.locator(view+'[data-state="CURRENT_NATIVE_VIEW"]').waitFor();
async function start(f,path='/workspace/erv'){await f.page.goto(f.tls.origin+'/t/tenant-a/workspace#'+path);await f.page.locator('[data-profile-state="READY"]').waitFor();if(path==='/workspace/erv'){await current(f.page);await ready(f.page);}else await f.page.locator(region).waitFor();assert.equal(await f.page.evaluate(()=>isSecureContext),true);}
async function search(p,q='PARTIAL',state='ONE_NATIVE_MATCH'){await p.getByRole('searchbox',{name:'Native Vorgangs-ID suchen',exact:true}).fill(q);await p.getByRole('button',{name:'Native Rechnungen suchen',exact:true}).click();await p.locator(region+'[data-state="'+state+'"]').waitFor();}
const choose=p=>p.locator('.invoice-navigation-candidates').getByRole('button',{name:new RegExp(id)}).click();
const keep=p=>p.getByRole('button',{name:'Entwurf behalten — Navigation abbrechen',exact:true});
const discard=p=>p.getByRole('button',{name:'Ungespeicherte Entwürfe verwerfen und navigieren',exact:true});
async function rendered(f){await f.page.locator(region+'[data-state="BROWSER_RENDERED_AND_ACK_REPORTED"]').waitFor();await current(f.page);await f.flushResponses();const state=await f.page.locator(region).evaluate(n=>({...n.dataset})),invoice=f.reader.read({tenantId:'tenant-a',objectId:id,expectedRevision:null});assert.equal(state.object,id);assert.equal(Number(state.dataRevision),invoice.revision);assert.ok(state.tab&&Number.isSafeInteger(Number(state.epoch)));assert.match(await f.page.locator('[id="shell.main"]').innerText(),new RegExp(id));const r=f.responses.findLast(r=>r.path.endsWith('/invoice-navigation/read')&&r.status===200),a=f.responses.findLast(r=>r.path.endsWith('/invoice-navigation/ack')&&r.status===200);assert.deepEqual(r.value.invoice,invoice);assert.deepEqual(a.value.rendered,{moduleId:'pan.erv',viewId:'pan.erv.view',objectId:id,dataRevision:invoice.revision,tabId:state.tab,epoch:Number(state.epoch)});assert.equal(a.value.serverCertifiedBrowserRender,false);assert.equal(a.value.executionAuthorityGranted,false);return {state,invoice,read:r.value,ack:a.value};}
async function geometry(p){const value=await p.evaluate(()=>{const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden';};const nodes=[...document.querySelectorAll('[id="shell.invoice-navigation"] button,[id="shell.invoice-navigation"] input,.invoice-navigation-dirtyguard,[id="shell.invoice-navigation"] p')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,text:(e.textContent??'').slice(0,180),rect:r.toJSON(),scrollWidth:e.scrollWidth,clientWidth:e.clientWidth};});return {viewport:{width:innerWidth,height:innerHeight},document:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight},zoom:document.documentElement.style.zoom||'1',dpr:devicePixelRatio,hash:location.hash,nodes};});assert.ok(value.nodes.length>0);assert.ok(value.document.width<=value.viewport.width+2);for(const n of value.nodes){assert.ok(n.rect.width>0&&n.rect.height>0);assert.ok(n.rect.x>=-2&&n.rect.right<=value.viewport.width+2,JSON.stringify(n));assert.ok(n.scrollWidth<=n.clientWidth+2,JSON.stringify(n));}return value;}
async function shot(f,name){const D=process.env.PAN546_BROWSER_EVIDENCE;mkdirSync(D,{recursive:true});const g=await geometry(f.page),state=await f.page.locator(region).evaluate(n=>({...n.dataset})),bytes=await f.page.screenshot({path:join(D,name+'.png'),fullPage:true});const r={name,...g,state,png:{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)},sha256:createHash('sha256').update(bytes).digest('hex'),build:{app:createHash('sha256').update(readFileSync('dist/browser-workspace/app.js')).digest('hex'),navigation:createHash('sha256').update(readFileSync('dist/browser-workspace/workspace-invoice-navigation.js')).digest('hex')},actualCSSZoomOnlyNotBrowserNativeZoom:true};writeFileSync(join(D,name+'.capture.json'),JSON.stringify(r,null,2)+'\n');return r;}
const writes=f=>f.requests.filter(r=>r.method==='POST'&&/\/(?:confirm|decide|configuration)$/.test(r.path)||r.method==='POST'&&r.path.endsWith('/profile'));
async function log(f,name,extras={}){await f.flushResponses();const safe=JSON.stringify({requests:f.requests,responses:f.responses,errors:f.errors,...extras},(k,v)=>['tabProof','contextHandle','candidateHandle','targetHandle','requestHandle','readReceiptHandle','csrfProof','sessionId'].includes(k)?'[REDACTED_EPHEMERAL_CAPABILITY]':v,2);writeFileSync(join(process.env.PAN546_BROWSER_EVIDENCE,name+'.receipt.json'),safe+'\n');}
test('DUI05 original3AC/UIDOD1-5 positive actual HTTPS source candidates NONE/AMBIGUOUS/ONE explicit keyboard choice; requested is not render; native values, revision, current view/tab/epoch exact in actual DOM and ACK; desktop390/CSS200/focus no business or personal writes',async()=>{const f=await nativeViewBrowserFixture546({invoiceNavigation:true});let release;try{const p=f.page,before=f.business(),personal=JSON.stringify(f.readPersisted());await start(f);await shot(f,'navigation-desktop-ready');await search(p,'NO-NATIVE-HIT','NO_NATIVE_MATCH');assert.equal(await p.locator('.invoice-navigation-candidates button').count(),0);assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/request')).length,0);await shot(f,'navigation-desktop-no-match');await search(p,'AP-PAN516','AMBIGUOUS_NATIVE_MATCH');assert.equal(await p.locator('.invoice-navigation-candidates button').count(),2);assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/request')).length,0);await shot(f,'navigation-desktop-ambiguous');await search(p);await p.keyboard.press('Tab');const focus=await p.evaluate(()=>({text:document.activeElement.textContent,outline:getComputedStyle(document.activeElement).outlineStyle,rect:document.activeElement.getBoundingClientRect().toJSON()}));assert.match(focus.text,new RegExp(id));assert.notEqual(focus.outline,'none');let readObserved;const seen=new Promise(r=>{readObserved=r;}),gate=new Promise(r=>{release=r;});await p.route('**/workspace/invoice-navigation/read',async route=>{readObserved();await gate;await route.continue();});await p.keyboard.press('Enter');await seen;await p.locator(region+'[data-state="NAVIGATION_REQUESTED"]').waitFor();assert.equal(await p.locator(region+'[data-state="BROWSER_RENDERED_AND_ACK_REPORTED"]').count(),0);assert.doesNotMatch(await p.locator('[id="shell.main"]').innerText(),new RegExp(id));await shot(f,'navigation-desktop-request-not-render');release();await rendered(f);await p.unroute('**/workspace/invoice-navigation/read');const positive=await rendered(f);await shot(f,'navigation-desktop-native-rendered');await p.setViewportSize({width:390,height:844});await shot(f,'navigation-390-native-rendered');await p.setViewportSize({width:1280,height:900});await p.evaluate(()=>{document.documentElement.style.zoom='2';});await shot(f,'navigation-desktop-css200-native-rendered');await p.evaluate(()=>{document.documentElement.style.zoom='1';});assert.equal(f.business(),before);assert.equal(JSON.stringify(f.readPersisted()),personal);assert.deepEqual(writes(f),[]);assert.deepEqual(f.errors,[]);assert.ok(f.requests.some(r=>r.path.endsWith('/invoice-navigation/request')));assert.ok(f.requests.some(r=>r.path.endsWith('/invoice-navigation/read')));assert.ok(f.requests.some(r=>r.path.endsWith('/invoice-navigation/ack')));await log(f,'navigation-positive',{positive,focus});}finally{release?.();await f.close();}});
test('DUI05 original dirtyguard PERSONAL_MODULE_VIEW preserves actual unsaved typed native view on keep/Escape, discards only explicit local/CANCEL on proceed; no CONFIRM or business mutation, exact destination render',async()=>{const f=await nativeViewBrowserFixture546({invoiceNavigation:true});try{const p=f.page,before=f.business(),personal=JSON.stringify(f.readPersisted());await start(f);await p.getByRole('button',{name:'View bearbeiten',exact:true}).click();await p.getByLabel('Elementgröße',{exact:true}).selectOption('large');await search(p);await choose(p);await p.locator(guard).waitFor();assert.match(await p.locator(guard).innerText(),/Persönlicher ERV-Viewentwurf/);assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/request')).length,0);await p.setViewportSize({width:390,height:844});const bindingLabels=await p.locator('#pan546-field-binding').evaluate(select=>{const s=getComputedStyle(select),c=document.createElement('canvas').getContext('2d');c.font=s.font;return [...select.options].map(o=>({label:o.textContent,value:o.value,ink:c.measureText(o.textContent).width,available:select.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight)-20}));});for(const o of bindingLabels){assert.ok(o.ink<=o.available,JSON.stringify(o));assert.doesNotMatch(o.label,/CURRENCY_MINOR/);assert.match(o.value,/^erv\.invoice\./);}assert.match(await p.locator('.module-view-binding-details').innerText(),/Rechnungsbetrag · CURRENCY_MINOR.*Erwarteter Betrag · CURRENCY_MINOR/);await shot(f,'navigation-390-view-dirtyguard');assert.equal(await keep(p).evaluate(n=>n===document.activeElement),true);await keep(p).click();assert.equal(await p.getByLabel('Elementgröße',{exact:true}).inputValue(),'large');assert.equal(await p.locator(view).getAttribute('data-editing'),'true');await choose(p);await p.keyboard.press('Escape');assert.equal(await p.locator(guard).isVisible(),false);await choose(p);await discard(p).click();await rendered(f);assert.equal(await p.locator(view).getAttribute('data-editing'),'false');assert.equal(f.business(),before);assert.equal(JSON.stringify(f.readPersisted()),personal);assert.deepEqual(writes(f),[]);assert.deepEqual(f.errors,[]);await log(f,'navigation-dirty-module-view');}finally{await f.close();}});
test('DUI05 original dirtyguard PERSONAL_SHELL_PROFILE retains local presentation and unconfirmed profile proposal; explicit navigation discard independently GETs saved profile, not save/confirm',async()=>{const f=await nativeViewBrowserFixture546({invoiceNavigation:true});try{const p=f.page,before=f.business();await start(f);const saved=await p.evaluate(async()=>{const r=await fetch(location.pathname+'/profile');return r.json();});await p.getByRole('button',{name:'Darstellung anpassen',exact:true}).click();await p.getByRole('checkbox',{name:'Informationspanel anzeigen',exact:true}).check();await p.getByRole('button',{name:'Profil speichern',exact:true}).click();await p.getByRole('button',{name:'Speichern bestätigen',exact:true}).waitFor();await search(p);await choose(p);await p.locator(guard).waitFor();assert.match(await p.locator(guard).innerText(),/Persönliches Darstellungsprofil/);await shot(f,'navigation-desktop-profile-dirtyguard');await keep(p).click();assert.equal(await p.getByRole('checkbox',{name:'Informationspanel anzeigen',exact:true}).isChecked(),true);assert.equal(await p.getByRole('button',{name:'Speichern bestätigen',exact:true}).isVisible(),true);assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/request')).length,0);await choose(p);const reads=f.requests.filter(r=>r.path.endsWith('/profile')&&r.method==='GET').length;await discard(p).click();await rendered(f);assert.ok(f.requests.filter(r=>r.path.endsWith('/profile')&&r.method==='GET').length>reads);assert.equal(await p.getByRole('checkbox',{name:'Informationspanel anzeigen',exact:true}).isChecked(),false);const after=await p.evaluate(async()=>{const r=await fetch(location.pathname+'/profile');return r.json();});assert.deepEqual(after,saved);assert.deepEqual(writes(f),[]);assert.equal(f.business(),before);assert.deepEqual(f.errors,[]);await log(f,'navigation-dirty-shell-profile');}finally{await f.close();}});
test('DUI05 original dirtyguard AGENT_CONFIGURATION intercepts manual navigation from genuine configuration editor; keeps unsaved input, explicit discard does not save and disposes editor/callbacks',async()=>{const f=await nativeViewBrowserFixture546({invoiceNavigation:true,configurationDrafts:true});try{const p=f.page,before=f.business();await start(f,'/workspace/configuration');await p.locator('[data-backend="configuration"][data-outcome="EMPTY"]').waitFor();const saved=JSON.stringify(f.readConfiguration());await p.getByRole('combobox',{name:'Ziel und Zweck der begrenzten Mitarbeiterassistenz',exact:true}).selectOption(JSON.stringify('employee.business.help'));const old=p.url();await p.locator('[id="shell.navigation"]').getByRole('button',{name:'Eingangsrechnungsprüfung — nur lesen',exact:true}).click();await p.locator(guard).waitFor();assert.equal(p.url(),old);assert.match(await p.locator(guard).innerText(),/Konfiguration/);await shot(f,'navigation-desktop-configuration-dirtyguard');await keep(p).click();assert.equal(await p.getByRole('combobox',{name:'Ziel und Zweck der begrenzten Mitarbeiterassistenz',exact:true}).inputValue(),JSON.stringify('employee.business.help'));await p.locator('[id="shell.navigation"]').getByRole('button',{name:'Eingangsrechnungsprüfung — nur lesen',exact:true}).click();await p.locator(guard).waitFor();await discard(p).click();await current(p);await ready(p);assert.equal(await p.locator('.configuration-draft').count(),0);assert.equal(JSON.stringify(f.readConfiguration()),saved);assert.deepEqual(writes(f),[]);await search(p);await choose(p);await rendered(f);assert.equal(f.business(),before);assert.deepEqual(f.errors,[]);await log(f,'navigation-dirty-configuration');}finally{await f.close();}});
test('DUI05 manual navigation supersedes a genuine already returned native target-read response; late receipt cannot replace setup/context or post an ACK, logout disposes owned navigation',async()=>{
 const f=await nativeViewBrowserFixture546({invoiceNavigation:true});let client,paused;
 try{
  const p=f.page,before=f.business();await start(f);await search(p);
  client=await f.context.newCDPSession(p);
  await client.send('Fetch.enable',{patterns:[{urlPattern:'*workspace/invoice-navigation/read',requestStage:'Response'}]});
  // Observe the browser's TLS-verified response, not a second API transport.
  const seen=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('GENUINE_CHROMIUM_NATIVE_READ_RESPONSE_NOT_OBSERVED')),10000);client.once('Fetch.requestPaused',event=>{clearTimeout(timer);paused=event;resolve(event);});});
  await choose(p);const event=await seen;assert.equal(event.responseStatusCode,200);
  const raw=await client.send('Fetch.getResponseBody',{requestId:event.requestId}),actual={status:event.responseStatusCode,value:JSON.parse(raw.base64Encoded?Buffer.from(raw.body,'base64').toString():raw.body)};
  assert.equal(actual.value.outcome,'NATIVE_TARGET_READBACK_RECEIVED');
  await p.locator(region+'[data-state="NAVIGATION_REQUESTED"]').waitFor();
  await p.locator('[id="shell.navigation"]').getByRole('button',{name:'Einrichtung und Betriebszustand',exact:true}).click();
  await p.locator('[id="shell.main"]').getByRole('heading',{name:'Einrichtung und Betriebszustand',exact:true}).waitFor();
  // Continue the real TLS-verified Chromium response unchanged, after manual action.
  await client.send('Fetch.continueResponse',{requestId:event.requestId});paused=null;await client.send('Fetch.disable');
  await p.locator('[id="shell.context-selection"][data-module="pan.setup"][data-state="CURRENT_CONTEXT"]').waitFor();
  assert.equal(new URL(p.url()).hash,'#/workspace/setup');assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/ack')).length,0);assert.equal(await p.locator(region+'[data-state="BROWSER_RENDERED_AND_ACK_REPORTED"]').count(),0);
  await shot(f,'navigation-desktop-late-native-read-manual-setup');assert.equal(f.business(),before);
  await p.locator('[id="shell.logout"]').click();await p.getByRole('heading',{name:'Abgemeldet',exact:true}).waitFor();assert.equal(await p.locator(region).count(),0);assert.equal(await p.locator(view).count(),0);assert.deepEqual(writes(f),[]);assert.deepEqual(f.errors,[]);await log(f,'navigation-manual-late-disposal',{actual});
 }finally{if(paused)try{await client.send('Fetch.continueResponse',{requestId:paused.requestId});}catch{/* only owned canceled request */}await client?.detach();await f.close();}
});
test('DUI05 actual registered native plugin retirement, external URL and copied foreign render tab fail visibly closed with no metadata leak/effect; failed optional navigation script leaves original setup/ERV/logout operable',async()=>{const f=await nativeViewBrowserFixture546({invoiceNavigation:true});const enabled=ervPluginV1.enabled;try{const p=f.page,before=f.business();await start(f);const count=f.requests.filter(r=>r.path.includes('/invoice-navigation/')).length;await search(p,'https://untrusted.invalid/','NATIVE_SEARCH_DENIED');assert.equal(f.requests.filter(r=>r.path.includes('/invoice-navigation/')).length,count);await shot(f,'navigation-desktop-external-url-denied');await search(p);ervPluginV1.enabled=false;await choose(p);await p.locator(region+'[data-state="NAVIGATION_NOT_CONFIRMED"]').waitFor();assert.equal(f.requests.filter(r=>r.path.endsWith('/invoice-navigation/ack')).length,0);await shot(f,'navigation-desktop-plugin-retired-denied');ervPluginV1.enabled=enabled;await search(p);await p.route('**/workspace/invoice-navigation/ack',route=>{const value=route.request().postDataJSON();value.rendered.tabId='tab:'+'a'.repeat(32);return route.continue({postData:JSON.stringify(value)});});await choose(p);await p.locator(region+'[data-state="NAVIGATION_NOT_CONFIRMED"]').waitFor();await f.flushResponses();assert.equal(f.responses.findLast(r=>r.path.endsWith('/invoice-navigation/ack')).status,400);assert.equal(await p.locator(region).getAttribute('data-object'),null);await shot(f,'navigation-desktop-foreign-tab-ack-denied');await p.unroute('**/workspace/invoice-navigation/ack');await p.route('**/workspace/invoice-navigation/app.js',route=>route.abort());await p.reload();await p.getByText('Suche nicht verfügbar.',{exact:true}).waitFor();assert.equal(await p.locator(region).count(),0);await p.locator('[id="shell.navigation"]').getByRole('button',{name:'Einrichtung und Betriebszustand',exact:true}).click();await p.locator('[id="shell.main"]').getByRole('heading',{name:'Einrichtung und Betriebszustand',exact:true}).waitFor();await p.locator('[id="shell.navigation"]').getByRole('button',{name:'Eingangsrechnungsprüfung — nur lesen',exact:true}).click();await current(p);assert.match(await p.locator(view).innerText(),/Rechnungsbetrag/);await p.locator('[id="shell.logout"]').click();await p.getByRole('heading',{name:'Abgemeldet',exact:true}).waitFor();assert.equal(f.business(),before);assert.deepEqual(writes(f),[]);assert.deepEqual(f.errors,[]);await log(f,'navigation-native-denials-and-module-isolation');}finally{ervPluginV1.enabled=enabled;await f.close();}});

// Four concrete review524 interleavings, real TLS-verified native replies.
// CDP pauses/loses the browser's existing response; no substitute API or write.
async function holdNativeReply(f,suffix){
 const client=await f.context.newCDPSession(f.page);let paused,timer;
 const seen=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('REVIEW524_GENUINE_NATIVE_REPLY_NOT_OBSERVED')),10000);client.on('Fetch.requestPaused',async e=>{if(e.request.method!=='POST'){await client.send('Fetch.continueResponse',{requestId:e.requestId});return;}clearTimeout(timer);paused=e;const b=await client.send('Fetch.getResponseBody',{requestId:e.requestId});resolve({status:e.responseStatusCode,value:JSON.parse(Buffer.from(b.body,b.base64Encoded?'base64':'utf8').toString())});});});
 await client.send('Fetch.enable',{patterns:[{urlPattern:'*workspace/'+suffix,requestStage:'Response'}]});
 return {seen,async release(lose=false){if(paused){const e=paused;paused=null;await client.send(lose?'Fetch.failRequest':'Fetch.continueResponse',lose?{requestId:e.requestId,errorReason:'Failed'}:{requestId:e.requestId});}},async close(){clearTimeout(timer);if(paused)await client.send('Fetch.continueResponse',{requestId:paused.requestId}).catch(()=>{});await client.send('Fetch.disable').catch(()=>{});await client.detach();}};
}
const setupNavigation=p=>p.locator('[id="shell.navigation"]').getByRole('button',{name:'Einrichtung und Betriebszustand',exact:true});
const unresolved=p=>p.locator(view+'[data-state="WRITE_OUTCOME_UNCONFIRMED"]');
const reconcileView=p=>p.getByRole('button',{name:'Unklaren Schreibausgang unabhängig zurücklesen',exact:true});
async function lostNativeViewConfirm(f){
 const p=f.page;await start(f);await p.getByRole('button',{name:'View bearbeiten',exact:true}).click();await p.getByLabel('Elementgröße',{exact:true}).selectOption('large');await p.getByRole('button',{name:'Vorher/Nachher prüfen',exact:true}).click();await p.locator(view+'[data-state="PREVIEW_ONLY"]').waitFor();
 const held=await holdNativeReply(f,'module-view/confirm');await p.getByRole('button',{name:'Genau diese persönliche View bestätigen und speichern',exact:true}).click();const actual=await held.seen;assert.equal(actual.status,200);assert.equal(actual.value.outcome,'VIEW_PERSISTED');assert.equal(f.readPersisted().revision,1);await held.release(true);await unresolved(p).waitFor();await held.close();return actual;
}
test('DUI05 review524 AC03 configuration clean-input genuine save-in-flight cannot be discarded or retired by manual navigation; independent read resolves without retry',async()=>{
 const f=await nativeViewBrowserFixture546({invoiceNavigation:true,configurationDrafts:true});let held;
 try{const p=f.page,before=f.business();await start(f,'/workspace/configuration');await p.locator('[data-backend="configuration"][data-outcome="EMPTY"]').waitFor();const initial=f.readConfiguration().revision;held=await holdNativeReply(f,'configuration');await p.getByRole('button',{name:'Als unbekannt speichern',exact:true}).click();const actual=await held.seen;assert.equal(actual.status,200);assert.equal(f.readConfiguration().revision,initial+1);const old=p.url();await setupNavigation(p).click();await p.locator(guard).waitFor();assert.equal(p.url(),old);await discard(p).click();await p.getByText(/Entwurf nicht sicher verworfen/).waitFor();assert.equal(p.url(),old);assert.equal(await p.locator('[data-backend="configuration"]').count(),1);await keep(p).click();await held.release();await p.locator('[data-backend="configuration"][data-outcome="PERSISTED"]').waitFor();assert.equal(f.requests.filter(r=>r.method==='POST'&&r.path.endsWith('/configuration')).length,1);await setupNavigation(p).click();await p.locator('[id="shell.main"]').getByRole('heading',{name:'Einrichtung und Betriebszustand',exact:true}).waitFor();assert.equal(f.business(),before);assert.deepEqual(f.errors,[]);await log(f,'review524-configuration-inflight',{actual});}finally{await held?.close();await f.close();}
});
test('DUI05 review524 AC03 lost genuine native personal CAS remains dirty and reconciliation survives explicit guard discard/CANCEL without write replay',async()=>{
 const f=await nativeViewBrowserFixture546({invoiceNavigation:true});try{const p=f.page,before=f.business(),actual=await lostNativeViewConfirm(f),old=p.url();await setupNavigation(p).click();await p.locator(guard).waitFor();await discard(p).click();await p.getByText(/Entwurf nicht sicher verworfen/).waitFor();assert.equal(p.url(),old);assert.equal(await reconcileView(p).isVisible(),true);assert.equal(f.requests.filter(r=>r.path.endsWith('/module-view/cancel')).length,0);assert.equal(f.requests.filter(r=>r.path.endsWith('/module-view/confirm')).length,1);await keep(p).click();await reconcileView(p).click();await p.locator(view+'[data-state="SAVED_AND_NATIVE_READBACK_CONFIRMED"]').waitFor();assert.equal(f.readPersisted().revision,1);assert.equal(f.requests.filter(r=>r.path.endsWith('/module-view/confirm')).length,1);assert.equal(f.business(),before);assert.deepEqual(f.errors,[]);await log(f,'review524-view-unknown-discard-refused',{actual});}finally{await f.close();}
});
test('DUI05 review524 AC03 actual stale selection/context-null cannot erase unknown native personal CAS; live values retired but same-source independent reconciliation remains',async()=>{
 const f=await nativeViewBrowserFixture546({invoiceNavigation:true});try{const p=f.page,before=f.business(),actual=await lostNativeViewConfirm(f);await p.locator('[id="shell.context-selection"] button').first().click();await p.locator('[id="shell.context-selection"][data-state="CONTEXT_UNAVAILABLE"]').waitFor();assert.equal(await reconcileView(p).isVisible(),true);assert.equal(await p.locator(view+' .module-view-card').count(),0);const old=p.url();await setupNavigation(p).click();await p.locator(guard).waitFor();assert.equal(p.url(),old);await keep(p).click();await reconcileView(p).click();await p.locator(view+'[data-state="SAVED_AND_NATIVE_READBACK_CONFIRMED"]').waitFor();assert.equal(f.readPersisted().revision,1);assert.equal(f.requests.filter(r=>r.path.endsWith('/module-view/confirm')).length,1);assert.equal(f.business(),before);assert.deepEqual(f.errors,[]);await log(f,'review524-view-unknown-context-failure',{actual});}finally{await f.close();}
});
test('DUI05 review524 AC03 optional search bundle failed: minimal shell draft admission preserves real unsaved view before manual setup; explicit existing discard then clean navigation/logout independent',async()=>{
 const f=await nativeViewBrowserFixture546({invoiceNavigation:true});try{const p=f.page,before=f.business();await p.route('**/workspace/invoice-navigation/app.js',r=>r.abort());await p.goto(f.tls.origin+'/t/tenant-a/workspace#/workspace/erv');await p.getByText('Suche nicht verfügbar.',{exact:true}).waitFor();await current(p);await p.getByRole('button',{name:'View bearbeiten',exact:true}).click();await p.getByLabel('Elementgröße',{exact:true}).selectOption('large');const old=p.url();await setupNavigation(p).click();await p.getByText(/Navigation angehalten.*Entwurf/).waitFor();assert.equal(p.url(),old);assert.equal(await p.locator(view).getAttribute('data-editing'),'true');assert.equal(await p.getByLabel('Elementgröße',{exact:true}).inputValue(),'large');assert.equal(f.readPersisted().revision,0);await p.getByRole('button',{name:'Entwurf verwerfen',exact:true}).click();await p.locator(view+'[data-state="LOCAL_DRAFT_DISCARDED"]').waitFor();await setupNavigation(p).click();await p.locator('[id="shell.main"]').getByRole('heading',{name:'Einrichtung und Betriebszustand',exact:true}).waitFor();await p.locator('[id="shell.logout"]').click();await p.getByRole('heading',{name:'Abgemeldet',exact:true}).waitFor();assert.equal(f.business(),before);assert.deepEqual(writes(f),[]);assert.deepEqual(f.errors,[]);await log(f,'review524-bundle-failure-dirty-fallback');}finally{await f.close();}
});

