import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {nativeViewBrowserFixture546} from './browser-fixture.mjs';
const digest=b=>createHash('sha256').update(b).digest('hex');
const root='[id="shell.module-view"]';
async function ready(f,state='CURRENT_NATIVE_VIEW'){try{await f.page.locator(root+'[data-state="'+state+'"]').waitFor();}catch(error){await f.flushResponses();mkdirSync(process.env.PAN546_BROWSER_EVIDENCE,{recursive:true,mode:0o700});const actual=await f.page.evaluate(()=>({root:document.getElementById('shell.module-view')?.outerHTML??null,context:document.getElementById('shell.context-selection')?.outerHTML??null,bodyOwnerModuleViews:document.body.dataset.ownerModuleViews}));writeFileSync(join(process.env.PAN546_BROWSER_EVIDENCE,'actual-failed-'+state+'-'+Date.now()+'.json'),JSON.stringify({expectedState:state,actual,errors:f.errors,requests:f.requests,responses:f.responses},null,2)+'\n');console.log('PAN546_ACTUAL_FAILED_BROWSER_STATE '+JSON.stringify({expectedState:state,actual,errors:f.errors,responseOutcomes:f.responses.map(r=>({path:r.path,status:r.status,error:r.value.error??null}))}));throw error;}}
async function open(f){await f.page.goto(f.tls.origin+'/t/tenant-a/workspace');await f.page.locator('[id="shell.context-selection"][data-module="pan.setup"][data-state="CURRENT_CONTEXT"]').waitFor();await f.page.getByRole('button',{name:'Eingangsrechnungsprüfung — nur lesen',exact:true}).click();await ready(f);}
async function capture(f,name){mkdirSync(process.env.PAN546_BROWSER_EVIDENCE,{recursive:true,mode:0o700});const image=join(process.env.PAN546_BROWSER_EVIDENCE,name+'.png');await f.page.screenshot({path:image,fullPage:true});const dimensions=await f.page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth,zoom:getComputedStyle(document.body).zoom,controls:[...document.querySelectorAll('button:not(:disabled),select,a')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return{label:e.textContent,left:r.left,right:r.right,width:r.width,height:r.height};})}));assert.ok(dimensions.width<=dimensions.viewport,'PAN546_NATIVE_PAGE_HORIZONTAL_OVERFLOW');assert.ok(dimensions.controls.every(c=>c.width>0&&c.height>0&&c.left>=0&&c.right<=dimensions.viewport),'PAN546_NATIVE_CONTROL_CLIPPING');const receipt={name,imageSHA256:digest(readFileSync(image)),dimensions,currentPersistedRevision:f.readPersisted().revision,actualBuildSHA256:digest(readFileSync('dist/browser-workspace/app.js')),actualSourceSHA256:digest(readFileSync('packages/browser-workspace/src/module-view-editor-v1.ts')),state:await f.page.locator(root).getAttribute('data-state')};writeFileSync(image+'.json',JSON.stringify(receipt,null,2)+'\n');return receipt;}
async function resize(f,value='large'){await f.page.locator(root).getByRole('button',{name:'View bearbeiten',exact:true}).click();await f.page.locator('#pan546-instance-size').selectOption(value);await f.page.locator(root).getByRole('button',{name:'Vorher/Nachher prüfen',exact:true}).click();await ready(f,'PREVIEW_ONLY');await f.flushResponses();return f.responses.filter(r=>r.path.endsWith('/module-view/preview')&&r.status===200).at(-1).value;}
async function confirm(f){await f.page.locator(root).getByRole('button',{name:'Genau diese persönliche View bestätigen und speichern',exact:true}).click();await ready(f,'SAVED_AND_NATIVE_READBACK_CONFIRMED');await f.flushResponses();}
function confirmCount(f){return f.requests.filter(r=>r.path.endsWith('/module-view/confirm')).length;}

test('DUI-01/03/04 actual mounted native browser: source/currency/Human units, explicit resize preview/cancel, once confirmed personal CAS/independent GET, relogin restore and new-CAS Undo; desktop390/zoom remain readable',async()=>{
 const f=await nativeViewBrowserFixture546();try{
  const business=f.business(),observations=[];await open(f);assert.equal(f.readPersisted().revision,0);await f.flushResponses();
  const native=f.reader.read({tenantId:'tenant-a',objectId:'AP-PAN516-MATCHED-01',expectedRevision:null}),data=f.responses.filter(r=>r.path.endsWith('/module-view/data')&&r.status===200).flatMap(r=>r.value.cells);
  assert.equal(data.find(c=>c.fieldId==='erv.invoice.amountMinor').value,native.invoiceAmountMinor);assert.equal(data.find(c=>c.fieldId==='erv.invoice.currency').value,native.currency);assert.ok(data.some(c=>c.source==='HUMAN_NATIVE'&&c.unit==='REVIEW_STATE'));assert.match(await f.page.locator(root).innerText(),/ERV_NATIVE/);assert.match(await f.page.locator(root).innerText(),/HUMAN_NATIVE/);assert.match(await f.page.locator(root).innerText(),/höchstens acht Felder je Read, eine Zeile, Relationstiefe 0/);assert.match(await f.page.locator(root).innerText(),/Lieferant, Zuständigkeit und Belegnummer: UNAVAILABLE/);observations.push(await capture(f,'desktop-native546-current-cards'));
  const p=await resize(f);assert.equal(p.previewOnly,true);assert.equal(p.persistenceProduced,false);assert.equal(f.readPersisted().revision,0);assert.equal(f.business(),business);assert.equal(await f.page.locator('#pan546-field-binding').isDisabled(),true);assert.equal(await f.page.locator(root).getByRole('button',{name:'Ausgewählte Feldbindung anwenden',exact:true}).isDisabled(),true,'MANDATORY_NATIVE_BINDING_APPLY_MUST_STAY_DISABLED');observations.push(await capture(f,'desktop-native546-explicit-before-after-confirmation'));
  await f.page.locator(root).getByRole('button',{name:'Vorschau abbrechen — nichts speichern',exact:true}).click();await ready(f,'LOCAL_DRAFT_DISCARDED');assert.equal(f.readPersisted().revision,0);assert.equal(confirmCount(f),0);
  const candidate=await resize(f);await confirm(f);assert.equal(confirmCount(f),1);const saved=f.readPersisted();assert.equal(saved.revision,1);assert.equal(saved.confirmedCandidateDigest,candidate.candidateDigest);assert.equal(saved.viewDigest,candidate.afterDigest);assert.equal(saved.view.instances.find(i=>i.instanceId==='invoice-value').size,'large');assert.ok(f.requests.some(r=>r.method==='GET'&&r.path.endsWith('/module-view')));assert.equal(f.business(),business);observations.push(await capture(f,'desktop-native546-confirmed-independent-native-readback'));
  await f.page.setViewportSize({width:390,height:844});observations.push(await capture(f,'390-native546-confirmed-cards-controls'));await f.page.evaluate(()=>{document.body.style.zoom='2';});observations.push(await capture(f,'390-native546-zoom200-confirmed-cards-controls'));await f.page.evaluate(()=>{document.body.style.zoom='1';});await f.page.setViewportSize({width:1280,height:900});
  await f.page.getByRole('button',{name:'Abmelden',exact:true}).click();await f.page.getByRole('heading',{name:'Abgemeldet',exact:true}).waitFor();await f.relogin();await open(f);assert.equal(f.readPersisted().revision,1);assert.equal(await f.page.locator(root+' [data-instance="invoice-value"]').getAttribute('data-size'),'large');
  await f.page.locator(root).getByRole('button',{name:'Letzten gespeicherten Viewstand zurückholen',exact:true}).click();await ready(f,'PREVIEW_ONLY');assert.equal(f.readPersisted().revision,1);await confirm(f);assert.equal(f.readPersisted().revision,2);assert.equal(f.readPersisted().view.instances.find(i=>i.instanceId==='invoice-value').size,'regular');assert.equal(confirmCount(f),2);assert.equal(f.business(),business);assert.deepEqual(f.errors,[]);
  writeFileSync(join(process.env.PAN546_BROWSER_EVIDENCE,'actual-native546-positive-journey.json'),JSON.stringify({observations,actualRequests:f.requests,actualResponses:f.responses,noBusinessEffects:true,actualPersonalRevisions:[0,1,2],notNativeHumanDecisionOrWhole546548OrModelAcceptance:true},null,2)+'\n');
 }finally{await f.close();}
});

test('DUI-03 actual native browser lost confirm reply after persisted CAS shows unknown not success; explicit independent target readback confirms exactly once without replay',async()=>{
 const f=await nativeViewBrowserFixture546();let cdp;try{
  const business=f.business();await open(f);const p=await resize(f);cdp=await f.context.newCDPSession(f.page);let captured,held=false;const actual=new Promise(resolve=>{captured=resolve;});
  await cdp.send('Fetch.enable',{patterns:[{urlPattern:f.tls.origin+'*/workspace/module-view/confirm',requestStage:'Response'}]});cdp.on('Fetch.requestPaused',async event=>{if(!held){held=true;assert.equal(event.responseStatusCode,200);const b=await cdp.send('Fetch.getResponseBody',{requestId:event.requestId}),v=JSON.parse(Buffer.from(b.body,b.base64Encoded?'base64':'utf8').toString());assert.equal(v.outcome,'VIEW_PERSISTED');captured(v);await cdp.send('Fetch.failRequest',{requestId:event.requestId,errorReason:'Failed'});}else await cdp.send('Fetch.continueResponse',{requestId:event.requestId});});
  await f.page.locator(root).getByRole('button',{name:'Genau diese persönliche View bestätigen und speichern',exact:true}).click();const receipt=await actual;await ready(f,'WRITE_OUTCOME_UNCONFIRMED');assert.equal(await f.page.locator(root).getByRole('button',{name:'Genau diese persönliche View bestätigen und speichern',exact:true}).isDisabled(),true,'UNKNOWN_WRITE_MUST_NOT_OFFER_BLIND_CONFIRM_REPLAY');assert.equal(receipt.confirmedCandidateDigest,p.candidateDigest);assert.equal(f.readPersisted().revision,1);assert.equal(confirmCount(f),1);await capture(f,'desktop-native546-actual-lost-confirm-reply-unknown');
  await f.page.locator(root).getByRole('button',{name:'Genau diese persönliche View bestätigen und speichern',exact:true}).evaluate(e=>e.dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal(await f.page.locator(root).getAttribute('data-state'),'WRITE_OUTCOME_UNCONFIRMED','ATTEMPTED_CANDIDATE_HANDLER_MUST_REJECT_PROGRAMMATIC_REPLAY');assert.equal(confirmCount(f),1);
  await cdp.send('Fetch.disable');await f.page.setViewportSize({width:390,height:844});await capture(f,'390-native546-actual-lost-confirm-reply-unknown');await f.page.locator(root).getByRole('button',{name:'Unklaren Schreibausgang unabhängig zurücklesen',exact:true}).click();await ready(f,'SAVED_AND_NATIVE_READBACK_CONFIRMED');assert.equal(confirmCount(f),1);assert.equal(f.readPersisted().revision,1);assert.equal(f.business(),business);assert.deepEqual(f.errors,[]);await capture(f,'390-native546-unknown-reconciled-by-only-independent-native-read');
 }finally{await cdp?.send('Fetch.disable').catch(()=>{});await f.close();}
});
