import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
const path=new URL('../../dist/packages/contracts/src/workspace-module-view-v1.js',import.meta.url);
const v=existsSync(path)?await import(path):{};
const fields=[{fieldId:'erv.invoice.amountMinor',source:'ERV_NATIVE',type:'NUMBER',unit:'CURRENCY_MINOR'}, {fieldId:'erv.invoice.currency',source:'ERV_NATIVE',type:'STRING',unit:'ISO4217'}, {fieldId:'erv.invoice.liabilityStatus',source:'ERV_NATIVE',type:'STRING',unit:'LIABILITY_STATE'}, {fieldId:'erv.human.reviewState',source:'HUMAN_NATIVE',type:'STRING',unit:'REVIEW_STATE'}];
function implementation(){assert.equal(typeof v.validateWorkspaceModuleViewV1,'function','PAN546_CLOSED_SEPARATE_MODULE_VIEW_NOT_IMPLEMENTED');assert.equal(typeof v.reduceWorkspaceModuleViewV1,'function','PAN546_SHARED_CANONICAL_VIEW_REDUCER_NOT_IMPLEMENTED');assert.equal(typeof v.defaultWorkspaceModuleViewV1,'function');}
function command(operations){return {schemaVersion:'pansphaira.workspace-module-view/delta/v1',operations};}
test('DUI-03 shared manual/agent MOVE RESIZE SHOW BIND use one closed canonical reducer and byte-identical resulting view',()=>{
 implementation();const initial=v.defaultWorkspaceModuleViewV1();const operations=[{kind:'MOVE',instanceId:'native-review',position:0},{kind:'RESIZE',instanceId:'native-review',size:'large'},{kind:'SHOW',instanceId:'invoice-table',visible:false},{kind:'BIND',instanceId:'invoice-value',binding:{fieldIds:['erv.invoice.amountMinor'],unit:'CURRENCY_MINOR'}}];const manual=v.reduceWorkspaceModuleViewV1(initial,command(operations),fields);const agent=v.reduceWorkspaceModuleViewV1(JSON.parse(JSON.stringify(initial)),JSON.parse(JSON.stringify(command(operations))),fields);assert.equal(JSON.stringify(manual),JSON.stringify(agent));assert.equal(manual.instances[0].instanceId,'native-review');assert.equal(manual.instances[0].size,'large');assert.equal(manual.instances.find(x=>x.instanceId==='invoice-table').visible,false);assert.equal(initial.instances[0].instanceId,'invoice-value');assert.ok(Object.isFrozen(manual)&&Object.isFrozen(manual.instances));
});
test('DUI-03 module view is data-free and closed: duplicate IDs, code HTML URL identity data and unknown field/unit are rejected',()=>{
 implementation();const initial=v.defaultWorkspaceModuleViewV1();for(const extra of [{tenantId:'tenant-b'},{data:{amount:100}},{expression:'return 1'},{html:'<script>'},{url:'https://outside.invalid'},{schemaVersion:'pansphaira.workspace-module-view/v999'}])assert.throws(()=>v.validateWorkspaceModuleViewV1({...initial,...extra},fields),/VIEW_/);const duplicate=JSON.parse(JSON.stringify(initial));duplicate.instances[1].instanceId=duplicate.instances[0].instanceId;assert.throws(()=>v.validateWorkspaceModuleViewV1(duplicate,fields),/VIEW_/);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([{kind:'BIND',instanceId:'invoice-value',binding:{fieldIds:['erv.invoice.supplier'],unit:'CURRENCY_MINOR'}}]),fields),/VIEW_BINDING_DENIED/);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([{kind:'BIND',instanceId:'invoice-value',binding:{fieldIds:['erv.invoice.amountMinor'],unit:'COUNT'}}]),fields),/VIEW_UNIT_DENIED/);
});
test('DUI-01 protected invariant cannot be hidden, rebound or removed through view delta; legacy profile bytes are separate',()=>{
 implementation();const initial=v.defaultWorkspaceModuleViewV1();const legacy={schemaVersion:'pansphaira.browser-profile/v1',items:[{id:'pan.workspace.boundary',version:'1.0.0',visible:false,size:'compact'}]};const bytes=JSON.stringify(legacy);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([{kind:'SHOW',instanceId:'invoice-value',visible:false}]),fields),/VIEW_MANDATORY_DENIED/);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([{kind:'BIND',instanceId:'native-review',binding:{fieldIds:['erv.invoice.liabilityStatus'],unit:'LIABILITY_STATE'}}]),fields),/VIEW_BINDING_DENIED/);assert.equal(JSON.stringify(legacy),bytes);assert.throws(()=>v.validateWorkspaceModuleViewV1({...initial,instances:initial.instances.filter(x=>x.instanceId!=='native-review')},fields),/VIEW_MANDATORY_DENIED/);
});
test('DUI-03 arrays/accessors and operation bounds reject before caller code can execute or produce partial reduced effects',()=>{
 implementation();const initial=v.defaultWorkspaceModuleViewV1();let getter=0;const bad={kind:'MOVE',instanceId:'native-review',get position(){getter++;return 0;}};assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([bad]),fields),/VIEW_/);assert.equal(getter,0);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command(Array.from({length:17},()=>({kind:'MOVE',instanceId:'native-review',position:0}))),fields),/VIEW_/);assert.throws(()=>v.reduceWorkspaceModuleViewV1(initial,command([{kind:'MOVE',instanceId:'native-review',position:99}]),fields),/VIEW_/);assert.equal(initial.instances[0].instanceId,'invoice-value');
});
