import test from 'node:test';
import assert from 'node:assert/strict';
import {readPan516Procurement} from '../../src/procurement-434/bestellung-lifecycle.mjs';
import {evaluatePan516ProcurementLiabilitySnapshot} from '../../src/procurement-434/bestellung-liability.mjs';
import {createNativeWorkspaceErvHumanV1} from '../../src/pan546/native-human-workspace.mjs';
import {nativeViewFixture546} from './native-fixture.mjs';
import {nativeViewBrowserFixture546} from './browser-fixture.mjs';
import {nativeRows} from '../fixtures/pan515/native-trade-fixture.mjs';
import {validateWorkspaceErvHumanReadV1} from '../../dist/packages/contracts/src/workspace-erv-human-v1.js';
const invoiceId='AP-PAN516-MATCHED-01';
function expected(root,id=invoiceId){const state=readPan516Procurement({root}),liability=evaluatePan516ProcurementLiabilitySnapshot({state,invoiceId:id,expectedConfirmationRevision:state.confirmations.at(-1).revision});return{schemaVersion:'pansphaira.workspace-erv-references/v1',invoiceId:id,orderId:state.effectiveDraft.bestellungId,positionId:state.effectiveDraft.positionen[0].positionId,receiptIds:state.receiptLedger.eintraege.map(e=>e.eingangsId),quantityUnit:state.confirmations.at(-1).terms.unit,invoiceSourcePath:liability.source.invoiceSource.path,invoiceSourceSha256:liability.source.invoiceSource.sha256};}
const events=f=>nativeRows(f.native.root,'SELECT ordinal,effect_key,command,event FROM pan542_events ORDER BY ordinal');
test('PUI-05-AC02 exact current shared reference DTO accepts the real projection and rejects extra authority, foreign invoice, wrong unit, sparse/accessor receipts without executing a getter',async()=>{const f=await nativeViewFixture546();let owner;try{owner=createNativeWorkspaceErvHumanV1({sessions:f.sessions,contextSelection:f.context,humanRoot:f.native.root});const t=f.tab(),v=owner.call(t.headers,'read',{context:f.verification(t)}).value,validate=x=>validateWorkspaceErvHumanReadV1(x,v.invoiceId,v.nativeRevision);assert.deepEqual(validate(v).references,expected(f.native.root));for(const references of [{...v.references,invoiceId:'AP-PAN516-PARTIAL-01'},{...v.references,quantityUnit:'INFERRED'},{...v.references,executionAuthorityGranted:true},{...v.references,receiptIds:Array(1)}])assert.throws(()=>validate({...v,references}),/HUMAN_REFERENCES_DENIED/);assert.throws(()=>validate({...v,bookingAuthorityGranted:true}),/HUMAN_READ_DENIED/);let called=0;const receiptIds=[];Object.defineProperty(receiptIds,'0',{enumerable:true,get(){called++;return'wareneingang:forged';}});assert.throws(()=>validate({...v,references:{...v.references,receiptIds}}),/HUMAN_REFERENCES_DENIED/);assert.equal(called,0);assert.equal(events(f).length,0);}finally{owner?.close();await f.close();}});
test('PUI-05-AC02 exact native invoice/order/position/receipt references and real quantity unit are closed source projections, never guessed IDs or a new grant',async()=>{const f=await nativeViewFixture546();let owner;try{owner=createNativeWorkspaceErvHumanV1({sessions:f.sessions,contextSelection:f.context,humanRoot:f.native.root});for(const id of [invoiceId,'AP-PAN516-PARTIAL-01']){const t=f.tab(f.issue(),id),context=f.verification(t),before=events(f),read=owner.call(t.headers,'read',{context}).value;assert.deepEqual(read.references,expected(f.native.root,id),'AC02_NATIVE_RELATION_REFERENCES_MUST_BE_PROJECTED_FROM_LEADING_SOURCE');assert.equal(read.bookingAuthorityGranted,false);assert.deepEqual(events(f),before);assert.throws(()=>owner.call({...t.headers,'x-tenant':'tenant-b'},'read',{context}),/HOSTED_HEADER_AUTHORITY_DENIED/);} }finally{owner?.close();await f.close();}});
test('PUI-05-AC02 actual browser displays native invoice/order/position/receipt source/unit before deciding and direct independent readback retains the same references',async()=>{const f=await nativeViewBrowserFixture546({subjectId:'synthetic:erv-reviewer',humanDecisions:true});try{await f.page.goto(f.tls.origin+'/t/tenant-a/workspace');await f.page.locator('[id="shell.context-selection"][data-module="pan.setup"][data-state="CURRENT_CONTEXT"]').waitFor();await f.page.getByRole('button',{name:'Eingangsrechnungsprüfung — nur lesen',exact:true}).click();await f.page.locator('[id="shell.erv-human"][data-state="CURRENT_HUMAN_READ"]').waitFor();const refs=expected(f.native.root),text=await f.page.locator('[id="shell.erv-human"]').innerText();for(const value of [refs.invoiceId,refs.orderId,refs.positionId,...refs.receiptIds,refs.quantityUnit,refs.invoiceSourcePath,refs.invoiceSourceSha256])assert.ok(text.includes(value),'AC02_NATIVE_REFERENCE_UNIT_OR_SOURCE_MISSING_FROM_REAL_BROWSER: '+value);assert.equal(events(f).length,0);await f.page.getByRole('button',{name:'Fachentscheidung vorschauen',exact:true}).click();assert.match(await f.page.locator('[id="shell.erv-human"]').innerText(),/Vorher \/ Nachher: REVIEW_REQUIRED → REVIEWED_LOCAL_EVIDENCE_ONLY/);await f.page.getByRole('button',{name:'Genau diese fachliche Evidenzentscheidung bestätigen',exact:true}).click();await f.page.locator('[id="shell.erv-human"][data-state="HUMAN_DECISION_NATIVE_READBACK_CONFIRMED"]').waitFor();assert.equal(events(f).length,1);await f.flushResponses();const receipts=f.responses.filter(r=>r.path.endsWith('/erv-human/read')&&r.status===200);assert.deepEqual(receipts.at(-1).value.value.references,refs);assert.ok(f.requests.some(r=>r.path.endsWith('/erv-human/decide')));assert.deepEqual(f.errors,[]);}finally{await f.close();}});
