import test from 'node:test';
import assert from 'node:assert/strict';
import {fork} from 'node:child_process';
import {createHash,createHmac,randomBytes} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {once} from 'node:events';
import {nativeViewFixture546} from './native-fixture.mjs';
import {nativeRows} from '../fixtures/pan515/native-trade-fixture.mjs';
import {request527} from '../pan527/helpers.mjs';
import {canonicalJson} from '../../src/pan473/scope-profile.mjs';
import {createNativeWorkspaceErvHumanV1} from '../../src/pan546/native-human-workspace.mjs';
import {mountProtectedWorkspaceErvHumanV1} from '../../src/pan527/origin-session-adapter.mjs';
const hash=v=>createHash('sha256').update(v).digest('hex');
function command(p,id='human-native-001',action='REVIEW'){return{schemaVersion:'pansphaira.erv-human/decision/v1',invoiceId:p.invoiceId,effectId:'synthetic:'+id,transportId:'synthetic:wire-'+id,expectedNativeRevision:p.nativeRevision,expectedProposalRevision:p.proposalRevision,proposalDigest:p.proposalDigest,action};}
function owner(f){return createNativeWorkspaceErvHumanV1({sessions:f.sessions,contextSelection:f.context,humanRoot:f.native.root});}
function opts(f,api,script=readFileSync('dist/browser-workspace/erv-human.js','utf8')){return{optIn:true,tenantId:'tenant-a',origin:f.tls.origin,identityDigest:f.sessions.binding.identityDigest,owner:api,script};}
const events=f=>nativeRows(f.native.root,'SELECT ordinal,effect_key,command,event FROM pan542_events ORDER BY ordinal');
test('PUI-05 new Human CSRF projection recovers only the actual issued own reviewer proof; readers, foreign origin, spoofed headers and missing session confer no authority',async()=>{const f=await nativeViewFixture546();try{const h=f.issue(),r=f.issue('synthetic:erv-reader','reader');assert.equal(f.sessions.workspaceMutationCsrf(h),h['x-pan527-csrf']);assert.equal(f.sessions.workspaceMutationCsrf({...h,origin:'https://foreign.test'}),null);assert.equal(f.sessions.workspaceMutationCsrf(r),null);assert.throws(()=>f.sessions.workspaceMutationCsrf({...h,'x-role':'APPROVER'}),/HOSTED_HEADER_AUTHORITY_DENIED/);assert.throws(()=>f.sessions.workspaceMutationCsrf({}),/HOSTED_SESSION_DENIED/);assert.throws(()=>f.sessions.authorizeMutation({...h,'x-pan527-csrf':'0'.repeat(64)}),/HOSTED_CSRF_DENIED/);assert.equal(events(f).length,0);}finally{await f.close();}});
test('PUI-05 existing signed historical random CSRF remains authorized and is not rotated or recovered/adopted by the browser bridge',async()=>{const f=await nativeViewFixture546();try{const h=f.issue(),root=f.tls.tenants[0].stateRoot,path=join(root,'sessions.json'),e=JSON.parse(readFileSync(path)),token=h.cookie.split('=')[1],legacy=randomBytes(32).toString('hex');e.payload.sessions[hash(token)].csrfDigest=hash(legacy);e.mac=createHmac('sha256',Buffer.from(readFileSync(join(root,'session-auth.key'),'utf8').trim(),'hex')).update(canonicalJson(e.payload)).digest('hex');writeFileSync(path,canonicalJson(e)+'\n');const original=readFileSync(path);assert.equal(f.sessions.workspaceMutationCsrf(h),null);assert.equal(f.sessions.authorizeMutation({...h,'x-pan527-csrf':legacy}).subjectId,'synthetic:erv-reviewer');assert.deepEqual(readFileSync(path),original);assert.throws(()=>f.sessions.authorizeMutation(h),/HOSTED_CSRF_DENIED/);}finally{await f.close();}});
test('PUI-05 Human closed native context wrapper and genuine TLS requests preserve original CSRF, role, proposal, duplicate, independent readback and unchanged ERV history',async()=>{const f=await nativeViewFixture546();let mounted,api;try{api=owner(f);mounted=mountProtectedWorkspaceErvHumanV1(f.tls.gateway,opts(f,api));const t=f.tab(),context=f.verification(t),path='/t/tenant-a/workspace/erv-human/',beforeERV=nativeRows(f.native.root,'SELECT revision,effect_key,command,event FROM pan516_events ORDER BY revision');const r=await request527(f.tls,path+'read',t.headers,'POST',{context});assert.equal(r.status,200);const before=JSON.parse(r.body);assert.equal(before.csrfProof,t.headers['x-pan527-csrf']);const c=command(before.value);let denied=await request527(f.tls,path+'decide',{...t.headers,'x-pan527-csrf':'0'.repeat(64)},'POST',{context,command:c});assert.equal(denied.status,403);assert.equal(events(f).length,0);denied=await request527(f.tls,path+'decide',{...t.headers,'x-role':'APPROVER'},'POST',{context,command:c});assert.equal(denied.status,403);assert.equal(events(f).length,0);denied=await request527(f.tls,path+'decide',t.headers,'POST',{context,command:{...c,expectedProposalRevision:99}});assert.equal(denied.status,409);assert.equal(events(f).length,0);const saved=await request527(f.tls,path+'decide',t.headers,'POST',{context,command:c});assert.equal(saved.status,200);const after=await request527(f.tls,path+'read',t.headers,'POST',{context});assert.equal(after.status,200);assert.deepEqual(JSON.parse(after.body).value,JSON.parse(saved.body).value);assert.equal(JSON.parse(after.body).value.state,'REVIEWED_LOCAL_EVIDENCE_ONLY');assert.equal(events(f).length,1);assert.equal((await request527(f.tls,path+'decide',t.headers,'POST',{context,command:c})).status,409);const rec=JSON.parse((await request527(f.tls,path+'reconcile',t.headers,'POST',{context,effectId:c.effectId})).body);assert.equal(rec.value.outcome,'RECONCILED_LOCAL_DECISION_NO_NEW_EFFECT');assert.equal(rec.value.newDecisionEffect,false);assert.equal(events(f).length,1);assert.deepEqual(nativeRows(f.native.root,'SELECT revision,effect_key,command,event FROM pan516_events ORDER BY revision'),beforeERV);const reader=f.tab(f.issue('synthetic:erv-reader','reader'));assert.throws(()=>api.call(reader.headers,'decide',{context:f.verification(reader),command:command(api.call(reader.headers,'read',{context:f.verification(reader)}).value,'reader-denied')}),/HOSTED_ROLE_DENIED/);assert.equal(events(f).length,1);}finally{mounted?.close();api?.close();await f.close();}});
test('PUI-05 Human asset remains owner-opt-in, closed to unknown paths and anonymous readers, and both original per-script bounds reject oversize without a global limit waiver',async()=>{const f=await nativeViewFixture546();let api,mounted;try{const path='/t/tenant-a/workspace/erv-human/app.js';assert.equal((await request527(f.tls,path,f.issue())).status,404);api=owner(f);assert.throws(()=>mountProtectedWorkspaceErvHumanV1(f.tls.gateway,opts(f,api,'x'.repeat(131073))),/HUMAN_WORKSPACE_OWNER_DENIED/);assert.throws(()=>mountProtectedWorkspaceErvHumanV1(f.tls.gateway,{...opts(f,api),owner:{...api}}),/HUMAN_WORKSPACE_OWNER_DENIED/);mounted=mountProtectedWorkspaceErvHumanV1(f.tls.gateway,opts(f,api));assert.equal((await request527(f.tls,path)).status,401);const r=await request527(f.tls,path,f.issue());assert.equal(r.status,200);assert.equal(hash(r.body),hash(readFileSync('dist/browser-workspace/erv-human.js')));assert.equal((await request527(f.tls,path+'.unknown',f.issue())).status,404);assert.equal((await request527(f.tls,path,f.issue(),'POST',{})).status,404);assert.equal(events(f).length,0);}finally{mounted?.close();api?.close();await f.close();}});
test('PUI-05 actual native Human SQLite reservation must not commit after the current session/context lease expires while awaiting the original writer',async()=>{const f=await nativeViewFixture546();let api,child;try{api=owner(f);const issued=f.sessions.issueOwnerSession({subjectId:'synthetic:erv-reviewer',role:'reviewer',expiresAtMs:Date.now()+1200}),headers={cookie:issued.cookieHeader,origin:f.tls.origin,'x-pan527-csrf':issued.csrf,'x-pan548-session':'session:'+hash(issued.cookieHeader)},t=f.tab(headers),context=f.verification(t),before=api.call(t.headers,'read',{context}).value;
 child=fork(new URL('./native-human-reservation-probe.mjs',import.meta.url),[],{execArgv:[],silent:true});const exit=once(child,'exit'),ready=once(child,'message');child.send({root:f.native.root,holdMs:2000});const[message]=await ready;assert.equal(message.outcome,'ACTUAL_NATIVE_WRITE_RESERVATION_HELD');let error;try{api.call(t.headers,'decide',{context,command:command(before,'native-wait-expiry')});}catch(e){error=e.message;}assert.match(error??'',/HOSTED_SESSION_DENIED|WORKSPACE_CONTEXT_LEASE_DENIED/);const[code,signal]=await exit;assert.equal(code,0);assert.equal(signal,null);assert.equal(events(f).length,0,'HUMAN_NATIVE_WRITE_MUST_REAUTHORIZE_AFTER_GENUINE_SQLITE_WAIT');
 }finally{if(child?.exitCode===null)child.kill('SIGKILL');api?.close();await f.close();}});
