import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {nativeViewFixture546} from './native-fixture.mjs';
import {request527} from '../pan527/helpers.mjs';
import {ervPluginV1} from '../../dist/packages/browser-workspace/src/plugin-erv-v1.js';
const candidate=new URL('../../src/pan546/native-invoice-navigation.mjs',import.meta.url);
const nav=existsSync(candidate)?await import(candidate):{};
async function fixture(){assert.equal(typeof nav.createNativeWorkspaceInvoiceNavigationV1,'function','DUI05_NATIVE_SEARCH_NAVIGATION_OWNER_NOT_IMPLEMENTED');const f=await nativeViewFixture546();try{const owner=nav.createNativeWorkspaceInvoiceNavigationV1({sessions:f.sessions,contextSelection:f.context,nativeReader:f.reader});const t=f.tab();const search=(query='PARTIAL',tab=t)=>owner.search(tab.headers,{schemaVersion:'pansphaira.workspace-invoice-search/v1',context:f.verification(tab),query});const request=(targetHandle,tab=t)=>owner.request(tab.headers,{schemaVersion:'pansphaira.workspace-navigation/request/v1',context:f.verification(tab),targetHandle});const read=(requestHandle,tab=t)=>owner.read(tab.headers,{schemaVersion:'pansphaira.workspace-navigation/read/v1',context:f.verification(tab),requestHandle});return {f,owner,t,search,request,read,async close(){owner.close();await f.close();}};}catch(e){await f.close();throw e;}}
function renderedContext(n,request){const {f,t}=n;f.fresh(t);const c=t.context;const snap=f.context.claim(t.headers,{schemaVersion:'pansphaira.workspace-context/claim/v1',tabId:c.binding.tabId,moduleId:'pan.erv',viewId:'pan.erv.view',primaryObjectId:request.target.objectId,selection:null,expected:{...c.revisions,domainRevision:request.target.dataRevision,epoch:c.binding.epoch}});t.context=snap.context;return t.context;}
function renderAck(n,r,request,c){return {schemaVersion:'pansphaira.workspace-navigation/render-ack/v1',context:n.f.verification(n.t),requestHandle:request.requestHandle,readReceiptHandle:r.readReceiptHandle,rendered:{moduleId:'pan.erv',viewId:'pan.erv.view',objectId:r.invoice.invoiceId,dataRevision:r.invoice.revision,tabId:c.binding.tabId,epoch:c.binding.epoch}};}
test('DUI05 native bounded search reads only current native authorized invoice candidates NONE ONE AMBIGUOUS with opaque target and no source metadata/right grant',async()=>{const n=await fixture();try{const one=n.search();assert.equal(one.outcome,'ONE');assert.equal(one.candidates.length,1);assert.equal(one.candidates[0].objectId,'AP-PAN516-PARTIAL-01');assert.match(one.candidates[0].targetHandle,/^nav-target:[a-f0-9]{64}$/);assert.equal(one.candidates[0].dataRevision,n.f.reader.read({tenantId:'tenant-a',objectId:one.candidates[0].objectId,expectedRevision:null}).revision);assert.equal(n.search('NOT-EXISTS').outcome,'NONE');const many=n.search('AP-PAN516');assert.equal(many.outcome,'AMBIGUOUS');assert.deepEqual(many.candidates.map(x=>x.objectId),['AP-PAN516-MATCHED-01','AP-PAN516-PARTIAL-01']);assert.deepEqual(Object.keys(one.candidates[0]).sort(),['dataRevision','label','objectId','targetHandle']);assert.equal(one.executionAuthorityGranted,false);assert.equal(one.effectsProduced,false);assert.equal(one.budget.maxNativeReads,2);}finally{await n.close();}});
test('DUI05 closed search rejects scope/URL/free query/getters/credential-like input before reads or metadata observation',async()=>{const n=await fixture();try{const base={schemaVersion:'pansphaira.workspace-invoice-search/v1',context:n.f.verification(n.t),query:'PARTIAL'};for(const extra of [{tenantId:'tenant-b'},{url:'https://outside.invalid'},{fieldIds:['supplier.email']},{expression:'SELECT *'},{query:''},{query:'A'.repeat(65)},{query:'https://outside.invalid'},{query:'sk'+'-denied-model-input'},{schemaVersion:'unknown'}])assert.throws(()=>n.owner.search(n.t.headers,{...base,...extra}),/NAV_|CONTEXT_/);let invoked=0;assert.throws(()=>n.owner.search(n.t.headers,{...base,get query(){invoked++;return 'PARTIAL';}}),/NAV_/);assert.equal(invoked,0);assert.throws(()=>n.f.reader.search({tenantId:'tenant-b',query:'PARTIAL'}),/ERV_/);assert.equal(n.search().outcome,'ONE');}finally{await n.close();}});
test('DUI05 navigation request proves only NAVIGATION_REQUESTED not browser render/read/context mutation; independently actual native read gets receipt',async()=>{const n=await fixture();try{const before=JSON.stringify(n.t.context),profile=n.f.store.read(n.f.sessions.authenticate(n.t.headers));const request=n.request(n.search().candidates[0].targetHandle);assert.equal(request.outcome,'NAVIGATION_REQUESTED');assert.equal(request.browserRenderConfirmed,false);assert.equal(request.effectsProduced,false);assert.equal(JSON.stringify(n.f.context.snapshot(n.t.headers).context),before);assert.deepEqual(n.f.store.read(n.f.sessions.authenticate(n.t.headers)),profile);assert.equal(request.target.routeId,'pan.erv.route');assert.equal(request.target.path,'/workspace/erv');const r=n.read(request.requestHandle);assert.equal(r.outcome,'NATIVE_TARGET_READBACK_RECEIVED');assert.match(r.readReceiptHandle,/^nav-read:[a-f0-9]{64}$/);assert.deepEqual(r.invoice,n.f.reader.read({tenantId:'tenant-a',objectId:'AP-PAN516-PARTIAL-01',expectedRevision:request.target.dataRevision}));assert.equal(r.browserRenderConfirmed,false);}finally{await n.close();}});
test('DUI05 native target/request/read receipt bind to actual session subject/tab/context and reject copied tab/header fake handles/external URL',async()=>{const n=await fixture();try{const candidate=n.search().candidates[0],other=n.f.tab(n.t.headers),foreign=n.f.tab(n.f.issue('synthetic:other-reviewer'));assert.throws(()=>n.request(candidate.targetHandle,other),/NAV_|CONTEXT_/);assert.throws(()=>n.request(candidate.targetHandle,foreign),/NAV_|CONTEXT_/);const request=n.request(candidate.targetHandle);assert.throws(()=>n.read(request.requestHandle,other),/NAV_|CONTEXT_/);assert.throws(()=>n.request('https://outside.invalid'),/NAV_/);assert.throws(()=>n.read('nav-request:'+ 'f'.repeat(64)),/NAV_/);const body={schemaVersion:'pansphaira.workspace-navigation/request/v1',context:n.f.verification(n.t),targetHandle:candidate.targetHandle};assert.throws(()=>n.owner.request({...n.t.headers,'x-pan548-tab-id':other.context.binding.tabId},body),/NAV_|CONTEXT_/);}finally{await n.close();}});
test('DUI05 pending navigation fails after real context/view revision changes or native plugin retirement; no stale request/read/render receipt',async()=>{const n=await fixture();const original=ervPluginV1.enabled;try{const c=n.search().candidates[0],request=n.request(c.targetHandle),p=n.f.preview(n.t,[{kind:'MOVE',instanceId:'native-review',position:0}]);n.f.view.confirm(n.t.headers,n.f.confirmation(n.t,p));assert.throws(()=>n.request(c.targetHandle),/NAV_|CONTEXT_/);assert.throws(()=>n.read(request.requestHandle),/NAV_|CONTEXT_/);n.f.fresh(n.t);const candidate=n.search().candidates[0];ervPluginV1.enabled=false;assert.throws(()=>n.request(candidate.targetHandle),/NAV_|CONTEXT_/);assert.throws(()=>n.search(),/NAV_|CONTEXT_/);ervPluginV1.enabled=original;}finally{ervPluginV1.enabled=original;await n.close();}});
test('DUI05 renderer ack cannot substitute for actual native read; exact closed object/view/tab/epoch/nativeRevision and current target context required',async()=>{const n=await fixture();try{const request=n.request(n.search().candidates[0].targetHandle);let c=renderedContext(n,request);const empty={schemaVersion:'pansphaira.workspace-navigation/render-ack/v1',context:n.f.verification(n.t),requestHandle:request.requestHandle,readReceiptHandle:'nav-read:'+ 'a'.repeat(64),rendered:{moduleId:'pan.erv',viewId:'pan.erv.view',objectId:request.target.objectId,dataRevision:request.target.dataRevision,tabId:c.binding.tabId,epoch:c.binding.epoch}};assert.throws(()=>n.owner.acknowledge(n.t.headers,empty),/NAV_/);}finally{await n.close();}});
test('DUI05 exact actual native read then target context and matching renderer ack are CLIENT_REPORTED not server-certified render or authority, no persistence effects',async()=>{const n=await fixture();try{const request=n.request(n.search().candidates[0].targetHandle),r=n.read(request.requestHandle);const c=renderedContext(n,request),body=renderAck(n,r,request,c);for(const rendered of [{...body.rendered,objectId:'AP-PAN516-MATCHED-01'},{...body.rendered,viewId:'pan.setup.view'},{...body.rendered,dataRevision:body.rendered.dataRevision+1},{...body.rendered,epoch:body.rendered.epoch+1},{...body.rendered,tabId:'tab:'+ 'f'.repeat(32)},{...body.rendered,renderConfirmed:true}])assert.throws(()=>n.owner.acknowledge(n.t.headers,{...body,rendered}),/NAV_/);const ack=n.owner.acknowledge(n.t.headers,body);assert.equal(ack.outcome,'BROWSER_RENDER_ACK_REPORTED');assert.equal(ack.serverCertifiedBrowserRender,false);assert.equal(ack.nativeReadVerified,true);assert.equal(ack.effectsProduced,false);assert.equal(ack.executionAuthorityGranted,false);assert.throws(()=>n.owner.acknowledge(n.t.headers,body),/NAV_/);}finally{await n.close();}});
test('DUI05 native owned construction/lifetime reject fake callback reader/context owner and revoked session without leaking stored targets',async()=>{const n=await fixture();try{assert.throws(()=>nav.createNativeWorkspaceInvoiceNavigationV1({sessions:n.f.sessions,contextSelection:n.f.context,nativeReader:{read:n.f.reader.read}}),/NAV_/);assert.throws(()=>nav.createNativeWorkspaceInvoiceNavigationV1({sessions:n.f.sessions,contextSelection:{verify:n.f.context.verify},nativeReader:n.f.reader}),/NAV_/);const request=n.request(n.search().candidates[0].targetHandle);const logout=await request527(n.f.tls,'/t/tenant-a/workspace/logout',n.t.headers,'POST');assert.equal(logout.status,200,logout.body);assert.throws(()=>n.read(request.requestHandle),/NAV_|HOSTED_|CONTEXT_/);n.owner.close();assert.throws(()=>n.search(),/NAV_/);}finally{await n.close();}});
