import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeViewFixture546} from './native-fixture.mjs';
import {financeFixture} from '../pan519/native-fixture.mjs';
import {createNativeErvReadAdapterV1} from '../../src/pan541/native-erv-read-adapter.mjs';
import {createNativeWorkspaceContextSelectionV1} from '../../src/pan548/native-context-selection.mjs';
import {protectedWorkspaceSetupStatusV1} from '../../src/pan527/origin-session-adapter.mjs';
import {createNativeWorkspaceInvoiceNavigationV1} from '../../src/pan546/native-invoice-navigation.mjs';
function verification(t){return {schemaVersion:'pansphaira.workspace-context/verify/v1',tabId:t.context.binding.tabId,contextHandle:t.context.contextHandle};}
function navOwner(f,context=f.context,reader=f.reader){return createNativeWorkspaceInvoiceNavigationV1({sessions:f.sessions,contextSelection:context,nativeReader:reader});}
function tab(f,context){const headers=f.issue(),boot=context.bootstrap(headers,{}),c=boot.snapshot.context,h={...headers,'x-pan548-tab':boot.tabProof,'x-pan548-tab-id':c.binding.tabId},invoice=f.reader.read({tenantId:'tenant-a',objectId:'AP-PAN516-MATCHED-01',expectedRevision:null});return {headers:h,context:context.claim(h,{schemaVersion:'pansphaira.workspace-context/claim/v1',tabId:c.binding.tabId,moduleId:'pan.erv',viewId:'pan.erv.view',primaryObjectId:invoice.invoiceId,selection:null,expected:{...c.revisions,domainRevision:invoice.revision,epoch:c.binding.epoch}}).context};}
function plan(owner,t,query='PARTIAL'){const result=owner.search(t.headers,{schemaVersion:'pansphaira.workspace-invoice-search/v1',context:verification(t),query});return owner.request(t.headers,{schemaVersion:'pansphaira.workspace-navigation/request/v1',context:verification(t),targetHandle:result.candidates[0].targetHandle});}
function read(owner,t,p){return owner.read(t.headers,{schemaVersion:'pansphaira.workspace-navigation/read/v1',context:verification(t),requestHandle:p.requestHandle});}
function claim(context,t,p){t.context=context.snapshot(t.headers).context;const c=t.context;t.context=context.claim(t.headers,{schemaVersion:'pansphaira.workspace-context/claim/v1',tabId:c.binding.tabId,moduleId:'pan.erv',viewId:'pan.erv.view',primaryObjectId:p.target.objectId,selection:null,expected:{...c.revisions,domainRevision:p.target.dataRevision,epoch:c.binding.epoch}}).context;}
function ack(t,p,r){const c=t.context;return {schemaVersion:'pansphaira.workspace-navigation/render-ack/v1',context:verification(t),requestHandle:p.requestHandle,readReceiptHandle:r.readReceiptHandle,rendered:{moduleId:c.moduleId,viewId:c.viewId,objectId:c.primaryObject.objectId,dataRevision:c.primaryObject.revision,tabId:c.binding.tabId,epoch:c.binding.epoch}};}
function callbackContext(f,onProfile){return createNativeWorkspaceContextSelectionV1({sessions:f.sessions,identity:f.tls.tenants[0].identity,nativeReader:f.reader,readSetup:()=>protectedWorkspaceSetupStatusV1(f.tls.gateway,{tenantId:'tenant-a',origin:f.tls.origin,identityDigest:f.sessions.binding.identityDigest}),readProfile:p=>{const value=f.legacy.read(p);onProfile();return value;},moduleViewStore:f.store});}
test('517-01 real authentic alternate same-tenant leading SQLite reader with same native IDs and numeric revision is not this context owner source',async()=>{const f=await nativeViewFixture546();const other=await financeFixture();try{const alternate=createNativeErvReadAdapterV1({tenantId:'tenant-a',root:other.root});assert.equal(alternate.read({tenantId:'tenant-a',objectId:'AP-PAN516-MATCHED-01',expectedRevision:null}).revision,f.reader.read({tenantId:'tenant-a',objectId:'AP-PAN516-MATCHED-01',expectedRevision:null}).revision);assert.throws(()=>navOwner(f,f.context,alternate),/NAV_NATIVE_OWNER_DENIED/);}finally{other.close();await f.close();}});
test('517-02 genuine context native profile callback closes navigation during final verification: no successful search or repopulation',async()=>{const f=await nativeViewFixture546();let arm=false,observations=0,owner,context;try{context=callbackContext(f,()=>{if(arm&&++observations===2)owner.close();});const t=tab(f,context);owner=navOwner(f,context);arm=true;assert.throws(()=>owner.search(t.headers,{schemaVersion:'pansphaira.workspace-invoice-search/v1',context:verification(t),query:'PARTIAL'}),/NAV_OWNER_CLOSED/);assert.equal(observations,2);assert.throws(()=>owner.search(t.headers,{schemaVersion:'pansphaira.workspace-invoice-search/v1',context:verification(t),query:'PARTIAL'}),/NAV_OWNER_CLOSED/);}finally{owner?.close();context?.close();await f.close();}});
test('517-03 nested caller toJSON render field cannot re-enter and consume one actual native readreceipt twice',async()=>{const f=await nativeViewFixture546();const owner=navOwner(f);try{const t=f.tab(),p=plan(owner,t),r=read(owner,t,p);claim(f.context,t,p);const good=ack(t,p,r);let calls=0,inner=0;const bad={...good,rendered:{...good.rendered,moduleId:{toJSON(){calls++;owner.acknowledge(t.headers,good);inner++;return 'pan.erv';}}}};assert.throws(()=>owner.acknowledge(t.headers,bad),/NAV_/);assert.equal(calls,0);assert.equal(inner,0);assert.equal(owner.acknowledge(t.headers,good).outcome,'BROWSER_RENDER_ACK_REPORTED');assert.throws(()=>owner.acknowledge(t.headers,good),/NAV_/);}finally{owner.close();await f.close();}});
test('517-04 real native retirement of same target context denies old request/readreceipt instead of accepting one extra epoch',async()=>{const f=await nativeViewFixture546();const owner=navOwner(f);try{const t=f.tab(),p=plan(owner,t,'MATCHED'),r=read(owner,t,p),before=t.context;f.context.retire(t.headers,verification(t));t.context=f.context.snapshot(t.headers).context;assert.equal(t.context.binding.epoch,before.binding.epoch+1);assert.equal(t.context.revisions.selectionRevision,before.revisions.selectionRevision+1);assert.throws(()=>owner.acknowledge(t.headers,ack(t,p,r)),/NAV_RENDER_BINDING_DENIED/);}finally{owner.close();await f.close();}});
test('517-05 actual original unmodified60s request/read lease expires during final native verify while destination context lease stays current; no late ACK', {timeout:90000},async()=>{const f=await nativeViewFixture546();let owner,context,arm=false,calls=0,expiry=0;try{context=callbackContext(f,()=>{if(arm&&++calls===2){const remaining=expiry-Date.now()+15;if(remaining>0)Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,remaining);assert.ok(Date.now()>=expiry);}});const t=tab(f,context);owner=navOwner(f,context);const original=t.context;assert.equal(original.lease.expiresAtMs-original.lease.issuedAtMs,60000);const p=plan(owner,t),r=read(owner,t,p);Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,150);claim(context,t,p);assert.ok(t.context.lease.expiresAtMs>original.lease.expiresAtMs+100);expiry=original.lease.expiresAtMs;arm=true;assert.throws(()=>owner.acknowledge(t.headers,ack(t,p,r)),/NAV_RENDER_BINDING_DENIED/);assert.equal(calls,2);}finally{owner?.close();context?.close();await f.close();}});
