import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {buildVerificationImpactPlanV2} from '../../dist/packages/contracts/src/index.js';
const load=path=>JSON.parse(readFileSync(path,'utf8')),sha=path=>createHash('sha256').update(readFileSync(path)).digest('hex');
const required=["src/pan523/production-state.mjs", "scripts/run-pan523-production.mjs", "scripts/run-pan523-production-tests.mjs", "tests/fixtures/pan523/native-production-fixture.mjs", "tests/fixtures/pan523/produced-dispatch-fixture.mjs", "tests/fixtures/pan523/historical-native-pins.mjs", "tests/fixtures/pan523/retained-pan515-trade-state-54d4a597.txt", "tests/pan523/native-production-boundaries.test.mjs", "tests/pan523/native-production-cli.test.mjs", "tests/pan523/native-production-cost.test.mjs", "tests/pan523/native-production-fulfilment.test.mjs", "tests/pan523/native-production-history.test.mjs", "tests/pan523/native-production-invoice.test.mjs", "tests/pan523/native-production-negatives.test.mjs", "tests/pan523/native-production-revision.test.mjs", "tests/pan523/native-production-rollback.test.mjs", "tests/pan523/native-production.test.mjs", "tests/pan523/historical-native-pins.test.mjs", "tests/pan523/registration.test.mjs", "tests/pan523/test-runner.test.mjs", "docs/architecture/pan523-native-production-v1.md", "verification/pan523-native-production-v1.json", "verification/pan523-historical-native-source-admission-v1.json"];
test('P09 one additive native-production canonical owner binds every byte and preserves original owners, hard gates and narrow history admission',()=>{
 const graph=load('verification/verification-dag-v2.json'),nodes=graph.nodes.filter(n=>n.id==='pan523-native-production-v1');assert.equal(nodes.length,1,'Actual native P09 is still not canonically owned');assert.equal(graph.graphVersion,90);assert.equal(graph.nodes.length,96);
 const node=nodes[0];assert.deepEqual(node.dependsOn,['pan515-native-trade-state-v1','pan517-native-fulfilment-v1','pan522-material-plan-v1']);assert.deepEqual(node.ownedTests,['npm run pan523:test']);assert.equal(node.riskClass,'HIGH');assert.equal(node.globalInvalidation,false);assert.deepEqual(node.inputs.map(r=>r.path),required);
 const observedInputDigests=Object.fromEntries(graph.nodes.flatMap(n=>n.inputs.map(i=>[i.path,i.sha256]))),legacy=new Set(readFileSync('release/public-files.manifest','utf8').split('\n').filter(l=>l&&!l.startsWith('#')).map(l=>l.split('\t')[0])),builder=readFileSync('scripts/build-public-release.sh','utf8');
 for(const row of node.inputs){assert.equal(row.sha256,sha(row.path),row.path);assert.deepEqual(graph.nodes.filter(n=>n.inputs.some(i=>i.path===row.path)).map(n=>n.id),[node.id]);assert.equal(legacy.has(row.path),false);assert.ok(builder.includes(JSON.stringify(row.path)),row.path);const plan=buildVerificationImpactPlanV2({graph,graphPath:'verification/verification-dag-v2.json',baseSha:'1'.repeat(40),headSha:'2'.repeat(40),changedPaths:[row.path],observedInputDigests});assert.deepEqual(plan.selectedNodes,[node.id]);assert.deepEqual(plan.selectedTests,['npm run pan523:test']);assert.deepEqual(plan.hardGates,[...graph.hardGates].sort((a,b)=>a.localeCompare(b,'en')));}
 assert.deepEqual(graph.hardGates,['npm run lint','npm run release-governance:verify','npm run supply-chain:verify','sha256sum -c SHA256SUMS','./scripts/build-public-release.sh --output <isolated-absolute-path>']);
 const b=load('verification/pan523-native-production-v1.json');assert.equal(b.originalCriteria.length,4);assert.equal(b.originalNegatives.length,5);assert.equal(b.productiveExecutionAuthorized,false);assert.equal(b.financialValuationQualified,false);assert.equal(b.fiscalInvoiceArchiveQualified,false);assert.equal(b.externalFiBuQualified,false);assert.equal(b.capacityQualified,false);assert.equal(b.closureEligible,false);assert.equal(b.separateDatabaseIntroduced,false);
 const pkg=load('package.json');assert.equal(pkg.scripts['pan523:test'],'TMPDIR="${TMPDIR:-${RUNNER_TEMP:?PAN523_OWNED_SCRATCH_REQUIRED}}" node scripts/run-pan523-production-tests.mjs');assert.equal(pkg.scripts.pretest.split('npm run pan523:test').length,2);assert.equal(graph.nodes.find(n=>n.id==='repository-integrity').ownedTests.filter(c=>c==='npm run pan523:test').length,1);
 assert.deepEqual(graph.nodes.filter(n=>n.inputs.some(i=>i.path==='src/pan515/trade-state.mjs')).map(n=>n.id),['pan515-native-trade-state-v1']);
});
