// Closed, data-only projection of the existing native Human ledger, not grants.
export type WorkspaceErvHumanActionV1='REVIEW'|'QUERY'|'APPROVE_LOCAL_EVIDENCE_ONLY';
export interface WorkspaceErvHumanReferencesV1 {readonly schemaVersion:'pansphaira.workspace-erv-references/v1';readonly invoiceId:string;readonly orderId:string;readonly positionId:string;readonly receiptIds:readonly string[];readonly quantityUnit:string;readonly invoiceSourcePath:string;readonly invoiceSourceSha256:string}
export interface WorkspaceErvHumanReadV1 {readonly invoiceId:string;readonly nativeRevision:number;readonly proposalRevision:number;readonly proposalDigest:string;readonly state:string;readonly nativeRole:'READER'|'REVIEWER'|'APPROVER';readonly lastEventDigest:string|null;readonly leadingStore:string;readonly references:WorkspaceErvHumanReferencesV1}
function nativeReferences(value:unknown,invoiceId:string):WorkspaceErvHumanReferencesV1 {
 const keys='schemaVersion invoiceId orderId positionId receiptIds quantityUnit invoiceSourcePath invoiceSourceSha256'.split(' '),d=value&&Object.getPrototypeOf(value)===Object.prototype?Object.getOwnPropertyDescriptors(value):null,v=value as Record<string,unknown>,ids=d?.receiptIds&&'value'in d.receiptIds?d.receiptIds.value:undefined;
 const token=(x:unknown,prefix:string)=>typeof x==='string'&&new RegExp('^'+prefix+':[a-z0-9-]{3,64}$').test(x);
 if(!d||Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!Object.hasOwn(d,k))||Object.values(d).some(x=>!x.enumerable||!('value'in x))||v.schemaVersion!=='pansphaira.workspace-erv-references/v1'||v.invoiceId!==invoiceId||!token(v.orderId,'bestellung')||!token(v.positionId,'position')||!Array.isArray(ids)||Object.getPrototypeOf(ids)!==Array.prototype||ids.length>128||Reflect.ownKeys(ids).length!==ids.length+1||Array.from({length:ids.length},(_,i)=>Object.getOwnPropertyDescriptor(ids,String(i))).some(x=>!x||!x.enumerable||!('value'in x)||!token(x.value,'wareneingang'))||new Set(ids).size!==ids.length||typeof v.quantityUnit!=='string'||!/^[A-Z]{1,4}$/.test(v.quantityUnit)||typeof v.invoiceSourcePath!=='string'||!/^contracts\/trade\/[a-z0-9-]+\.json$/.test(v.invoiceSourcePath)||typeof v.invoiceSourceSha256!=='string'||!/^[a-f0-9]{64}$/.test(v.invoiceSourceSha256))throw Error('HUMAN_REFERENCES_DENIED');
 return Object.freeze({...v,receiptIds:Object.freeze([...ids])}) as unknown as WorkspaceErvHumanReferencesV1;
}
export interface WorkspaceErvHumanDecisionV1 {readonly schemaVersion:'pansphaira.erv-human/decision/v1';readonly invoiceId:string;readonly effectId:string;readonly transportId:string;readonly expectedNativeRevision:number;readonly expectedProposalRevision:number;readonly proposalDigest:string;readonly action:WorkspaceErvHumanActionV1}
export function validateWorkspaceErvHumanReadV1(value:unknown,objectId:string,revision:number):WorkspaceErvHumanReadV1{
 const keys='invoiceId nativeRevision proposalRevision proposalDigest state nativeRole lastEventDigest leadingStore persisted bookingAuthorityGranted paymentOrderAuthorized productiveDispatchAuthorized executionAuthorityGranted references'.split(' '),d=value&&Object.getPrototypeOf(value)===Object.prototype?Object.getOwnPropertyDescriptors(value):null,v=value as Record<string,unknown>;
 if(!d||Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!Object.hasOwn(d,k))||Object.values(d).some(x=>!x.enumerable||!('value'in x))||v.invoiceId!==objectId||v.nativeRevision!==revision||!Number.isSafeInteger(v.proposalRevision)||(v.proposalRevision as number)<0||typeof v.proposalDigest!=='string'||!/^[a-f0-9]{64}$/.test(v.proposalDigest)||v.lastEventDigest!==null&&(typeof v.lastEventDigest!=='string'||!/^[a-f0-9]{64}$/.test(v.lastEventDigest))||!['READER','REVIEWER','APPROVER'].includes(v.nativeRole as string)||!['REVIEW_REQUIRED','REVIEWED_LOCAL_EVIDENCE_ONLY','QUERY_PENDING_LOCAL_EVIDENCE_ONLY','APPROVED_LOCAL_EVIDENCE_ONLY','STALE_NATIVE_BASIS_REVIEW_REQUIRED'].includes(v.state as string)||v.leadingStore!=='PAN472_TARGET_SQLITE'||v.persisted!==true||keys.slice(9,13).some(k=>v[k]!==false))throw Error('HUMAN_READ_DENIED');return Object.freeze({...v,references:nativeReferences(v.references,objectId)}) as unknown as WorkspaceErvHumanReadV1;
}
