import type {WorkspaceContextReadbackV1} from './workspace-context-selection-v1.js';
import {validateWorkspaceModuleViewV1,reduceWorkspaceModuleViewV1,type WorkspaceModuleViewV1,type WorkspaceViewDeltaV1,type WorkspaceViewFieldV1} from './workspace-module-view-v1.js';
type Binding=WorkspaceContextReadbackV1['binding'];
export interface WorkspaceAgentPlanV1 {readonly schemaVersion:'pansphaira.workspace-agent/plan-readback/v1';readonly phase:'PLANNED_NOT_DISPATCHED';readonly planHandle:string;readonly planDigest:string;readonly runId:string;readonly binding:Binding;readonly sourceDigest:string;readonly sourceRevisions:{readonly erv:number;readonly human:number};readonly selectedInstanceId:string;readonly expiresAtMs:number;readonly modelMode:'SYNTHETIC_PROBE_ONLY';readonly realModelAcceptance:false;readonly consequence:'BOUNDED_MODEL_VIEW_PROPOSAL_ONLY_NO_SAVE';readonly operations:unknown;readonly personalViewPersistenceProduced:false;readonly businessEffectProduced:false;readonly executionAuthorityGranted:false}
export interface WorkspaceAgentProposalV1 {readonly delta:WorkspaceViewDeltaV1;readonly beforeView:WorkspaceModuleViewV1;readonly afterView:WorkspaceModuleViewV1;readonly beforeDigest:string;readonly afterDigest:string;readonly expectedRevision:number;readonly requiresSeparateNative546PreviewAndConfirmation:true;readonly previewOnly:true;readonly persistenceProduced:false;readonly businessEffectProduced:false}
export interface WorkspaceAgentReadV1 {readonly schemaVersion:'pansphaira.workspace-agent/readback/v1';readonly runId:string;readonly phase:'RESULT_READY'|'OUTCOME_UNCONFIRMED';readonly requestDigest:string;readonly binding:Binding|null;readonly sourceDigest:string|null;readonly sourceRevisions:{readonly erv:number;readonly human:number}|null;readonly modelMode:'SYNTHETIC_PROBE_ONLY';readonly realModelAcceptance:false;readonly proposal:WorkspaceAgentProposalV1|null;readonly text:string;readonly operations:unknown;readonly budget:{readonly model:{readonly committedUnits:number;readonly consumedUnits:number;readonly remainingUnits:number};readonly runtime:{readonly committedUnits:number;readonly consumedUnits:number;readonly remainingUnits:number}};readonly personalViewPersistenceProduced:false;readonly businessEffectProduced:false;readonly executionAuthorityGranted:false}
function deny():never{throw Error('WORKSPACE_AGENT_DTO_DENIED');}
function object(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Object.getPrototypeOf(value)!==Object.prototype)deny();const d=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(d).length!==keys.length||keys.some(k=>!Object.hasOwn(d,k))||Object.values(d).some(x=>!x.enumerable||!('value'in x)))deny();return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}
function digest(x:unknown):string{if(typeof x!=='string'||!/^[a-f0-9]{64}$/.test(x))deny();return x;}
function integer(x:unknown):number{if(!Number.isSafeInteger(x)||(x as number)<0)deny();return x as number;}
function binding(value:unknown,current:Binding,exact=false):Binding{const keys=['origin','tenantId','subjectId','sessionId','instanceId','generation','tabId','epoch'];const v=object(value,keys);if(keys.some(k=>typeof v[k]!==typeof current[k as keyof Binding])||['origin','tenantId','subjectId','instanceId','generation',...(exact?['sessionId','tabId','epoch']:[])].some(k=>v[k]!==current[k as keyof Binding])||typeof v.sessionId!=='string'||!/^session:[a-f0-9]{64}$/.test(v.sessionId)||typeof v.tabId!=='string'||!/^tab:[a-f0-9]{32}$/.test(v.tabId)||integer(v.epoch)<1)deny();return v as unknown as Binding;}
function revisions(value:unknown){const v=object(value,['erv','human']);integer(v.erv);integer(v.human);return v as unknown as {erv:number;human:number};}
function boundary(v:Record<string,unknown>){if(v.modelMode!=='SYNTHETIC_PROBE_ONLY'||v.realModelAcceptance!==false||v.personalViewPersistenceProduced!==false||v.businessEffectProduced!==false||v.executionAuthorityGranted!==false||typeof v.runId!=='string'||!/^operation:ui-[a-f0-9]{48}$/.test(v.runId))deny();const ops=object(v.operations,['cancel','resume']);for(const key of ['cancel','resume']){const o=object(ops[key],['available','reason']);if(o.available!==false||o.reason!==('NO_NATIVE_MODEL_TASK_'+key.toUpperCase()+'_CONTRACT'))deny();}}
export function validateWorkspaceAgentPlanV1(value:unknown,c:WorkspaceContextReadbackV1):WorkspaceAgentPlanV1{const v=object(value,['schemaVersion','phase','planHandle','planDigest','runId','binding','sourceDigest','sourceRevisions','selectedInstanceId','expiresAtMs','modelMode','realModelAcceptance','consequence','operations','personalViewPersistenceProduced','businessEffectProduced','executionAuthorityGranted']);boundary(v);if(v.schemaVersion!=='pansphaira.workspace-agent/plan-readback/v1'||v.phase!=='PLANNED_NOT_DISPATCHED'||typeof v.planHandle!=='string'||!/^task-plan:[a-f0-9]{64}$/.test(v.planHandle)||v.consequence!=='BOUNDED_MODEL_VIEW_PROPOSAL_ONLY_NO_SAVE'||integer(v.expiresAtMs)<=Date.now()||v.expiresAtMs!==c.lease.expiresAtMs||v.selectedInstanceId!==c.selection?.rowId)deny();binding(v.binding,c.binding,true);digest(v.planDigest);digest(v.sourceDigest);revisions(v.sourceRevisions);return Object.freeze(v) as unknown as WorkspaceAgentPlanV1;}
export function validateWorkspaceAgentReadV1(value:unknown,c:WorkspaceContextReadbackV1,fields:readonly WorkspaceViewFieldV1[]):WorkspaceAgentReadV1{const v=object(value,['schemaVersion','runId','phase','requestDigest','binding','sourceDigest','sourceRevisions','modelMode','realModelAcceptance','proposal','text','operations','budget','personalViewPersistenceProduced','businessEffectProduced','executionAuthorityGranted']);boundary(v);if(v.schemaVersion!=='pansphaira.workspace-agent/readback/v1'||!['RESULT_READY','OUTCOME_UNCONFIRMED'].includes(v.phase as string)||typeof v.text!=='string'||new TextEncoder().encode(v.text).length>65536)deny();digest(v.requestDigest);const b=object(v.budget,['model','runtime','reservations']);integer(b.reservations);for(const k of ['model','runtime']){const raw=b[k];if(!raw||typeof raw!=='object'||Array.isArray(raw))deny();const ds=Object.getOwnPropertyDescriptors(raw);for(const name of ['committedUnits','consumedUnits','remainingUnits']){const d=ds[name];if(!d||!('value'in d)||!d.enumerable)deny();integer(d.value);}}
 if(v.phase==='OUTCOME_UNCONFIRMED'){if(v.proposal!==null||v.binding!==null||v.sourceDigest!==null||v.sourceRevisions!==null)deny();}else{binding(v.binding,c.binding);digest(v.sourceDigest);revisions(v.sourceRevisions);const p=object(v.proposal,['delta','beforeView','afterView','beforeDigest','afterDigest','expectedRevision','requiresSeparateNative546PreviewAndConfirmation','previewOnly','persistenceProduced','businessEffectProduced']);if(p.requiresSeparateNative546PreviewAndConfirmation!==true||p.previewOnly!==true||p.persistenceProduced!==false||p.businessEffectProduced!==false)deny();integer(p.expectedRevision);digest(p.beforeDigest);digest(p.afterDigest);const before=validateWorkspaceModuleViewV1(p.beforeView,fields),after=validateWorkspaceModuleViewV1(p.afterView,fields),delta=object(p.delta,['schemaVersion','operations']);if(delta.schemaVersion!=='pansphaira.workspace-module-view/delta/v1'||!Array.isArray(delta.operations)||delta.operations.length!==1||!['MOVE','RESIZE'].includes(delta.operations[0]?.kind)||JSON.stringify(reduceWorkspaceModuleViewV1(before,delta,fields))!==JSON.stringify(after))deny();}
 return Object.freeze(v) as unknown as WorkspaceAgentReadV1;
}
