import {validateWorkspaceContextVerifyV1} from './workspace-context-selection-v1.js';
export type WorkspaceContextVerifyV1=ReturnType<typeof validateWorkspaceContextVerifyV1>;
import {validateBrowserErvReadV1,type BrowserErvReadV1} from './browser-erv-read-v1.js';
export type WorkspaceNavigationOperationV1='SEARCH'|'REQUEST'|'READ'|'ACK';
export interface WorkspaceInvoiceSearchV1 {readonly schemaVersion:'pansphaira.workspace-invoice-search/v1';readonly context:WorkspaceContextVerifyV1;readonly query:string}
export interface WorkspaceNavigationRequestV1 {readonly schemaVersion:'pansphaira.workspace-navigation/request/v1';readonly context:WorkspaceContextVerifyV1;readonly targetHandle:string}
export interface WorkspaceNavigationReadV1 {readonly schemaVersion:'pansphaira.workspace-navigation/read/v1';readonly context:WorkspaceContextVerifyV1;readonly requestHandle:string}
export interface WorkspaceNavigationRenderedV1 {readonly moduleId:'pan.erv';readonly viewId:'pan.erv.view';readonly objectId:string;readonly dataRevision:number;readonly tabId:string;readonly epoch:number}
export interface WorkspaceNavigationRenderAckV1 {readonly schemaVersion:'pansphaira.workspace-navigation/render-ack/v1';readonly context:WorkspaceContextVerifyV1;readonly requestHandle:string;readonly readReceiptHandle:string;readonly rendered:WorkspaceNavigationRenderedV1}
export type WorkspaceNavigationInputV1=WorkspaceInvoiceSearchV1|WorkspaceNavigationRequestV1|WorkspaceNavigationReadV1|WorkspaceNavigationRenderAckV1;
interface NoEffect {readonly executionAuthorityGranted:false;readonly effectsProduced:false}
export interface WorkspaceInvoiceCandidateV1 {readonly targetHandle:string;readonly objectId:string;readonly dataRevision:number;readonly label:string}
export interface WorkspaceInvoiceSearchReadbackV1 extends NoEffect {readonly schemaVersion:'pansphaira.workspace-invoice-search/readback/v1';readonly contextHandle:string;readonly query:string;readonly outcome:'NONE'|'ONE'|'AMBIGUOUS';readonly candidates:readonly WorkspaceInvoiceCandidateV1[];readonly budget:{readonly maxNativeReads:2;readonly maxCandidates:2}}
export interface WorkspaceNavigationTargetV1 {readonly moduleId:'pan.erv';readonly viewId:'pan.erv.view';readonly routeId:'pan.erv.route';readonly path:'/workspace/erv';readonly objectId:string;readonly dataRevision:number}
export interface WorkspaceNavigationRequestReadbackV1 extends NoEffect {readonly schemaVersion:'pansphaira.workspace-navigation/request-readback/v1';readonly requestHandle:string;readonly outcome:'NAVIGATION_REQUESTED';readonly target:WorkspaceNavigationTargetV1;readonly lease:{readonly issuedAtMs:number;readonly expiresAtMs:number};readonly browserRenderConfirmed:false}
export interface WorkspaceNavigationNativeReadbackV1 extends NoEffect {readonly schemaVersion:'pansphaira.workspace-navigation/native-readback/v1';readonly requestHandle:string;readonly readReceiptHandle:string;readonly outcome:'NATIVE_TARGET_READBACK_RECEIVED';readonly invoice:BrowserErvReadV1;readonly browserRenderConfirmed:false}
export interface WorkspaceNavigationRenderReadbackV1 extends NoEffect {readonly schemaVersion:'pansphaira.workspace-navigation/render-readback/v1';readonly requestHandle:string;readonly outcome:'BROWSER_RENDER_ACK_REPORTED';readonly rendered:WorkspaceNavigationRenderedV1;readonly nativeReadVerified:true;readonly serverCertifiedBrowserRender:false}
export type WorkspaceNavigationResultV1=WorkspaceInvoiceSearchReadbackV1|WorkspaceNavigationRequestReadbackV1|WorkspaceNavigationNativeReadbackV1|WorkspaceNavigationRenderReadbackV1;
function denied():never{throw new Error('NAV_INPUT_DENIED');}
function record(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Object.getPrototypeOf(value)!==Object.prototype)return denied();const ds=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(ds).length!==keys.length||Reflect.ownKeys(ds).some(k=>typeof k!=='string'||!keys.includes(k))||Object.values(ds).some(d=>!d.enumerable||!('value'in d)))return denied();return Object.fromEntries(keys.map(k=>[k,ds[k]!.value as unknown]));}
function integer(v:unknown):number{if(!Number.isSafeInteger(v)||(v as number)<1)return denied();return v as number;}
function literal<T extends string|boolean|number>(v:unknown,wanted:T):T{if(v!==wanted)return denied();return wanted;}
function handle(v:unknown,prefix:string):string{if(typeof v!=='string'||!new RegExp('^'+prefix+':[a-f0-9]{64}$').test(v))return denied();return v;}
function invoice(v:unknown):string{if(typeof v!=='string'||!/^AP-PAN516-(MATCHED|PARTIAL)-01$/.test(v))return denied();return v;}
export function validateWorkspaceInvoiceQueryV1(v:unknown):string{if(typeof v!=='string'||!/^[A-Z0-9][A-Z0-9-]{0,63}$/.test(v))return denied();return v;}
export function validateWorkspaceNavigationRenderedV1(value:unknown):WorkspaceNavigationRenderedV1{const v=record(value,['moduleId','viewId','objectId','dataRevision','tabId','epoch']);if(typeof v.tabId!=='string'||!/^tab:[a-f0-9]{32}$/.test(v.tabId))return denied();return Object.freeze({moduleId:literal(v.moduleId,'pan.erv'),viewId:literal(v.viewId,'pan.erv.view'),objectId:invoice(v.objectId),dataRevision:integer(v.dataRevision),tabId:v.tabId,epoch:integer(v.epoch)});}
export function validateWorkspaceNavigationInputV1(operation:WorkspaceNavigationOperationV1,value:unknown):WorkspaceNavigationInputV1{
 const schemas={SEARCH:'pansphaira.workspace-invoice-search/v1',REQUEST:'pansphaira.workspace-navigation/request/v1',READ:'pansphaira.workspace-navigation/read/v1',ACK:'pansphaira.workspace-navigation/render-ack/v1'}as const;
 if(!Object.hasOwn(schemas,operation))return denied();const keys=operation==='SEARCH'?['query']:operation==='REQUEST'?['targetHandle']:operation==='READ'?['requestHandle']:['requestHandle','readReceiptHandle','rendered'];const v=record(value,['schemaVersion','context',...keys]);literal(v.schemaVersion,schemas[operation]);const context=validateWorkspaceContextVerifyV1(v.context);
 if(operation==='SEARCH')return Object.freeze({schemaVersion:schemas.SEARCH,context,query:validateWorkspaceInvoiceQueryV1(v.query)});
 if(operation==='REQUEST')return Object.freeze({schemaVersion:schemas.REQUEST,context,targetHandle:handle(v.targetHandle,'nav-target')});
 if(operation==='READ')return Object.freeze({schemaVersion:schemas.READ,context,requestHandle:handle(v.requestHandle,'nav-request')});
 return Object.freeze({schemaVersion:schemas.ACK,context,requestHandle:handle(v.requestHandle,'nav-request'),readReceiptHandle:handle(v.readReceiptHandle,'nav-read'),rendered:validateWorkspaceNavigationRenderedV1(v.rendered)});
}
function noEffect(v:Record<string,unknown>){return {executionAuthorityGranted:literal(v.executionAuthorityGranted,false),effectsProduced:literal(v.effectsProduced,false)};}
function array(value:unknown):readonly unknown[]{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length>2)return denied();const ds=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(ds).length!==value.length+1||Array.from({length:value.length},(_,i)=>ds[String(i)]).some(d=>!d||!d.enumerable||!('value'in d)))return denied();return Array.from({length:value.length},(_,i)=>ds[String(i)]!.value as unknown);}
export function validateWorkspaceNavigationResultV1(operation:WorkspaceNavigationOperationV1,value:unknown):WorkspaceNavigationResultV1{
 const effects=['executionAuthorityGranted','effectsProduced'];
 if(operation==='SEARCH'){const v=record(value,['schemaVersion','contextHandle','query','outcome','candidates','budget',...effects]);const candidates=Object.freeze(array(v.candidates).map(x=>{const i=record(x,['targetHandle','objectId','dataRevision','label']),objectId=invoice(i.objectId);return Object.freeze({targetHandle:handle(i.targetHandle,'nav-target'),objectId,dataRevision:integer(i.dataRevision),label:literal(i.label,'Rechnungsvorgang '+objectId)});}));if(new Set(candidates.map(c=>c.objectId)).size!==candidates.length||new Set(candidates.map(c=>c.targetHandle)).size!==candidates.length)return denied();const budget=record(v.budget,['maxNativeReads','maxCandidates']);return Object.freeze({schemaVersion:literal(v.schemaVersion,'pansphaira.workspace-invoice-search/readback/v1'),contextHandle:handle(v.contextHandle,'context'),query:validateWorkspaceInvoiceQueryV1(v.query),outcome:literal(v.outcome,candidates.length===0?'NONE':candidates.length===1?'ONE':'AMBIGUOUS'),candidates,budget:Object.freeze({maxNativeReads:literal(budget.maxNativeReads,2),maxCandidates:literal(budget.maxCandidates,2)}),...noEffect(v)});}
 if(operation==='REQUEST'){const v=record(value,['schemaVersion','requestHandle','outcome','target','lease','browserRenderConfirmed',...effects]),t=record(v.target,['moduleId','viewId','routeId','path','objectId','dataRevision']),l=record(v.lease,['issuedAtMs','expiresAtMs']),issuedAtMs=integer(l.issuedAtMs),expiresAtMs=integer(l.expiresAtMs);if(expiresAtMs<=issuedAtMs||expiresAtMs-issuedAtMs>60000)return denied();return Object.freeze({schemaVersion:literal(v.schemaVersion,'pansphaira.workspace-navigation/request-readback/v1'),requestHandle:handle(v.requestHandle,'nav-request'),outcome:literal(v.outcome,'NAVIGATION_REQUESTED'),target:Object.freeze({moduleId:literal(t.moduleId,'pan.erv'),viewId:literal(t.viewId,'pan.erv.view'),routeId:literal(t.routeId,'pan.erv.route'),path:literal(t.path,'/workspace/erv'),objectId:invoice(t.objectId),dataRevision:integer(t.dataRevision)}),lease:Object.freeze({issuedAtMs,expiresAtMs}),browserRenderConfirmed:literal(v.browserRenderConfirmed,false),...noEffect(v)});}
 if(operation==='READ'){const v=record(value,['schemaVersion','requestHandle','readReceiptHandle','outcome','invoice','browserRenderConfirmed',...effects]);return Object.freeze({schemaVersion:literal(v.schemaVersion,'pansphaira.workspace-navigation/native-readback/v1'),requestHandle:handle(v.requestHandle,'nav-request'),readReceiptHandle:handle(v.readReceiptHandle,'nav-read'),outcome:literal(v.outcome,'NATIVE_TARGET_READBACK_RECEIVED'),invoice:validateBrowserErvReadV1(v.invoice),browserRenderConfirmed:literal(v.browserRenderConfirmed,false),...noEffect(v)});}
 if(operation==='ACK'){const v=record(value,['schemaVersion','requestHandle','outcome','rendered','nativeReadVerified','serverCertifiedBrowserRender',...effects]);return Object.freeze({schemaVersion:literal(v.schemaVersion,'pansphaira.workspace-navigation/render-readback/v1'),requestHandle:handle(v.requestHandle,'nav-request'),outcome:literal(v.outcome,'BROWSER_RENDER_ACK_REPORTED'),rendered:validateWorkspaceNavigationRenderedV1(v.rendered),nativeReadVerified:literal(v.nativeReadVerified,true),serverCertifiedBrowserRender:literal(v.serverCertifiedBrowserRender,false),...noEffect(v)});}
 return denied();
}
