import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {originalInvoiceRequestV1,createOriginalInvoiceStoreV1} from '../../src/pan360/original-invoice-input-v1.mjs';
import {Pan396InvoiceBrokerV1,verifyPan396BoundedEvidenceV1} from '../../src/pan396/invoice-broker-v1.mjs';
import {SimplestAtomicS3SqsFakeV1,pan396HighBindingV1} from '../../src/pan396/simplest-fake-v1.mjs';
import {FlociLabHttpV1,md5} from '../../src/pan396/floci-http-v1.mjs';
async function fixture(){const namespace='pan396-'+randomUUID();const binding=pan396HighBindingV1(namespace,'http://localhost:4566/000000000000/'+namespace+'-events');const fake=new SimplestAtomicS3SqsFakeV1(binding);const bytes=originalInvoiceRequestV1().bytes;const put=await fake.put(binding.key,bytes);const broker=new Pan396InvoiceBrokerV1(binding,{readObject:r=>fake.readObject(r)});return {binding,fake,bytes,envelope:put.message,broker};}
const alter=(envelope,fn)=>{const copy=structuredClone(envelope);const body=JSON.parse(copy.body);fn(body);copy.body=JSON.stringify(body);copy.bodyMd5=md5(copy.body);return copy;};
test('explicit fake control reaches unchanged real intake/core and independent bounded evidence readback',async()=>{const f=await fixture();const result=await f.broker.process(f.envelope);assert.equal(result.outcome,'BOUNDED_EVIDENCE_VERIFIED');assert.equal(result.evidence.decision.matchedAmountMinor,1200000);assert(verifyPan396BoundedEvidenceV1(result.evidence));assert.deepEqual(f.broker.statistics,{objectReadAttempts:1,intakeInvocations:1,intakeInserted:1,coreInvocations:1,evidencePersisted:1,independentEvidenceReads:1,reservedKeys:1,reservedEvents:1});assert.equal(result.productivePostingAuthorized,false);assert.equal(result.bookingAuthorityGranted,false);});
for(const [name,reason,mutate] of [
 ['wrong bucket','WRONG_BUCKET_DENIED',m=>alter(m,b=>b.Records[0].s3.bucket.name+='-wrong')],
 ['wrong queue','WRONG_QUEUE_DENIED',m=>({...m,queueUrl:m.queueUrl+'-wrong'})],
 ['foreign namespace','FOREIGN_SCOPE_DENIED',m=>({...m,namespace:m.namespace+'-foreign'})],
 ['foreign key','FOREIGN_KEY_DENIED',m=>alter(m,b=>b.Records[0].s3.object.key='foreign/invoice.txt')],
 ['stale event','STALE_EVENT_DENIED',m=>alter(m,b=>b.Records[0].eventTime='2000-01-01T00:00:00.000Z')],
 ['substituted event metadata','SUBSTITUTED_EVENT_PAYLOAD_DENIED',m=>alter(m,b=>b.Records[0].s3.object.eTag='0'.repeat(32))],
 ['unverified message digest','MESSAGE_DIGEST_DENIED',m=>({...m,body:m.body+' '})],
 ['unknown event operation','EVENT_SYNTAX_DENIED',m=>alter(m,b=>b.Records[0].eventName='ObjectRemoved:Delete')],
 ['unknown event syntax','EVENT_SYNTAX_DENIED',m=>alter(m,b=>b.unadmitted=true)],
 ['unknown envelope authority field','EVENT_ENVELOPE_SHAPE_DENIED',m=>({...m,productivePostingAuthorized:true})],
 ['malformed id is not normalized','EVENT_ENVELOPE_SHAPE_DENIED',m=>({...m,messageId:'-'.repeat(36)})],
 ])test(name+' denies BEFORE provider or core effects',async()=>{const f=await fixture();const result=await f.broker.process(mutate(f.envelope));assert.equal(result.outcome,'DENIED');assert.equal(result.reasonCode,reason);assert.equal(f.broker.statistics.objectReadAttempts,0);assert.equal(f.broker.statistics.coreInvocations,0);});
test('getter envelope is denied without invoking getter',async()=>{const f=await fixture();let n=0;const m={...f.envelope};Object.defineProperty(m,'body',{enumerable:true,get(){n++;return f.envelope.body;}});assert.equal((await f.broker.process(m)).reasonCode,'EVENT_ENVELOPE_SHAPE_DENIED');assert.equal(n,0);});
test('same event is denied after one actual core application',async()=>{const f=await fixture();assert.equal((await f.broker.process(f.envelope)).outcome,'BOUNDED_EVIDENCE_VERIFIED');assert.equal((await f.broker.process(f.envelope)).reasonCode,'DUPLICATE_EVENT_DENIED');assert.equal(f.broker.statistics.coreInvocations,1);});
test('different event for reserved key is conflict and cannot reapply core',async()=>{const f=await fixture();assert.equal((await f.broker.process(f.envelope)).outcome,'BOUNDED_EVIDENCE_VERIFIED');const second=await f.fake.put(f.binding.key,f.bytes);assert.equal((await f.broker.process(second.message)).reasonCode,'KEY_CONFLICT_DENIED');assert.equal(f.broker.statistics.coreInvocations,1);});
test('concurrent event delivery reserves BEFORE provider await; only one core application',async()=>{const f=await fixture();const results=await Promise.all([f.broker.process(f.envelope),f.broker.process(f.envelope)]);assert.equal(results.filter(r=>r.outcome==='BOUNDED_EVIDENCE_VERIFIED').length,1);assert.equal(results.filter(r=>r.reasonCode==='DUPLICATE_EVENT_DENIED').length,1);assert.equal(f.broker.statistics.coreInvocations,1);});
test('stale/substituted stored bytes fail before intake despite valid original event',async()=>{const f=await fixture();f.fake.objects.set(f.binding.key,new Uint8Array([0,1,2]));assert.equal((await f.broker.process(f.envelope)).reasonCode,'STALE_OR_SUBSTITUTED_OBJECT_DENIED');assert.equal(f.broker.statistics.coreInvocations,0);assert.equal(f.broker.statistics.intakeInvocations,0);});
test('missing object readback consumes reservation without core or blind retry',async()=>{const f=await fixture();f.fake.objects.delete(f.binding.key);assert.equal((await f.broker.process(f.envelope)).reasonCode,'MISSING_OBJECT_READBACK');assert.equal((await f.broker.process(f.envelope)).reasonCode,'DUPLICATE_EVENT_DENIED');assert.equal(f.broker.statistics.coreInvocations,0);assert.equal(f.broker.statistics.objectReadAttempts,1);});
test('timeout refuses late object delivery and retains uncertain reservation',async()=>{const f=await fixture();const b=new Pan396InvoiceBrokerV1({...f.binding,deadlineEpochMs:Date.now()+20},{readObject:async r=>{const actual=await f.fake.readObject(r);await new Promise(resolve=>setTimeout(resolve,70));return actual;}});assert.equal((await b.process(f.envelope)).reasonCode,'TIMEOUT');await new Promise(resolve=>setTimeout(resolve,90));assert.equal(b.statistics.intakeInvocations,0);assert.equal(b.statistics.coreInvocations,0);});
test('missing original store readback records landed intake but does not invoke core',async()=>{const f=await fixture();const actualStore=createOriginalInvoiceStoreV1();const b=new Pan396InvoiceBrokerV1(f.binding,{readObject:r=>f.fake.readObject(r),store:{insertIfAbsent:r=>actualStore.insertIfAbsent(r),getByVersionId:async()=>undefined}});const result=await b.process(f.envelope);assert.equal(result.reasonCode,'MISSING_INTAKE_READBACK');assert.equal(result.partialEffects.intakeInserted,true);assert.equal(b.statistics.intakeInserted,1);assert.equal(b.statistics.coreInvocations,0);});
test('missing resulting evidence readback is NOT success and preserves actually landed effects',async()=>{const f=await fixture();const persisted=new Map();const b=new Pan396InvoiceBrokerV1(f.binding,{readObject:r=>f.fake.readObject(r),persistEvidence:async(id,r)=>persisted.set(id,r),readEvidence:async()=>null});const result=await b.process(f.envelope);assert.equal(result.reasonCode,'MISSING_OR_SUBSTITUTED_EVIDENCE_READBACK');assert.equal(result.partialEffects.coreInvoked,true);assert.equal(persisted.size,1);assert.equal((await b.process(f.envelope)).reasonCode,'DUPLICATE_EVENT_DENIED');assert.equal(b.statistics.coreInvocations,1);});
test('late evidence persistence must not produce a successful result after lease deadline',async()=>{const f=await fixture();const persisted=new Map();const b=new Pan396InvoiceBrokerV1({...f.binding,deadlineEpochMs:Date.now()+80},{readObject:r=>f.fake.readObject(r),persistEvidence:async(id,r)=>{await new Promise(resolve=>setTimeout(resolve,160));persisted.set(id,r);},readEvidence:async id=>persisted.get(id)});const result=await b.process(f.envelope);assert.equal(result.outcome,'DENIED');assert.equal(result.reasonCode,'TIMEOUT');});
test('late independent evidence readback must not produce success after lease deadline',async()=>{const f=await fixture();const persisted=new Map();const b=new Pan396InvoiceBrokerV1({...f.binding,deadlineEpochMs:Date.now()+80},{readObject:r=>f.fake.readObject(r),persistEvidence:async(id,r)=>persisted.set(id,r),readEvidence:async id=>{await new Promise(resolve=>setTimeout(resolve,160));return persisted.get(id);}});const result=await b.process(f.envelope);assert.equal(result.outcome,'DENIED');assert.equal(result.reasonCode,'TIMEOUT');});
test('fake negative queue comparison is explicit atomic substitution, not claimed native result',async()=>{const f=await fixture();f.fake.purge();const r=await f.fake.put(f.binding.namespace+'/partial.txt',f.bytes);assert.equal(r.outcome,'FAKE_QUEUE_MISSING_NO_OBJECT_EFFECT');assert.equal(f.fake.objects.size,0);});
test('transport rejects undeclared operation, scope, relabelled method and credential injection before fetch',async()=>{const f=await fixture();const client=new FlociLabHttpV1('http://172.19.0.2:4566',{namespace:f.binding.namespace});await assert.rejects(client.s3('PutObjectAcl',f.binding.bucket,f.binding.key),/OPERATION_NOT_ADMITTED/);await assert.rejects(client.s3('PutObject',f.binding.bucket,f.binding.key,{method:'DELETE'}),/OPERATION_METHOD_DENIED/);await assert.rejects(client.s3('GetObject','foreign',f.binding.key),/BUCKET_SCOPE_DENIED/);await assert.rejects(client.s3('GetObject',f.binding.bucket,f.binding.key,{headers:{Authorization:'unadmitted'}}),/CREDENTIAL_OR_HEADER_INJECTION_DENIED/);await assert.rejects(client.sqs('DeleteQueue',{QueueUrl:'http://localhost:4566/foreign'}),/QUEUE_SCOPE_DENIED/);await assert.rejects(client.sqs('SendMessage',{QueueUrl:f.binding.queueUrl}),/OPERATION_NOT_ADMITTED/);assert.equal(client.request,undefined);assert.equal(client.raw,undefined);});
