import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { nativeFixture527, request527 } from "../pan527/helpers.mjs";
import { financeFixture } from "../pan519/native-fixture.mjs";
import { nativeRows } from "../fixtures/pan515/native-trade-fixture.mjs";
import { createNativeErvReadAdapterV1 } from "../../src/pan541/native-erv-read-adapter.mjs";

test("PUI-01-AC03 actual shared-browser navigation reads both native Setup/ERV backends and opens the selected invoice panel", async () => {
  assert.ok(existsSync(new URL("../../src/pan541/workspace-browser.mjs", import.meta.url)), "PAN541_REAL_SHARED_BROWSER_VIEWS_NOT_IMPLEMENTED");
  assert.ok(process.env.PAN527_BROWSER_MODULE && process.env.PAN527_CERTUTIL && process.env.PAN541_BROWSER_EVIDENCE, "owned real browser and durable screenshot directory required; no skipped test");
  const { enableWorkspaceBrowserV1 } = await import("../../src/pan541/workspace-browser.mjs");
  const { chromium } = await import(process.env.PAN527_BROWSER_MODULE);
  const tls = await nativeFixture527(); let native; let browser; let workspace;
  try {
    native = await financeFixture();
    const before = JSON.stringify(nativeRows(native.root, "SELECT revision,effect_key,command,event FROM pan516_events ORDER BY revision"));
    const reader = createNativeErvReadAdapterV1({ tenantId: "tenant-a", root: native.root });
    workspace = enableWorkspaceBrowserV1({ optIn: true, gateway: tls.gateway, tenantId: "tenant-a", origin: tls.origin, nativeReader: reader });
    const home = join(tls.root, "browser-home"); const nss = join(home, ".pki/nssdb"); mkdirSync(nss, { recursive: true, mode: 0o700 });
    execFileSync(process.env.PAN527_CERTUTIL, ["-N", "--empty-password", "-d", "sql:" + nss], { stdio: "ignore" });
    execFileSync(process.env.PAN527_CERTUTIL, ["-A", "-d", "sql:" + nss, "-n", "PAN541 isolated native test CA", "-t", "CT,C,C", "-i", tls.options.tls.certPath], { stdio: "ignore" });
    browser = await chromium.launch({ headless: true, env: { ...process.env, HOME: home }, args: ["--no-proxy-server", "--disable-background-networking"] });
    const context = await browser.newContext({ ignoreHTTPSErrors: false, viewport: { width: 1280, height: 900 } });
    await context.route("**/*", route => new URL(route.request().url()).origin === tls.origin ? route.continue() : route.abort());
    const issued = tls.gateway.sessionAdapter("tenant-a").issueOwnerSession({ subjectId: "synthetic-shell-browser-reader", role: "reader", expiresAtMs: Date.now() + 60000 });
    await context.addCookies([{ name: "__Host-pan527-session", value: issued.cookieHeader.split("=")[1], url: tls.origin, secure: true, httpOnly: true, sameSite: "Strict" }]);
    const page = await context.newPage(); const errors = []; const requests = [];
    page.on("pageerror", error => errors.push(error.message)); page.on("request", r => requests.push({ method: r.method(), path: new URL(r.url()).pathname }));
    await page.goto(tls.origin + "/t/tenant-a/workspace");
    await page.getByRole("heading", { name: "Einrichtung und Betriebszustand" }).waitFor();
    await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();
    assert.ok(requests.some(r => r.path === "/t/tenant-a/api/status"));
    assert.equal(await page.evaluate(() => window.isSecureContext), true); assert.equal(await page.evaluate(() => document.cookie), "");
    await page.screenshot({ path: join(process.env.PAN541_BROWSER_EVIDENCE, "desktop-setup.png"), fullPage: true });
    await page.getByRole("button", { name: "Eingangsrechnungsprüfung — nur lesen", exact: true }).click();
    await page.locator('[data-backend="erv"][data-outcome="READBACK_RECEIVED"]').waitFor();
    assert.ok(requests.some(r => r.path === "/t/tenant-a/workspace/erv"));
    assert.match(await page.locator("main").innerText(), /AP-PAN516-MATCHED-01/);
    assert.match(await page.locator("main").innerText(), /600,00/);
    await page.getByRole("button", { name: "Informationspanel zum aktuellen Vorgang öffnen", exact: true }).click();
    await page.getByRole("heading", { name: "Informationen zum aktuellen Rechnungsvorgang" }).waitFor();
    assert.match(await page.locator('[id="shell.panels"]').innerText(), /AP-PAN516-MATCHED-01/);
    await page.screenshot({ path: join(process.env.PAN541_BROWSER_EVIDENCE, "desktop-erv-panel.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: join(process.env.PAN541_BROWSER_EVIDENCE, "390-erv-panel.png"), fullPage: true });
    const titleTailLines = await page.locator("main h1").evaluate(heading => {
      const node = heading.firstChild; const range = document.createRange();
      range.setStart(node, node.textContent.length - 7); range.setEnd(node, node.textContent.length);
      return range.getClientRects().length;
    });
    assert.equal(titleTailLines, 1, "LONG_GERMAN_HEADING_STRANDS_FINAL_G_ON_390PX");
    const dimensions = await page.evaluate(() => ({ viewport: innerWidth, width: document.documentElement.scrollWidth, controls: [...document.querySelectorAll("button:not(:disabled),a")].filter(e => e.getClientRects().length).map(e => { const r = e.getBoundingClientRect(); return { label: e.textContent, x: r.x, right: r.right, width: r.width, height: r.height }; }) }));
    assert.ok(dimensions.width <= dimensions.viewport); assert.ok(dimensions.controls.every(c => c.width > 0 && c.height > 0 && c.x >= 0 && c.right <= dimensions.viewport));
    await page.getByRole("button", { name: "Einrichtung und Betriebszustand", exact: true }).click();
    await page.locator('[data-backend="setup"][data-outcome="READBACK_RECEIVED"]').waitFor();
    assert.equal(await page.locator('[id="shell.panels"]').isVisible(), false);
    await page.screenshot({ path: join(process.env.PAN541_BROWSER_EVIDENCE, "390-setup.png"), fullPage: true });
    const skip = page.getByRole("link", { name: "Zum Arbeitsbereich", exact: true });
    const beforeSkipHash = await page.evaluate(() => location.hash);
    await skip.focus(); await skip.press("Enter");
    assert.equal(await page.evaluate(() => location.hash), beforeSkipHash, "KEYBOARD_SKIP_LINK_MISROUTED_AS_DEEP_LINK");
    assert.equal(await page.locator("main h1").innerText(), "Einrichtung und Betriebszustand", "KEYBOARD_SKIP_LINK_MISROUTED_AS_DEEP_LINK");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "shell.main");
    assert.equal(JSON.stringify(nativeRows(native.root, "SELECT revision,effect_key,command,event FROM pan516_events ORDER BY revision")), before);
    assert.deepEqual(errors, []);
    console.log("PAN541 actual isolated Chromium " + browser.version() + "; verified private CA; two bound native backend views; actual leading history unchanged; " + JSON.stringify({ requests, dimensions }));
    await context.close();
  } finally { await browser?.close(); workspace?.close(); native?.close(); await tls.close(); }
});
